import type { CompanyCopy } from './types';

export const it: CompanyCopy = {
  home:'Home',breadcrumb:'Percorso di navigazione',contents:'In questa pagina',privacy:'Informativa sulla protezione dei dati',portrait:'Ritratto',groupPhoto:'Foto del team',photoPending:'La vera foto approvata sarà aggiunta prossimamente.',
  labels:{about:'Il nostro approccio',team:'Team',contact:'Contatti',faq:'Domande frequenti'},
  pages:{
    about:{title:'Il nostro approccio: verificare personalmente, mettere in contatto.',intro:'PvPro.ch è una piattaforma svizzera indipendente di confronto e intermediazione. Mettiamo i proprietari in contatto con imprese fotovoltaiche adatte, gratuitamente e senza impegno.',description:'L’approccio di PvPro.ch: verifica personale, massimo tre partner installatori, finanziamento trasparente e la nostra storia da ottobre 2025.'},
    team:{title:'Le persone dietro PvPro.ch.',intro:'Tre persone, responsabilità ben definite. Accompagniamo personalmente il percorso dall’acquisizione dei clienti alla qualificazione telefonica fino al contatto con gli installatori.',description:'Conosci Elia Alacam, Mario Kopar e Marcus Tezel, il team di tre persone di PvPro.ch, e le loro effettive responsabilità.'},
    contact:{title:'Hai una domanda? Parliamone.',intro:'Stai progettando un impianto fotovoltaico, hai una domanda sulla tua richiesta o vuoi collaborare come installatore? Il nostro team è raggiungibile per telefono, WhatsApp ed e-mail.',description:'Contatta PvPro.ch: anfrage@pvpro.ch e +41 76 270 38 87. Ogni giorno 08:00–20:00, quattro lingue, sede a Lugaggia.'},
    faq:{title:'Risposte chiare alle tue domande.',intro:'Che cosa è gratuito? Chi riceve la tua richiesta? Chi è responsabile dell’installazione? Queste 20 risposte spiegano il nostro servizio, il confronto e le tue possibilità.',description:'20 risposte su PvPro.ch: costi, procedura, scelta dei partner, dati, ritiro della richiesta, preventivi e responsabilità per le garanzie.'}
  },
  quote:'Richiedi preventivi solari',quoteTitle:'Una richiesta per il tuo progetto solare.',quoteText:'Usa il nostro modulo di richiesta esistente. Verifichiamo i tuoi dati e inoltriamo le richieste idonee a un massimo di tre partner adatti. Gratuito e senza obbligo di accettare un preventivo; il numero effettivo dipende da luogo, progetto e disponibilità.',
  facts:[{value:'Ottobre 2025',label:'Fondazione di PvPro.ch'},{value:'30+',label:'Imprese partner nel mercato fotovoltaico svizzero'},{value:'3',label:'Persone nel team di PvPro.ch'},{value:'20+ anni',label:'Esperienza nel settore nella rete dei partner installatori — non l’età di PvPro.ch'}],
  about:{
    title:'Un impianto adatto inizia dalla comprensione delle possibilità.',
    paragraphs:['Quale impianto è adatto alla mia casa? Come si differenziano prezzi e prestazioni? Di quale installatore fidarsi e come riconoscere un preventivo equo? Queste domande rendono spesso difficile la ricerca di un impianto fotovoltaico.','PvPro.ch vuole rendere la ricerca più semplice, trasparente e accessibile. Invece di cercare e contattare diversi installatori, basta un’unica richiesta. Puoi richiedere fino a tre preventivi gratuitamente e senza impegno.','Verifichiamo la richiesta e la inoltriamo a partner adatti che lavorano nel luogo del progetto. Trasparenza, comunicazione personale e qualità dei contatti trasmessi sono al centro del nostro lavoro.'],
    storyTitle:'La nostra storia: da un’osservazione a una piattaforma.',
    story:['Dal 2023 Elia Alacam lavora nel settore fotovoltaico svizzero. Ha collaborato, tra gli altri, con Green Solar Energy, acquisendo esperienza pratica con imprese solari, acquisizione di clienti e sfide del mercato svizzero.','Ha osservato due lati dello stesso problema: i proprietari faticavano a trovare le imprese adatte e a confrontare i preventivi. Buone imprese di installazione cercavano nuovi clienti e progetti concreti nelle loro aree di attività.','L’idea di riunire entrambe le parti su una piattaforma centrale è nata durante un soggiorno a Bali. Nell’ottobre 2025 Elia Alacam, fondatore e CEO di NOBA Media Sagl, ha lanciato PvPro.ch.','Il progetto imprenditoriale è diventato una piattaforma di intermediazione attiva in tutta la Svizzera, con oltre 30 imprese partner e un team di tre persone. La visione rimane facilitare l’accesso dei proprietari a preventivi adatti e offrire nuove opportunità commerciali agli installatori.'],
    principlesTitle:'Come lavoriamo.',
    principles:[
      {title:'Verifica personale, non inoltro automatico',text:'Non inoltriamo ogni questionario senza verificarlo. Il team chiama gli interessati, conferma il loro interesse e controlla i dati dell’immobile, le aspettative del proprietario e i tempi previsti. Vogliamo così fornire ai partner richieste pertinenti e mettere i proprietari in contatto con imprese adatte al progetto.'},
      {title:'Massimo tre imprese per richiesta',text:'Il confronto richiede diverse possibilità, non innumerevoli chiamate. Ogni richiesta viene inoltrata a non più di tre partner adatti, per confrontare con chiarezza prezzi, prestazioni, componenti e garanzie. Fino a tre preventivi sono possibili, non garantiti.'},
      {title:'Gratuito e senza impegno',text:'I proprietari non pagano per la richiesta, l’intermediazione o il confronto. Non c’è obbligo di accettare un preventivo o installare un impianto. La decisione resta sempre tua.'},
      {title:'Una rete di oltre 30 imprese partner',text:'I partner lavorano in diversi cantoni e permettono di gestire richieste dalla Svizzera tedesca, dalla Svizzera romanda e dal Ticino. Nella rete dei partner installatori è presente esperienza di oltre 20 anni nel settore. Questo dato non riguarda l’età o l’esperienza propria di PvPro.ch.'},
      {title:'Contatto diretto con persone reali',text:'Il nostro piccolo team gestisce personalmente la prima richiesta, la qualificazione telefonica e la collaborazione con gli installatori. Vogliamo essere raggiungibili da proprietari e partner e costruire relazioni durature basate sulla fiducia.'}
    ],
    selectionTitle:'Come scegliamo i partner installatori.',selectionIntro:'Non tutte le imprese diventano automaticamente partner. Prima della collaborazione cerchiamo di formarci un quadro il più completo possibile dell’impresa fotovoltaica, considerando:',
    criteria:[{title:'Contesto aziendale',text:'Verifichiamo che l’impresa sia effettivamente attiva nel fotovoltaico e ci informiamo sulla sua attività commerciale.'},{title:'Recensioni dei clienti',text:'Esaminiamo valutazioni pubbliche ed esperienze dei clienti precedenti.'},{title:'Referenze e progetti',text:'Quando disponibili, consideriamo lavori completati e progetti di riferimento.'},{title:'Attività nel luogo del progetto',text:'Verifichiamo in quali cantoni e località l’installatore accetta effettivamente progetti.'},{title:'Professionalità',text:'Consideriamo comunicazione, affidabilità e impressione professionale complessiva.'},{title:'Reperibilità e collaborazione',text:'Ci aspettiamo comunicazione professionale e un trattamento rispettoso degli interessati.'}],
    feedback:'Anche dopo l’inizio della collaborazione prestiamo attenzione alle esperienze e ai riscontri ricevuti. Problemi o reclami ripetuti possono portarci a rivedere la collaborazione. L’obiettivo è una rete affidabile, non il maggior numero possibile di partner.',
    disclaimer:'La selezione non sostituisce una certificazione tecnica indipendente e non garantisce l’esecuzione del progetto. Consulenza, preventivi e lavori di installazione sono responsabilità delle rispettive imprese.',
    modelTitle:'Come finanziamo il servizio gratuito.',
    model:['PvPro.ch è completamente gratuito per i proprietari. Le nostre entrate provengono dalle imprese fotovoltaiche che pagano per contatti clienti qualificati.','Il team verifica la richiesta e, se idonea, la inoltra a un massimo di tre partner adatti. Queste imprese pagano per i contatti qualificati ricevuti. Il modello finanzia il servizio gratuito di intermediazione.','PvPro.ch non vende né installa impianti solari. Preventivi ed eventuali contratti vengono concordati direttamente tra te e l’impresa installatrice. Il pagamento dei partner non ti obbliga ad accettare un preventivo. Vogliamo permettere un confronto trasparente e semplice.']
  },
  team:{
    title:'Un team impegnato e vicino ai clienti.',intro:'La direzione sviluppa la piattaforma e i rapporti con i partner. Gli altri membri qualificano le richieste in entrata e pianificano e ottimizzano le campagne pubblicitarie digitali. Accompagniamo così personalmente l’intero processo di intermediazione.',
    people:[
      {name:'Elia Alacam',role:'Fondatore & CEO',bio:['Elia Alacam è il fondatore di PvPro.ch e amministratore di NOBA Media Sagl. Dal 2023 lavora professionalmente nel mercato fotovoltaico svizzero e ha acquisito esperienza pratica collaborando con Green Solar Energy.','Ha sviluppato una comprensione delle esigenze di proprietari e installatori e delle sfide dell’acquisizione di clienti nel settore solare. Nell’ottobre 2025 ha fondato PvPro.ch per portare queste esperienze nella propria piattaforma.','Oggi Elia è responsabile dello sviluppo strategico e operativo, dell’acquisizione di nuovi partner, della gestione delle collaborazioni esistenti e dell’ampliamento della piattaforma.','Si concentra sul dialogo diretto con gli installatori e sulla costruzione di rapporti commerciali duraturi. Il suo obiettivo è sviluppare PvPro.ch come punto di riferimento affidabile e consolidato per il confronto fotovoltaico in Svizzera.']},
      {name:'Mario Kopar',role:'Specialista nella qualificazione delle richieste clienti',bio:['Mario Kopar si occupa della qualificazione telefonica e dell’assistenza alle richieste in entrata. È uno dei primi interlocutori dei proprietari che manifestano interesse per un impianto fotovoltaico tramite la piattaforma.','Contatta personalmente gli interessati, verifica i dati e raccoglie le informazioni essenziali: tipo di immobile, interesse per impianto solare o accumulo, aspettative personali e tempi previsti.','La comunicazione diretta contribuisce a fornire ai partner richieste il più possibile complete e pertinenti. Mario gestisce anche il contatto telefonico e il numero WhatsApp pubblico di PvPro.ch.','Le sue responsabilità uniscono comunicazione con i clienti, qualificazione accurata e sostegno operativo all’intermediazione.']},
      {name:'Marcus Tezel',role:'Responsabile della pubblicità digitale',bio:['Marcus Tezel è responsabile del marketing digitale e delle campagne pubblicitarie di PvPro.ch. Pianifica, gestisce e ottimizza continuamente campagne online, soprattutto sulle piattaforme Meta, tra cui Facebook e Instagram.','Sviluppa e attua strategie pubblicitarie, analizza i risultati e migliora costantemente le attività. L’obiettivo è raggiungere proprietari con interesse concreto nel fotovoltaico e informarli sulle possibilità di confronto.','Il monitoraggio degli indicatori di rendimento e l’ottimizzazione mirata sostengono un’acquisizione di clienti efficiente e sostenibile. Il suo lavoro è parte del modello commerciale e dello sviluppo continuo della piattaforma.']}
    ],responsibilitiesTitle:'Intermediazione e installazione hanno responsabilità diverse.',responsibilities:'Il team accompagna l’intermediazione. Consulenza tecnica, preventivi vincolanti, progettazione, installazione e servizi concordati sono compito dell’installatore. Il contratto di installazione viene stipulato direttamente tra te e l’impresa.'
  },
  contact:{general:'Domande generali & collaborazioni',requests:'Domande sulla tua richiesta',phone:'Telefono',address:'Indirizzo aziendale',country:'Svizzera',canton:'Ticino',availability:'Quando siamo raggiungibili',daily:'Ogni giorno 08:00–20:00',timing:'Cerchiamo di rispondere tempestivamente a richieste e messaggi. I tempi possono variare in base al numero di richieste ricevute. Non garantiamo volutamente un tempo di risposta fisso.',mario:'Mario Kopar gestisce il numero pubblico di telefono e WhatsApp.',languagesTitle:'Quattro lingue. Un team per la Svizzera.',languagesIntro:'Assistiamo proprietari e partner in tutta la Svizzera. Puoi contattarci in una di queste quattro lingue:',languages:['Tedesco','Italiano','Francese','Inglese'],locationTitle:'La nostra sede e il nostro modo di lavorare.',location:['PvPro.ch / NOBA Media Sagl è gestita da Lugaggia, in Ticino. L’attività è organizzata digitalmente e per telefono. Comunichiamo principalmente tramite la piattaforma, telefono, WhatsApp ed e-mail.','L’indirizzo aziendale non è un negozio aperto al pubblico con normale accesso dei clienti. Non serve una visita personale per utilizzare i servizi.'],partnerTitle:'Vuoi diventare partner installatore?',partnerText:'Desideriamo conoscere imprese fotovoltaiche professionali interessate a contatti clienti qualificati nelle proprie aree di attività. Scrivici per informazioni sulla collaborazione e sulle condizioni.',existingTitle:'Hai già inviato una richiesta?',existingText:'Per domande su una richiesta esistente o per ritirarla, chiamaci o scrivi ad anfrage@pvpro.ch. Indica l’indirizzo e-mail usato nella richiesta. L’informativa sulla protezione dei dati spiega il loro trattamento.'},
  faq:{groupTitles:['Servizio, costi & decisione','Richiesta, contatto & dati','Partner & disponibilità','Progetto, preventivi & responsabilità'],helpTitle:'Hai ancora una domanda?',helpText:'Il team ti aiuta con la piattaforma o la richiesta. Per domande tecniche e dettagli di un preventivo specifico rivolgiti alla rispettiva impresa installatrice.'}
};
