import type { CompanyCopy } from './types';

export const fr: CompanyCopy = {
  home:'Accueil',breadcrumb:'Fil d’Ariane',contents:'Sur cette page',privacy:'Déclaration de protection des données',portrait:'Portrait',groupPhoto:'Photo de l’équipe',photoPending:'La véritable photo approuvée sera ajoutée prochainement.',
  labels:{about:'Notre approche',team:'Équipe',contact:'Contact',faq:'Questions fréquentes'},
  pages:{
    about:{title:'Notre approche : vérifier personnellement, mettre en relation.',intro:'PvPro.ch est une plateforme suisse indépendante de comparaison et de mise en relation. Nous aidons les propriétaires à trouver des entreprises photovoltaïques adaptées, gratuitement et sans engagement.',description:'L’approche de PvPro.ch : vérification personnelle, trois partenaires au maximum, financement transparent et histoire depuis octobre 2025.'},
    team:{title:'Les personnes derrière PvPro.ch.',intro:'Trois personnes, des responsabilités bien définies. Nous accompagnons personnellement le parcours, de l’acquisition de clients à la mise en relation, en passant par la qualification téléphonique.',description:'Découvrez Elia Alacam, Mario Kopar et Marcus Tezel, les trois membres de l’équipe PvPro.ch, et leurs responsabilités réelles.'},
    contact:{title:'Une question ? Parlons-en.',intro:'Vous préparez un projet photovoltaïque, avez une question sur votre demande ou souhaitez devenir partenaire installateur ? Notre équipe est joignable par téléphone, WhatsApp et e-mail.',description:'Contact PvPro.ch : anfrage@pvpro.ch, +41 76 270 38 87. Tous les jours de 08 h à 20 h, quatre langues, adresse à Lugaggia.'},
    faq:{title:'Des réponses claires à vos questions.',intro:'Qu’est-ce qui est gratuit ? Qui reçoit votre demande ? Qui est responsable de l’installation ? Ces 20 réponses expliquent notre service, la comparaison et vos possibilités.',description:'20 réponses sur PvPro.ch : coûts, fonctionnement, sélection des partenaires, données, retrait d’une demande, offres et responsabilités en matière de garanties.'}
  },
  quote:'Demander des offres solaires',quoteTitle:'Une demande pour votre projet solaire.',quoteText:'Utilisez notre formulaire de demande existant. Nous vérifions vos informations et transmettons les demandes appropriées à trois partenaires adaptés au maximum. Gratuit et sans obligation d’accepter une offre ; le nombre effectif dépend du lieu, du projet et des disponibilités.',
  facts:[{value:'Octobre 2025',label:'Création de PvPro.ch'},{value:'30+',label:'Entreprises partenaires sur le marché photovoltaïque suisse'},{value:'3',label:'Personnes dans l’équipe de PvPro.ch'},{value:'20+ ans',label:'Expérience dans le réseau des partenaires installateurs — et non l’âge de PvPro.ch'}],
  about:{
    title:'Choisir une installation adaptée commence par comprendre les possibilités.',
    paragraphs:['Quelle installation convient à ma maison ? Comment les prix et les prestations se distinguent-ils ? À quel installateur faire confiance et comment reconnaître une offre équitable ? Ces questions compliquent souvent la recherche d’une installation photovoltaïque.','PvPro.ch souhaite rendre cette recherche plus simple, transparente et accessible. Au lieu de rechercher et de contacter plusieurs installateurs, vous soumettez une seule demande. Vous pouvez demander jusqu’à trois offres gratuitement et sans engagement.','Nous vérifions votre demande puis la transmettons à des partenaires adaptés qui interviennent au lieu de votre projet. Nous accordons de l’importance à la transparence, à la communication personnelle et à la qualité des contacts transmis.'],
    storyTitle:'Notre histoire : d’un constat à une plateforme.',
    story:['Depuis 2023, Elia Alacam travaille dans le secteur photovoltaïque suisse. Il a notamment collaboré avec Green Solar Energy et acquis une expérience pratique des entreprises solaires, de l’acquisition de clients et des défis du marché suisse.','Il a observé deux facettes d’un même problème : des propriétaires peinaient à trouver les bonnes entreprises et à comparer les offres. De bonnes entreprises d’installation recherchaient de nouveaux clients et des projets concrets dans leurs zones d’intervention.','L’idée de réunir ces deux parties sur une plateforme centrale est née lors d’un séjour à Bali. En octobre 2025, Elia Alacam, fondateur et CEO de NOBA Media Sagl, a lancé PvPro.ch.','Le projet entrepreneurial est devenu une plateforme de mise en relation active dans toute la Suisse, avec plus de 30 entreprises partenaires et une équipe de trois personnes. Notre vision reste de faciliter l’accès des propriétaires à des offres adaptées et de créer des possibilités commerciales pour les installateurs.'],
    principlesTitle:'Notre façon de travailler.',
    principles:[
      {title:'Une vérification personnelle, pas une transmission automatique',text:'Nous ne transmettons pas chaque questionnaire sans le vérifier. Notre équipe appelle les personnes intéressées, confirme leur intérêt et examine les informations sur le bien, leurs attentes et le calendrier envisagé. Nous souhaitons ainsi fournir aux partenaires des demandes pertinentes et mettre les propriétaires en contact avec des entreprises adaptées à leur projet.'},
      {title:'Trois entreprises au maximum par demande',text:'Comparer nécessite plusieurs possibilités, pas une multitude d’appels. Chaque demande est transmise à trois partenaires adaptés au maximum. Vous pouvez ainsi comparer les prix, prestations, composants et garanties de manière lisible. Jusqu’à trois offres sont possibles, mais ne sont pas garanties.'},
      {title:'Gratuit et sans engagement',text:'Les propriétaires ne paient ni la demande, ni la mise en relation, ni la comparaison. Aucune obligation d’accepter une offre ou de faire installer des panneaux solaires. La décision vous appartient toujours.'},
      {title:'Un réseau de plus de 30 entreprises partenaires',text:'Nos partenaires interviennent dans différents cantons, ce qui permet de traiter des demandes de Suisse alémanique, de Suisse romande et du Tessin. Le réseau des partenaires installateurs réunit une expérience de plus de 20 ans dans le secteur. Cette indication ne concerne ni l’âge ni l’expérience propre de PvPro.ch.'},
      {title:'Un contact direct avec de vrais interlocuteurs',text:'Notre petite équipe s’occupe elle-même des premières demandes, de la qualification téléphonique et de la collaboration avec les installateurs. Nous souhaitons être personnellement accessibles aux propriétaires et aux partenaires et construire des relations durables et de confiance.'}
    ],
    selectionTitle:'Comment nous sélectionnons nos partenaires.',selectionIntro:'Chaque entreprise ne devient pas automatiquement partenaire. Avant de collaborer, nous essayons de nous faire une idée aussi complète que possible de l’entreprise photovoltaïque, notamment à travers :',
    criteria:[{title:'Le parcours de l’entreprise',text:'Nous vérifions qu’elle est réellement active dans le photovoltaïque et nous nous renseignons sur son activité commerciale.'},{title:'Les avis clients',text:'Nous consultons les évaluations publiques et les expériences d’anciens clients.'},{title:'Les références et les projets',text:'Dans la mesure où ils sont disponibles, nous examinons les travaux réalisés et les projets de référence.'},{title:'L’activité au lieu du projet',text:'Nous vérifions dans quels cantons et localités l’installateur accepte effectivement des projets.'},{title:'Le professionnalisme',text:'Nous considérons la communication, la fiabilité et l’impression professionnelle générale.'},{title:'La disponibilité et la collaboration',text:'Nous attendons une communication professionnelle et un comportement respectueux envers les personnes intéressées.'}],
    feedback:'Après le début de la collaboration, nous restons attentifs aux expériences et aux retours reçus. Des problèmes ou plaintes répétés peuvent nous conduire à réexaminer la collaboration. Notre objectif est un réseau fiable, pas le plus grand nombre de partenaires.',
    disclaimer:'Cette sélection ne remplace pas une certification technique indépendante et ne garantit pas la réalisation du projet. Les conseils, les offres et les travaux d’installation restent sous la responsabilité des entreprises concernées.',
    modelTitle:'Comment le service gratuit est financé.',
    model:['PvPro.ch est entièrement gratuit pour les propriétaires. Nos revenus proviennent des entreprises photovoltaïques qui paient pour des contacts clients qualifiés.','Notre équipe vérifie la demande et, si elle convient, la transmet à trois partenaires adaptés au maximum. Ces entreprises paient pour les contacts qualifiés reçus. Ce modèle finance notre service gratuit de mise en relation.','PvPro.ch ne vend ni n’installe de systèmes solaires. Les offres et les éventuels contrats sont convenus directement entre vous et l’entreprise d’installation. Le paiement des partenaires ne vous oblige pas à accepter une offre. Notre objectif est une comparaison transparente et simple.']
  },
  team:{
    title:'Une équipe impliquée, proche des clients.',intro:'La direction développe la plateforme et les relations avec les partenaires. Les autres membres qualifient les demandes entrantes et planifient et optimisent les campagnes publicitaires numériques. Nous accompagnons ainsi nous-mêmes l’ensemble du processus de mise en relation.',
    people:[
      {name:'Elia Alacam',role:'Fondateur & CEO',bio:['Elia Alacam est le fondateur de PvPro.ch et le directeur de NOBA Media Sagl. Depuis 2023, il travaille dans le marché photovoltaïque suisse et a acquis une expérience pratique en collaborant avec Green Solar Energy.','Il a développé une compréhension des besoins des propriétaires et des installateurs ainsi que des défis de l’acquisition de clients dans le solaire. En octobre 2025, il a créé PvPro.ch pour mettre cette expérience au service de sa propre plateforme.','Aujourd’hui, Elia est responsable du développement stratégique et opérationnel, de l’acquisition de nouveaux partenaires, du suivi des collaborations existantes et du développement de la plateforme.','Il se concentre sur les échanges directs avec les installateurs et sur les relations commerciales durables. Son objectif est de développer PvPro.ch comme un interlocuteur fiable et établi pour la comparaison photovoltaïque en Suisse.']},
      {name:'Mario Kopar',role:'Spécialiste de la qualification des demandes clients',bio:['Mario Kopar s’occupe de la qualification téléphonique et du suivi des demandes clients entrantes. Il est l’un des premiers interlocuteurs des propriétaires qui expriment leur intérêt pour une installation photovoltaïque sur la plateforme.','Il contacte personnellement les personnes intéressées, vérifie leurs informations et rassemble les éléments essentiels du projet : type de bien, intérêt pour les panneaux ou une batterie, attentes personnelles et calendrier.','Cette communication directe contribue à fournir aux partenaires des demandes aussi complètes et pertinentes que possible. Mario gère aussi le contact téléphonique et le numéro WhatsApp public de PvPro.ch.','Ses responsabilités associent communication avec les clients, qualification attentive et soutien opérationnel au processus de mise en relation.']},
      {name:'Marcus Tezel',role:'Responsable de la publicité numérique',bio:['Marcus Tezel est responsable du marketing numérique et des campagnes publicitaires de PvPro.ch. Il planifie, gère et optimise continuellement les campagnes en ligne, notamment sur les plateformes Meta, dont Facebook et Instagram.','Il développe et met en œuvre les stratégies publicitaires, analyse les résultats et améliore les actions en continu. Son objectif est de toucher les propriétaires concrètement intéressés par le photovoltaïque et de leur présenter les possibilités de comparaison.','Le suivi des indicateurs de performance et l’optimisation ciblée contribuent à une acquisition de clients efficace et durable. Son travail fait partie du modèle commercial et du développement continu de la plateforme.']}
    ],responsibilitiesTitle:'Mise en relation et installation : des responsabilités distinctes.',responsibilities:'Notre équipe accompagne la mise en relation. Les conseils techniques, les offres fermes, la planification, l’installation et les services convenus relèvent de l’installateur. Le contrat d’installation est conclu directement entre vous et l’entreprise.'
  },
  contact:{general:'Questions générales & partenariats',requests:'Questions sur votre demande',phone:'Téléphone',address:'Adresse commerciale',country:'Suisse',canton:'Tessin',availability:'Nos disponibilités',daily:'Tous les jours, 08:00–20:00',timing:'Nous nous efforçons de répondre rapidement aux demandes et messages. Le délai de traitement varie selon le volume reçu. Nous ne garantissons volontairement aucun délai fixe de réponse.',mario:'Mario Kopar gère le numéro public de téléphone et de WhatsApp.',languagesTitle:'Quatre langues. Une équipe pour la Suisse.',languagesIntro:'Nous accompagnons propriétaires et partenaires dans toute la Suisse. Vous pouvez nous contacter dans l’une de ces quatre langues :',languages:['Allemand','Italien','Français','Anglais'],locationTitle:'Notre adresse et notre fonctionnement.',location:['PvPro.ch / NOBA Media Sagl est géré depuis Lugaggia, au Tessin. Notre activité est organisée en ligne et par téléphone. Les échanges ont principalement lieu via la plateforme, par téléphone, WhatsApp et e-mail.','Notre adresse commerciale n’est pas un magasin ouvert au public avec accueil habituel des clients. Aucun déplacement personnel n’est nécessaire pour utiliser nos services.'],partnerTitle:'Vous souhaitez devenir partenaire installateur ?',partnerText:'Nous souhaitons rencontrer des entreprises photovoltaïques professionnelles intéressées par des contacts clients qualifiés dans leurs zones d’intervention. Écrivez-nous pour connaître la collaboration et ses conditions.',existingTitle:'Vous avez déjà envoyé une demande ?',existingText:'Pour une question sur une demande existante ou pour la retirer, appelez-nous ou écrivez à anfrage@pvpro.ch. Précisez l’adresse e-mail utilisée pour la demande. Notre déclaration de protection des données explique leur traitement.'},
  faq:{groupTitles:['Service, coûts & décision','Demande, contact & données','Partenaires & disponibilité','Projet, offres & responsabilités'],helpTitle:'Votre question reste ouverte ?',helpText:'Notre équipe vous aide pour la plateforme ou votre demande. Les questions techniques et les détails d’une offre précise sont à discuter avec l’entreprise d’installation concernée.'}
};
