export type CompanyLocale = 'de' | 'fr' | 'en' | 'it';

export const companyRoutes = {
  de: { contact: '/kontakt', team: '/team', about: '/ueber-uns', quote: '/anfrage', service: '/wie-es-funktioniert', subsidy: '/foerderungen', faq: '/faq', legal: '/impressum' },
  fr: { contact: '/fr/contact', team: '/fr/equipe', about: '/fr/a-propos', quote: '/fr/demande', service: '/fr/comment-ca-marche', subsidy: '/fr/subventions-solaires', faq: '/fr/faq', legal: '/fr/mentions-legales' },
  en: { contact: '/en/contact', team: '/en/team', about: '/en/about-us', quote: '/en/request', service: '/en/how-it-works', subsidy: '/en/solar-subsidies', faq: '/en/faq', legal: '/en/imprint' },
  it: { contact: '/it/contatti', team: '/it/team', about: '/it/chi-siamo', quote: '/it/richiesta', service: '/it/come-funziona', subsidy: '/it/incentivi-solari', faq: '/it/faq', legal: '/it/note-legali' },
} as const;

export const companyContent = {
  de: {
    home: 'Startseite', contact: 'Kontakt', team: 'Team', about: 'Über das Unternehmen', faq: 'Häufige Fragen', legal: 'Impressum',
    contactTitle: 'Wie können wir Ihnen helfen?',
    contactIntro: 'Eine Frage zu PvPro.ch oder zu Ihrer bestehenden Anfrage? Schreiben Sie uns oder rufen Sie uns an. Für neue Solarofferten nutzen Sie bitte das separate Anfrageformular.',
    contactMeta: 'Kontaktieren Sie PvPro.ch per E-Mail oder Telefon. Finden Sie unsere Adresse in Lugano und den richtigen Weg für Solarofferten.',
    deskTitle: 'Direkt mit PvPro.ch sprechen',
    deskText: 'Für allgemeine Fragen zur Plattform, zu Ihrer Anfrage oder zur Zusammenarbeit.',
    email: 'E-Mail', phone: 'Telefon', address: 'Unternehmensadresse', country: 'Schweiz',
    quoteTitle: 'Sie suchen Solarofferten?',
    quoteText: 'Über das Anfrageformular erfassen wir die Angaben zu Ihrer Liegenschaft und vermitteln Ihre Anfrage an bis zu drei geprüfte Installateure. Der Vergleich ist für Hausbesitzer kostenlos und unverbindlich.',
    quoteAction: 'Solarofferten anfordern',
    prepareTitle: 'Bereits eine Anfrage gestellt?',
    prepareText: 'Nennen Sie in Ihrer E-Mail die Adresse der Liegenschaft und die bei Ihrer Anfrage verwendete E-Mail-Adresse. Senden Sie bitte keine sensiblen Dokumente, wenn diese für Ihre Frage nicht nötig sind.',
    teamTitle: 'Eine Plattform. Klare Zuständigkeiten.',
    teamIntro: 'Hinter einer Solarofferte stehen unterschiedliche Aufgaben. Hier erfahren Sie, welche Rolle PvPro.ch übernimmt, was die Installateure leisten und an wen Sie sich mit Ihren Fragen wenden können.',
    teamMeta: 'Lernen Sie die Aufgaben von PvPro.ch und den unabhängigen Installateuren kennen: Vermittlung, Unterstützung, Planung und Installation.',
    platformTitle: 'PvPro.ch: Vermittlung & Unterstützung',
    platformText: 'Wir verbinden Hausbesitzer mit geprüften Photovoltaik-Installateuren. PvPro.ch ist eine Vergleichsplattform, kein Installationsbetrieb.',
    platformTasks: ['Anfragen über das Formular entgegennehmen und an passende Partner weiterleiten.', 'Partner vor der Aufnahme ins Netzwerk prüfen: Zertifikate, Referenzen und Versicherungsnachweise.', 'Fragen zur Nutzung der Plattform und zu Ihrer Anfrage per E-Mail oder Telefon entgegennehmen.'],
    installerTitle: 'Installateure: Planung & Umsetzung',
    installerText: 'Die unabhängigen Fachbetriebe erstellen ihre eigenen Offerten. Technische Abklärungen und die Ausführung stimmen Sie direkt mit dem gewählten Installateur ab.',
    installerTasks: ['Dach, Stromverbrauch und technische Voraussetzungen für die Anlage abklären.', 'Komponenten, Leistungsumfang, Preis und Vertragsbedingungen in der Offerte festhalten.', 'Installation, Inbetriebnahme und vereinbarte Leistungen nach Auftragserteilung ausführen.'],
    supportTitle: 'Die richtige Anlaufstelle für Ihre Frage',
    supportIntro: 'Von der ersten Anfrage bis zur Entscheidung: Zuständigkeiten sollen verständlich bleiben.',
    supportRows: [
      { title: 'Fragen zur Anfrage oder Plattform', text: 'Für allgemeine Anliegen und Fragen zur Vermittlung erreichen Sie PvPro.ch über die Kontaktseite.', action: 'Kontakt aufnehmen', target: 'contact' },
      { title: 'Fragen zu einer konkreten Offerte', text: 'Leistung, Dachplanung, Termine und Garantien klären Sie mit dem Installateur, der die Offerte erstellt hat.', action: 'Ablauf des Vergleichs ansehen', target: 'service' },
      { title: 'Ein neues Solarprojekt starten', text: 'Nutzen Sie das Anfrageformular, damit Ihre Projektangaben für die Vermittlung vorliegen.', action: 'Anfrageformular öffnen', target: 'quote' },
    ],
    decision: 'Sie entscheiden selbst, ob Sie eine Offerte annehmen. Einen Auftrag für die Installation vereinbaren Sie direkt mit dem Fachbetrieb, nicht mit PvPro.ch.',
    companyNote: 'Die Mission, Arbeitsweise und Unternehmensangaben finden Sie auf unserer Unternehmensseite.',
  },
  fr: {
    home: 'Accueil', contact: 'Contact', team: 'Équipe', about: 'À propos de l’entreprise', faq: 'Questions fréquentes', legal: 'Mentions légales',
    contactTitle: 'Comment pouvons-nous vous aider ?',
    contactIntro: 'Une question sur PvPro.ch ou sur une demande déjà envoyée ? Écrivez-nous ou appelez-nous. Pour obtenir de nouvelles offres solaires, utilisez le formulaire de demande dédié.',
    contactMeta: 'Contactez PvPro.ch par e-mail ou téléphone. Retrouvez notre adresse à Lugano et le formulaire pour demander des offres solaires.',
    deskTitle: 'Contacter directement PvPro.ch',
    deskText: 'Pour vos questions sur la plateforme, votre demande ou une collaboration.',
    email: 'E-mail', phone: 'Téléphone', address: 'Adresse de l’entreprise', country: 'Suisse',
    quoteTitle: 'Vous cherchez des offres solaires ?',
    quoteText: 'Le formulaire nous permet de recueillir les informations sur votre bien et de transmettre votre demande à jusqu’à trois installateurs vérifiés. La comparaison est gratuite et sans engagement pour les propriétaires.',
    quoteAction: 'Demander des offres solaires',
    prepareTitle: 'Vous avez déjà envoyé une demande ?',
    prepareText: 'Indiquez dans votre e-mail l’adresse du bien et l’adresse e-mail utilisée lors de votre demande. Évitez de joindre des documents sensibles s’ils ne sont pas nécessaires à votre question.',
    teamTitle: 'Une plateforme. Des rôles bien définis.',
    teamIntro: 'Une offre solaire fait intervenir plusieurs compétences. Découvrez ce que prend en charge PvPro.ch, ce qui relève des installateurs et à qui adresser vos questions.',
    teamMeta: 'Découvrez les rôles de PvPro.ch et des installateurs indépendants : mise en relation, accompagnement, planification et installation.',
    platformTitle: 'PvPro.ch : mise en relation et assistance',
    platformText: 'Nous mettons les propriétaires en relation avec des installateurs photovoltaïques vérifiés. PvPro.ch est une plateforme de comparaison, pas une entreprise d’installation.',
    platformTasks: ['Recueillir les demandes via le formulaire et les transmettre aux partenaires adaptés.', 'Vérifier les partenaires avant leur entrée dans le réseau : certifications, références et attestations d’assurance.', 'Recevoir vos questions sur la plateforme et votre demande par e-mail ou téléphone.'],
    installerTitle: 'Installateurs : étude et réalisation',
    installerText: 'Les entreprises indépendantes établissent leurs propres offres. Vous convenez directement des aspects techniques et de la réalisation avec l’installateur choisi.',
    installerTasks: ['Examiner la toiture, la consommation électrique et les conditions techniques du projet.', 'Préciser les composants, les prestations, le prix et les conditions contractuelles dans l’offre.', 'Réaliser l’installation, la mise en service et les prestations convenues après acceptation du mandat.'],
    supportTitle: 'Le bon interlocuteur pour votre question',
    supportIntro: 'De la première demande à votre décision, chacun doit savoir qui fait quoi.',
    supportRows: [
      { title: 'Questions sur la demande ou la plateforme', text: 'Pour vos questions générales et celles concernant la mise en relation, contactez PvPro.ch depuis la page de contact.', action: 'Nous contacter', target: 'contact' },
      { title: 'Questions sur une offre précise', text: 'Les prestations, l’étude de toiture, les délais et les garanties sont à clarifier avec l’installateur qui a établi l’offre.', action: 'Comprendre la comparaison', target: 'service' },
      { title: 'Démarrer un projet solaire', text: 'Utilisez le formulaire de demande pour nous transmettre les informations nécessaires à la mise en relation.', action: 'Ouvrir le formulaire', target: 'quote' },
    ],
    decision: 'Vous restez libre d’accepter ou non une offre. Le contrat d’installation est conclu directement avec l’entreprise choisie, et non avec PvPro.ch.',
    companyNote: 'Notre mission, notre fonctionnement et les informations sur l’entreprise figurent sur la page À propos.',
  },
  en: {
    home: 'Home', contact: 'Contact', team: 'Team', about: 'About the company', faq: 'Frequently asked questions', legal: 'Legal notice',
    contactTitle: 'How can we help?',
    contactIntro: 'Have a question about PvPro.ch or a request you have already sent? Email or call us. For new solar quotes, please use the separate quote request form.',
    contactMeta: 'Contact PvPro.ch by email or phone. Find our address in Lugano and the dedicated form for requesting solar quotes.',
    deskTitle: 'Speak directly with PvPro.ch',
    deskText: 'For general questions about the platform, your request or working with us.',
    email: 'Email', phone: 'Phone', address: 'Company address', country: 'Switzerland',
    quoteTitle: 'Looking for solar quotes?',
    quoteText: 'The request form collects your property details so we can forward your enquiry to up to three vetted installers. The comparison service is free for homeowners, with no obligation.',
    quoteAction: 'Request solar quotes',
    prepareTitle: 'Already submitted a request?',
    prepareText: 'In your email, include the property address and the email address used for your request. Please do not attach sensitive documents unless they are needed to explain your question.',
    teamTitle: 'One platform. Clear responsibilities.',
    teamIntro: 'A solar quote involves different responsibilities. Find out what PvPro.ch handles, what installers do, and who to contact when you have a question.',
    teamMeta: 'Understand the roles of PvPro.ch and independent installers: introductions, support, system planning and installation.',
    platformTitle: 'PvPro.ch: introductions & support',
    platformText: 'We connect homeowners with vetted photovoltaic installers. PvPro.ch is a comparison platform, not an installation company.',
    platformTasks: ['Receive enquiries through the form and forward them to suitable partners.', 'Check partners before they join the network: certifications, references and proof of insurance.', 'Receive questions about using the platform and your request by email or phone.'],
    installerTitle: 'Installers: planning & delivery',
    installerText: 'Independent installation businesses prepare their own quotes. You discuss technical assessments and delivery directly with your chosen installer.',
    installerTasks: ['Assess the roof, electricity consumption and technical requirements for the system.', 'Specify components, scope of work, price and contractual terms in the quote.', 'Carry out installation, commissioning and agreed services once commissioned.'],
    supportTitle: 'The right contact for your question',
    supportIntro: 'From your first enquiry to your decision, it should be clear who handles each step.',
    supportRows: [
      { title: 'Questions about your request or the platform', text: 'For general enquiries and questions about the introduction process, reach PvPro.ch through the contact page.', action: 'Contact us', target: 'contact' },
      { title: 'Questions about a specific quote', text: 'Discuss scope, roof design, timing and warranties with the installer who prepared the quote.', action: 'See how comparison works', target: 'service' },
      { title: 'Starting a new solar project', text: 'Use the request form to provide the project details needed to connect you with installers.', action: 'Open the request form', target: 'quote' },
    ],
    decision: 'You decide whether to accept a quote. Any installation contract is agreed directly with the installer, not with PvPro.ch.',
    companyNote: 'Our mission, approach and company details are on the About page.',
  },
  it: {
    home: 'Home', contact: 'Contatti', team: 'Team', about: 'Informazioni sull’azienda', faq: 'Domande frequenti', legal: 'Note legali',
    contactTitle: 'Come possiamo aiutarti?',
    contactIntro: 'Hai una domanda su PvPro.ch o su una richiesta già inviata? Scrivici o chiamaci. Per nuovi preventivi solari, utilizza il modulo di richiesta dedicato.',
    contactMeta: 'Contatta PvPro.ch via e-mail o telefono. Trova il nostro indirizzo a Lugano e il modulo dedicato ai preventivi solari.',
    deskTitle: 'Parla direttamente con PvPro.ch',
    deskText: 'Per domande sulla piattaforma, sulla tua richiesta o su una collaborazione.',
    email: 'E-mail', phone: 'Telefono', address: 'Indirizzo dell’azienda', country: 'Svizzera',
    quoteTitle: 'Cerchi preventivi solari?',
    quoteText: 'Il modulo raccoglie le informazioni sul tuo immobile per inoltrare la richiesta a un massimo di tre installatori verificati. Il confronto è gratuito e senza impegno per i proprietari.',
    quoteAction: 'Richiedi preventivi solari',
    prepareTitle: 'Hai già inviato una richiesta?',
    prepareText: 'Nella tua e-mail indica l’indirizzo dell’immobile e l’indirizzo e-mail usato per la richiesta. Non allegare documenti sensibili se non sono necessari per spiegare la tua domanda.',
    teamTitle: 'Una piattaforma. Responsabilità chiare.',
    teamIntro: 'Un preventivo solare coinvolge competenze diverse. Scopri di cosa si occupa PvPro.ch, quali attività spettano agli installatori e a chi rivolgerti per le tue domande.',
    teamMeta: 'Scopri i ruoli di PvPro.ch e degli installatori indipendenti: contatto, assistenza, progettazione e installazione.',
    platformTitle: 'PvPro.ch: contatto e assistenza',
    platformText: 'Mettiamo i proprietari in contatto con installatori fotovoltaici verificati. PvPro.ch è una piattaforma di confronto, non un’impresa di installazione.',
    platformTasks: ['Ricevere le richieste tramite il modulo e inoltrarle ai partner adatti.', 'Verificare i partner prima dell’ingresso nella rete: certificazioni, referenze e attestazioni assicurative.', 'Ricevere domande sull’utilizzo della piattaforma e sulla tua richiesta via e-mail o telefono.'],
    installerTitle: 'Installatori: progetto e realizzazione',
    installerText: 'Le imprese indipendenti preparano i propri preventivi. Concordi gli approfondimenti tecnici e la realizzazione direttamente con l’installatore scelto.',
    installerTasks: ['Valutare il tetto, i consumi elettrici e i requisiti tecnici dell’impianto.', 'Specificare componenti, prestazioni, prezzo e condizioni contrattuali nel preventivo.', 'Eseguire l’installazione, la messa in servizio e le prestazioni concordate dopo il conferimento dell’incarico.'],
    supportTitle: 'Il contatto giusto per la tua domanda',
    supportIntro: 'Dalla prima richiesta alla decisione, le responsabilità devono essere comprensibili.',
    supportRows: [
      { title: 'Domande sulla richiesta o sulla piattaforma', text: 'Per domande generali e sul contatto con gli installatori, raggiungi PvPro.ch dalla pagina Contatti.', action: 'Contattaci', target: 'contact' },
      { title: 'Domande su un preventivo specifico', text: 'Chiarisci prestazioni, progetto del tetto, tempi e garanzie con l’installatore che ha preparato il preventivo.', action: 'Scopri come funziona il confronto', target: 'service' },
      { title: 'Avviare un nuovo progetto solare', text: 'Usa il modulo di richiesta per fornire i dati necessari a metterti in contatto con gli installatori.', action: 'Apri il modulo di richiesta', target: 'quote' },
    ],
    decision: 'Decidi tu se accettare un preventivo. Il contratto di installazione viene stipulato direttamente con l’impresa scelta, non con PvPro.ch.',
    companyNote: 'La nostra missione, il nostro approccio e i dati aziendali si trovano nella pagina Chi siamo.',
  },
} as const;
