import type { CompanyCopy } from './types';

export const de: CompanyCopy = {
  home:'Startseite', breadcrumb:'Brotkrumennavigation', contents:'Auf dieser Seite', privacy:'Datenschutzerklärung', portrait:'Porträt', groupPhoto:'Teamfoto', photoPending:'Das echte, freigegebene Foto folgt.',
  labels:{about:'Unser Ansatz',team:'Team',contact:'Kontakt',faq:'Häufige Fragen'},
  pages:{
    about:{title:'Unser Ansatz: persönlich prüfen, passend vermitteln.',intro:'PvPro.ch ist eine unabhängige Schweizer Vergleichs- und Vermittlungsplattform. Wir verbinden Hauseigentümer mit passenden Photovoltaik-Fachbetrieben – kostenlos und unverbindlich.',description:'Unser Ansatz bei PvPro.ch: persönliche Prüfung, maximal drei Installationspartner, transparente Finanzierung und unsere Geschichte seit Oktober 2025.'},
    team:{title:'Die Menschen hinter PvPro.ch.',intro:'Drei Menschen, klar definierte Aufgaben: Wir begleiten den Weg von der Kundengewinnung über die telefonische Qualifizierung bis zur Vermittlung persönlich.',description:'Elia Alacam, Mario Kopar und Marcus Tezel: Lernen Sie das dreiköpfige Team von PvPro.ch und seine tatsächlichen Aufgaben kennen.'},
    contact:{title:'Haben Sie Fragen? Sprechen Sie mit uns.',intro:'Sie planen eine Photovoltaikanlage, haben eine Frage zu Ihrer Anfrage oder möchten als Installationsunternehmen mit uns zusammenarbeiten? Unser Team ist telefonisch, per WhatsApp und per E-Mail erreichbar.',description:'Kontakt zu PvPro.ch: info@pvpro.ch, anfrage@pvpro.ch, +41 76 270 38 87. Täglich 08–20 Uhr, vier Sprachen, Geschäftsadresse in Lugaggia.'},
    faq:{title:'Klare Antworten auf Ihre Fragen.',intro:'Was ist kostenlos? Wer erhält Ihre Anfrage? Wer ist für die Installation verantwortlich? Hier beantworten wir 20 Fragen zu unserem Service, zum Vergleich und zu Ihren Möglichkeiten.',description:'20 Antworten zum Vermittlungsservice von PvPro.ch: Kosten, Ablauf, Partnerauswahl, Daten, Rückzug der Anfrage, Angebote und Verantwortung für Garantien.'}
  },
  quote:'Solarofferten anfordern',quoteTitle:'Eine Anfrage für Ihr Solarprojekt.',quoteText:'Nutzen Sie unser bestehendes Anfrageformular. Wir prüfen Ihre Angaben und vermitteln geeignete Anfragen an maximal drei passende Partnerunternehmen. Kostenlos und ohne Verpflichtung zur Angebotsannahme; die tatsächliche Anzahl hängt von Standort, Projekt und Verfügbarkeit ab.',
  facts:[{value:'Oktober 2025',label:'Gründung von PvPro.ch'},{value:'30+',label:'Partnerunternehmen im Schweizer Photovoltaikmarkt'},{value:'3',label:'Menschen im Team von PvPro.ch'},{value:'20+ Jahre',label:'Branchenerfahrung im Netzwerk der Installationspartner – nicht das Alter von PvPro.ch'}],
  about:{
    title:'Eine passende Solaranlage beginnt mit verständlichen Möglichkeiten.',
    paragraphs:['Welche Anlage eignet sich für mein Haus? Wie unterscheiden sich Preise und Leistungen? Welchem Installateur kann ich vertrauen und wie erkenne ich ein faires Angebot? Diese Fragen machen die Suche nach einer Photovoltaikanlage häufig schwierig.','PvPro.ch möchte diese Suche einfacher, transparenter und unkomplizierter gestalten. Statt selbst mehrere Installateure zu suchen und zu kontaktieren, stellen Sie eine einzige Anfrage. Sie können kostenlos und unverbindlich bis zu drei Angebote anfordern.','Wir prüfen Ihre Anfrage und leiten sie an geeignete Partnerunternehmen weiter, die am Standort Ihres Projekts tätig sind. Transparenz, persönliche Kommunikation und die Qualität der vermittelten Kontakte stehen dabei im Mittelpunkt.'],
    storyTitle:'Unsere Geschichte: von der Beobachtung zur Plattform.',
    story:['Seit 2023 ist Elia Alacam beruflich in der Schweizer Photovoltaikbranche tätig. Unter anderem arbeitete er mit Green Solar Energy zusammen und sammelte praktische Erfahrungen mit Solarunternehmen, der Kundengewinnung und den Herausforderungen des Schweizer Marktes.','Dabei begegnete er zwei Seiten desselben Problems: Hauseigentümer suchten passende Betriebe und verständliche Vergleiche. Gute Installationsbetriebe suchten neue Kunden und konkrete Projekte in ihren Einsatzgebieten.','Die Idee, beide Seiten über eine zentrale Plattform zusammenzubringen, entstand während eines Aufenthalts auf Bali. Im Oktober 2025 gründete Elia Alacam, Gründer und CEO von NOBA Media Sagl, PvPro.ch.','Aus dem unternehmerischen Projekt ist eine schweizweit tätige Vermittlungsplattform mit über 30 Partnerunternehmen und einem dreiköpfigen Team geworden. Unsere Vision bleibt: Hauseigentümern den Zugang zu passenden Photovoltaik-Angeboten erleichtern und Installationsbetrieben neue Geschäftsmöglichkeiten eröffnen.'],
    principlesTitle:'So arbeiten wir.',
    principles:[
      {title:'Persönliche Prüfung statt automatischer Weiterleitung',text:'Wir leiten nicht jeden ausgefüllten Fragebogen ungeprüft weiter. Unser Team kontaktiert Interessenten telefonisch, bestätigt ihr Interesse und prüft Angaben zur Immobilie, zu den Vorstellungen des Eigentümers und zum Umsetzungszeitraum. So sollen Partner möglichst relevante Anfragen erhalten und Eigentümer mit Betrieben in Kontakt kommen, die für ihr Vorhaben infrage kommen.'},
      {title:'Maximal drei Fachbetriebe pro Anfrage',text:'Ein Vergleich braucht unterschiedliche Möglichkeiten, nicht unzählige Anrufe. Wir leiten eine Anfrage an höchstens drei passende Partner weiter. Damit können Sie Preise, Leistungen, Komponenten und Garantien übersichtlich vergleichen. Bis zu drei Angebote sind möglich, aber nicht garantiert.'},
      {title:'Kostenlos und unverbindlich',text:'Für Hauseigentümer entstehen weder Kosten für die Anfrage noch für die Vermittlung oder den Vergleich. Sie müssen kein Angebot annehmen und keine Solaranlage installieren lassen. Die Entscheidung liegt immer bei Ihnen.'},
      {title:'Ein Netzwerk von über 30 Partnerunternehmen',text:'Unsere Partner übernehmen Projekte in verschiedenen Kantonen. So bearbeiten wir Anfragen aus der Deutschschweiz, der Romandie und dem Tessin. Im Netzwerk der Installationspartner ist Erfahrung aus über 20 Jahren Branchentätigkeit vertreten. Diese Angabe bezieht sich nicht auf das Alter oder die eigene Erfahrung von PvPro.ch.'},
      {title:'Direkter Kontakt mit echten Ansprechpartnern',text:'Unser kleines Team übernimmt die erste Anfrage, die telefonische Qualifizierung und die Zusammenarbeit mit den Installateuren selbst. Wir wollen für Hauseigentümer und Partner persönlich erreichbar sein und langfristige, vertrauensvolle Beziehungen aufbauen.'}
    ],
    selectionTitle:'Wie wir Installationspartner auswählen.',selectionIntro:'Nicht jedes Unternehmen wird automatisch Partner. Vor einer Zusammenarbeit versuchen wir, uns ein möglichst umfassendes Bild des Photovoltaikunternehmens zu machen. Dabei berücksichtigen wir:',
    criteria:[{title:'Unternehmenshintergrund',text:'Ist der Betrieb tatsächlich im Photovoltaikbereich tätig? Wir informieren uns über seinen geschäftlichen Hintergrund.'},{title:'Kundenbewertungen',text:'Wir sehen uns öffentlich verfügbare Bewertungen und Erfahrungen bisheriger Kunden an.'},{title:'Referenzen und Projekte',text:'Soweit verfügbar berücksichtigen wir abgeschlossene Arbeiten und Referenzprojekte.'},{title:'Tätigkeit am Projektstandort',text:'Wir prüfen, in welchen Kantonen und Orten der Installateur tatsächlich Projekte übernimmt.'},{title:'Professionalität',text:'Wir achten auf Kommunikation, Zuverlässigkeit und den allgemeinen geschäftlichen Eindruck.'},{title:'Erreichbarkeit und Zusammenarbeit',text:'Wir erwarten professionelle Kommunikation und einen respektvollen Umgang mit Interessenten.'}],
    feedback:'Auch nach Beginn der Zusammenarbeit beachten wir eingehende Erfahrungen und Rückmeldungen. Bei wiederholten Problemen oder Beschwerden können wir die Zusammenarbeit überprüfen. Unser Ziel ist ein verlässliches Netzwerk, nicht die grösstmögliche Zahl an Partnern.',
    disclaimer:'Die Auswahl ersetzt keine unabhängige technische Zertifizierung und ist keine Garantie für die spätere Ausführung. Beratung, Angebote und Installationsarbeiten liegen in der Verantwortung der jeweiligen Fachbetriebe.',
    modelTitle:'Wie sich der kostenlose Service finanziert.',
    model:['Hauseigentümer nutzen PvPro.ch vollständig kostenlos. Unsere Einnahmen stammen von den Photovoltaikunternehmen, die für qualifizierte Kundenkontakte bezahlen.','Unser Team prüft die Anfrage und leitet sie bei entsprechender Eignung an maximal drei passende Partner weiter. Diese bezahlen für die erhaltenen qualifizierten Kontakte. So finanzieren wir den kostenlosen Vermittlungsservice.','PvPro.ch verkauft und installiert selbst keine Solaranlagen. Angebote und allfällige Verträge vereinbaren Sie direkt mit dem jeweiligen Installationsbetrieb. Die Zahlung durch unsere Partner verpflichtet Sie nicht, ein Angebot anzunehmen. Unser Ziel ist ein transparenter, unkomplizierter Vergleich.']
  },
  team:{
    title:'Persönlich, engagiert und nah am Kunden.',intro:'Die Geschäftsführung entwickelt die Plattform und die Zusammenarbeit mit Partnern. Die weiteren Teammitglieder qualifizieren eingehende Anfragen und planen und optimieren digitale Werbekampagnen. So begleiten wir den gesamten Vermittlungsprozess selbst.',
    people:[
      {name:'Elia Alacam',role:'Gründer & CEO',bio:['Elia Alacam ist der Gründer von PvPro.ch und Geschäftsführer von NOBA Media Sagl. Seit 2023 beschäftigt er sich beruflich mit dem Schweizer Photovoltaikmarkt und sammelte durch die Zusammenarbeit mit Green Solar Energy praktische Branchenerfahrung.','Dabei entwickelte er ein Verständnis für die Bedürfnisse von Hauseigentümern und Installationsbetrieben sowie die Herausforderungen der Kundengewinnung im Solarsektor. Im Oktober 2025 gründete er PvPro.ch, um diese Erfahrungen in eine eigene Vermittlungsplattform einzubringen.','Heute verantwortet Elia die strategische und operative Entwicklung, die Akquisition neuer Geschäftspartner, die Betreuung bestehender Kooperationen und den Ausbau der Plattform.','Sein Schwerpunkt ist der direkte Austausch mit Installationsunternehmen und der Aufbau langfristiger Geschäftsbeziehungen. Er möchte PvPro.ch als zuverlässige und etablierte Anlaufstelle für Photovoltaikvergleiche in der Schweiz weiterentwickeln.']},
      {name:'Mario Kopar',role:'Customer Qualification Specialist',bio:['Mario Kopar ist für die telefonische Qualifizierung und Betreuung eingehender Kundenanfragen zuständig. Er gehört zu den ersten direkten Ansprechpartnern für Hauseigentümer, die Interesse an einer Photovoltaikanlage anmelden.','Er kontaktiert Interessenten persönlich, prüft ihre Angaben und trägt die wichtigsten Projektinformationen zusammen: Immobilienart, Interesse an Solaranlage oder Batteriespeicher, persönliche Vorstellungen und zeitliche Rahmenbedingungen.','Die direkte Kommunikation hilft unseren Partnern, möglichst vollständige und relevante Anfragen zu erhalten. Mario betreut ausserdem den telefonischen Kontakt und die öffentliche WhatsApp-Nummer von PvPro.ch.','Sein Aufgabenbereich verbindet Kundenkommunikation, sorgfältige Qualifizierung und operative Unterstützung des Vermittlungsprozesses.']},
      {name:'Marcus Tezel',role:'Digital Advertising Manager',bio:['Marcus Tezel ist für digitales Marketing und die Werbekampagnen von PvPro.ch verantwortlich. Er plant, verwaltet und optimiert Online-Kampagnen, insbesondere auf Meta-Plattformen wie Facebook und Instagram.','Er entwickelt und setzt Werbestrategien um, analysiert Kampagnenergebnisse und verbessert die Werbemassnahmen laufend. Ziel ist, Hauseigentümer mit konkretem Photovoltaikinteresse zu erreichen und auf die Vergleichsmöglichkeiten aufmerksam zu machen.','Durch die Überwachung wichtiger Leistungskennzahlen und gezielte Optimierung unterstützt er eine möglichst effiziente und nachhaltige Kundengewinnung. Seine Arbeit ist ein Bestandteil des Geschäftsmodells und der kontinuierlichen Entwicklung der Plattform.']}
    ],responsibilitiesTitle:'Vermittlung und Installation sind unterschiedliche Aufgaben.',responsibilities:'Unser Team begleitet die Vermittlung. Die technische Beratung, verbindliche Angebote, Planung, Installation und vereinbarte Serviceleistungen übernimmt der jeweilige Installationsbetrieb. Ein Installationsvertrag entsteht direkt zwischen Ihnen und dem Betrieb.'
  },
  contact:{general:'Allgemeine Fragen & Zusammenarbeit',requests:'Fragen zu Ihrer Anfrage',phone:'Telefon',address:'Geschäftsadresse',country:'Schweiz',canton:'Tessin',availability:'Unsere Erreichbarkeit',daily:'Täglich 08:00–20:00 Uhr',timing:'Wir bemühen uns, Anfragen und Nachrichten möglichst zeitnah zu beantworten. Die Bearbeitungszeit kann je nach Anzahl eingehender Anfragen variieren. Wir garantieren bewusst keine feste Antwortzeit.',mario:'Die öffentliche Telefon- und WhatsApp-Nummer wird von Mario Kopar betreut.',languagesTitle:'Vier Sprachen. Ein Team für die Schweiz.',languagesIntro:'Wir betreuen Hauseigentümer und Partner in der ganzen Schweiz. Sie können sich in einer dieser vier Sprachen an uns wenden:',languages:['Deutsch','Italienisch','Französisch','Englisch'],locationTitle:'Unser Standort und unsere Arbeitsweise.',location:['PvPro.ch / NOBA Media Sagl wird von Lugaggia im Tessin aus geführt. Unser Geschäftsmodell ist digital und telefonisch organisiert. Wir kommunizieren hauptsächlich über die Plattform, telefonisch, per WhatsApp und per E-Mail.','Unsere Geschäftsadresse ist kein öffentliches Kundengeschäft mit regulärem Besucherverkehr. Für die Nutzung unserer Dienstleistungen ist kein persönlicher Besuch nötig.'],partnerTitle:'Sie möchten Installationspartner werden?',partnerText:'Wir möchten professionelle Photovoltaikunternehmen kennenlernen, die qualifizierte Kundenkontakte aus ihren Einsatzgebieten erhalten möchten. Schreiben Sie uns für Informationen zur Zusammenarbeit und zu den Konditionen.',existingTitle:'Bereits eine Anfrage gestellt?',existingText:'Für Fragen zu einer bestehenden Anfrage oder für einen Rückzug erreichen Sie uns telefonisch oder unter anfrage@pvpro.ch. Bitte nennen Sie die bei der Anfrage verwendete E-Mail-Adresse. Informationen zur Bearbeitung Ihrer Daten finden Sie in unserer Datenschutzerklärung.'},
  faq:{groupTitles:['Service, Kosten & Entscheidung','Anfrage, Kontakt & Datenschutz','Partner & Verfügbarkeit','Ihr Projekt, Angebote & Verantwortung'],helpTitle:'Ihre Frage ist noch offen?',helpText:'Unser Team hilft bei Fragen zur Plattform oder zu Ihrer Anfrage. Technische Fragen und Details einer konkreten Offerte besprechen Sie bitte mit dem jeweiligen Installationsbetrieb.'}
};
