import type { CompanyCopy } from './types';

export const en: CompanyCopy = {
  home:'Home',breadcrumb:'Breadcrumb',contents:'On this page',privacy:'Privacy policy',portrait:'Portrait',groupPhoto:'Team photograph',photoPending:'The approved real photograph will follow.',
  labels:{about:'Our approach',team:'Team',contact:'Contact',faq:'Frequently asked questions'},
  pages:{
    about:{title:'Our approach: personal checks, suitable introductions.',intro:'PvPro.ch is an independent Swiss comparison and referral platform. We connect homeowners with suitable photovoltaic installation businesses, free of charge and without obligation.',description:'The PvPro.ch approach: personal checks, up to three installation partners, transparent funding and our story since October 2025.'},
    team:{title:'The people behind PvPro.ch.',intro:'Three people with clearly defined responsibilities. We personally support the journey from customer acquisition through telephone qualification to introductions to installers.',description:'Meet Elia Alacam, Mario Kopar and Marcus Tezel, the three-person PvPro.ch team, and learn about their actual responsibilities.'},
    contact:{title:'Have a question? Talk to us.',intro:'Planning a photovoltaic installation, following up on a request, or interested in becoming an installation partner? Our team is available by phone, WhatsApp and email.',description:'Contact PvPro.ch: info@pvpro.ch, anfrage@pvpro.ch and +41 76 270 38 87. Available daily 08:00–20:00 in four languages, based in Lugaggia.'},
    faq:{title:'Straight answers to your questions.',intro:'What is free? Who receives your request? Who is responsible for installation? These 20 answers explain our service, comparing quotes and your options.',description:'20 answers about PvPro.ch: costs, process, partner selection, data sharing, withdrawing a request, comparing quotes and warranty responsibilities.'}
  },
  quote:'Request solar quotes',quoteTitle:'One request for your solar project.',quoteText:'Use our existing request form. We check your details and refer suitable requests to no more than three appropriate partners. Free and without any obligation to accept a quote; the actual number depends on location, project and partner availability.',
  facts:[{value:'October 2025',label:'PvPro.ch founded'},{value:'30+',label:'Partner companies in the Swiss photovoltaic market'},{value:'3',label:'People on the PvPro.ch team'},{value:'20+ years',label:'Industry experience within the installation partner network — not the age of PvPro.ch'}],
  about:{
    title:'Finding a suitable solar installation starts with understanding your options.',
    paragraphs:['Which system suits my home? How do prices and services differ? Which installer can I trust, and how do I recognise a fair quote? These questions can make finding a photovoltaic installation difficult.','PvPro.ch aims to make the search simpler, more transparent and straightforward. Rather than finding and contacting several installers yourself, you submit one request. You can request up to three quotes free of charge, with no obligation.','We check your request and forward it to suitable partners working at your project location. Transparency, personal communication and the quality of the introductions matter to us.'],
    storyTitle:'Our story: from an observation to a platform.',
    story:['Elia Alacam has worked in the Swiss photovoltaic industry since 2023. His work included collaborating with Green Solar Energy, gaining practical experience with solar companies, customer acquisition and the challenges of the Swiss market.','He saw two sides of the same problem: homeowners struggled to find suitable businesses and compare their quotes. Good installation companies were looking for new customers and concrete projects in the places they served.','The idea of bringing both sides together on a central platform arose during a stay in Bali. In October 2025, Elia Alacam, founder and CEO of NOBA Media Sagl, launched PvPro.ch.','The entrepreneurial project has developed into a referral platform operating across Switzerland, with over 30 partner companies and a three-person team. Our vision remains to help homeowners access suitable photovoltaic quotes while opening up business opportunities for installers.'],
    principlesTitle:'How we work.',
    principles:[
      {title:'Personal checks, not automatic forwarding',text:'We do not pass on every completed questionnaire unchecked. Our team calls interested homeowners, confirms their interest and checks details about the property, their expectations and intended timescale. This helps partners receive relevant requests and homeowners meet businesses that may suit their project.'},
      {title:'No more than three companies per request',text:'Comparison needs different options, not countless calls. We forward each request to at most three suitable partners, keeping prices, services, components and warranties manageable to compare. Up to three quotes are possible, not guaranteed.'},
      {title:'Free and without obligation',text:'Homeowners pay nothing for requesting, receiving introductions or comparing quotes. There is no obligation to accept a quote or install a solar system. The decision always remains yours.'},
      {title:'A network of over 30 partners',text:'Our partners work in different cantons, allowing us to handle requests from German-speaking Switzerland, French-speaking Switzerland and Ticino. The installation partner network includes over 20 years of industry experience. This is not a claim about the age or own experience of PvPro.ch.'},
      {title:'Direct contact with real people',text:'Our small team handles initial requests, telephone qualification and working with installers ourselves. We want to be personally accessible to homeowners and partners and build lasting relationships based on trust.'}
    ],
    selectionTitle:'How we select installation partners.',selectionIntro:'Not every company automatically becomes a partner. Before working together, we try to build a comprehensive picture of the photovoltaic business, considering:',
    criteria:[{title:'Business background',text:'We check whether the company actually operates in photovoltaics and learn about its business background.'},{title:'Customer reviews',text:'We review publicly available ratings and previous customers’ experiences.'},{title:'References and projects',text:'Where available, we consider completed work and reference projects.'},{title:'Activity at the project location',text:'We check the cantons and locations where the installer actually takes on projects.'},{title:'Professionalism',text:'We consider communication, reliability and the overall business impression.'},{title:'Availability and cooperation',text:'We expect professional communication and respectful treatment of prospective customers.'}],
    feedback:'We continue to consider experiences and feedback after cooperation begins. Repeated problems or complaints may lead us to review the relationship. Our goal is a dependable network, not the largest possible number of partners.',
    disclaimer:'Partner selection is not an independent technical certification or a guarantee of project delivery. Each installation business is responsible for its advice, quotes and installation work.',
    modelTitle:'How the free service is funded.',
    model:['PvPro.ch is completely free for homeowners. Our income comes from photovoltaic companies that pay for qualified customer contacts.','Our team checks a request and, where suitable, refers it to at most three appropriate partners. These companies pay for the qualified contacts they receive. This funds our free referral service.','PvPro.ch does not sell or install solar systems. Quotes and any contracts are agreed directly between you and the installer. Payments by partners do not oblige you to accept a quote. We aim to make comparing different options transparent and straightforward.']
  },
  team:{
    title:'Personal, committed and close to our customers.',intro:'Management develops the platform and its partner relationships. The other team members qualify incoming requests and plan and optimise digital advertising campaigns. Together, we personally support the whole referral process.',
    people:[
      {name:'Elia Alacam',role:'Founder & CEO',bio:['Elia Alacam is the founder of PvPro.ch and managing director of NOBA Media Sagl. He has worked professionally in the Swiss photovoltaic market since 2023, gaining practical experience through collaboration with Green Solar Energy.','He developed an understanding of the needs of homeowners and installation businesses and the challenges of customer acquisition in the solar sector. In October 2025 he founded PvPro.ch to bring that experience into his own referral platform.','Today Elia is responsible for strategic and operational development, acquiring new business partners, supporting existing collaborations and expanding the platform.','His focus is direct dialogue with installers and building long-term business relationships. He aims to develop PvPro.ch into a dependable, established contact point for photovoltaic comparisons in Switzerland.']},
      {name:'Mario Kopar',role:'Customer Qualification Specialist',bio:['Mario Kopar handles telephone qualification and support for incoming customer requests. He is one of the first people homeowners speak to when they express an interest in photovoltaics through the platform.','He contacts prospective customers personally, checks their details and gathers essential project information: property type, interest in solar panels or battery storage, personal expectations and intended timescale.','This direct communication helps partners receive requests that are as complete and relevant as possible. Mario also handles the public PvPro.ch phone number and WhatsApp communication.','His responsibilities combine customer communication, careful qualification and operational support for the referral process.']},
      {name:'Marcus Tezel',role:'Digital Advertising Manager',bio:['Marcus Tezel is responsible for digital marketing and PvPro.ch advertising campaigns. He plans, manages and continuously optimises online campaigns, particularly on Meta platforms including Facebook and Instagram.','He develops and implements advertising strategies, analyses campaign results and keeps improving advertising activity. His aim is to reach homeowners with a concrete interest in photovoltaics and introduce them to the comparison options.','By monitoring key performance indicators and targeting campaign improvements, he supports efficient and sustainable customer acquisition. His work is part of the business model and the platform’s continuing development.']}
    ],responsibilitiesTitle:'Introductions and installation are different responsibilities.',responsibilities:'Our team supports the referral process. The installer handles technical advice, binding quotes, planning, installation and agreed after-sales services. Any installation contract is between you and the installation business.'
  },
  contact:{general:'General questions & partnerships',requests:'Questions about your request',phone:'Phone',address:'Business address',country:'Switzerland',canton:'Ticino',availability:'When you can reach us',daily:'Daily 08:00–20:00',timing:'We aim to respond to requests and messages promptly. Processing time can vary with the number of incoming enquiries. We deliberately do not guarantee a fixed response time.',mario:'Mario Kopar handles the public phone and WhatsApp number.',languagesTitle:'Four languages. One team for Switzerland.',languagesIntro:'We support homeowners and partners throughout Switzerland. You can contact us in any of these four languages:',languages:['German','Italian','French','English'],locationTitle:'Our location and how we work.',location:['PvPro.ch / NOBA Media Sagl is run from Lugaggia in Ticino. Our business operates digitally and by phone. Communication mainly takes place through the platform, telephone, WhatsApp and email.','Our business address is not a public walk-in customer store. You do not need to visit in person to use our services.'],partnerTitle:'Interested in becoming an installation partner?',partnerText:'We welcome professional photovoltaic businesses interested in qualified customer contacts from the places they serve. Email us to learn about cooperation and its terms.',existingTitle:'Already submitted a request?',existingText:'For questions about an existing request or to withdraw it, call us or email anfrage@pvpro.ch. Please mention the email address used for your request. Our privacy policy explains how your data is processed.'},
  faq:{groupTitles:['Service, costs & your decision','Requests, contact & privacy','Partners & availability','Your project, quotes & responsibilities'],helpTitle:'Still have a question?',helpText:'Our team can help with the platform and your request. Please discuss technical questions and the details of a specific quote with the installation business concerned.'}
};
