import type { CompanyQuestion } from './types';

export const frQuestions: CompanyQuestion[] = [
  {id:1,question:'PvPro.ch est-il vraiment gratuit ?',answer:['Oui. PvPro.ch est entièrement gratuit et sans engagement pour les propriétaires. Vous ne payez ni la demande, ni la mise en relation, ni la comparaison des offres.','La plateforme est financée par les entreprises photovoltaïques qui paient pour des contacts clients qualifiés. Aucun frais de mise en relation ne vous est facturé.']},
  {id:2,question:'Comment fonctionne la comparaison sur PvPro.ch ?',answer:['Vous remplissez d’abord notre formulaire en ligne avec des informations sur votre bien et votre projet photovoltaïque. Notre équipe peut ensuite vous appeler pour confirmer vos données et clarifier les questions ouvertes.','Après vérification, nous transmettons la demande à trois entreprises photovoltaïques adaptées au maximum, actives au lieu du projet. Elles peuvent vous contacter directement, discuter de votre projet et préparer une offre individuelle. Vous décidez ensuite si vous souhaitez travailler avec une entreprise et laquelle.']},
  {id:3,question:'Pourquoi suis-je appelé après ma demande ?',answer:['Nous souhaitons vérifier que votre demande est correcte et complète. Notre équipe appelle les personnes intéressées pour confirmer les informations importantes et mieux comprendre le projet.','Cela nous permet de transmettre la demande aux partenaires les plus adaptés. Cet appel sert à la qualification et ne vous engage à rien.']},
  {id:4,question:'Combien d’offres vais-je recevoir ?',answer:['Vous pouvez recevoir jusqu’à trois offres d’entreprises photovoltaïques via PvPro.ch. Nous limitons volontairement la transmission à trois entreprises au maximum pour permettre la comparaison sans multiplier les appels d’installateurs.','Le nombre effectif dépend du lieu, du projet et des disponibilités des partenaires adaptés. Trois offres ne sont pas garanties.']},
  {id:5,question:'Dois-je accepter une des offres ?',answer:['Non. La demande et la comparaison sont entièrement sans engagement. Vous pouvez examiner les offres tranquillement et décider vous-même si vous souhaitez installer un système photovoltaïque. Si aucune offre ne vous convainc, vous n’avez pas à en accepter une.']},
  {id:6,question:'Combien de temps faut-il pour être contacté ?',answer:['Nous essayons de traiter les demandes rapidement. Après vérification et transmission aux partenaires adaptés, les entreprises peuvent vous contacter directement.','Le délai pour obtenir une offre précise dépend notamment de la disponibilité des installateurs et de la complexité du projet. Certains projets nécessitent d’abord une consultation supplémentaire ou une visite sur place. Nous ne pouvons garantir aucun délai fixe de contact ou d’offre.']},
  {id:7,question:'Comment PvPro.ch choisit-il ses partenaires installateurs ?',answer:['Nous accordons de l’importance à la collaboration avec des entreprises photovoltaïques sérieuses et professionnelles. Avant de collaborer, nous nous renseignons sur l’entreprise, son activité passée, les avis disponibles, les références et les cantons et localités où elle installe des systèmes. Le professionnalisme de la communication compte également.','Notre objectif est de faciliter le contact avec des entreprises adaptées. La sélection ne remplace pas une certification technique indépendante et ne garantit pas la réalisation. Les conseils, offres et installations relèvent de l’entreprise concernée.']},
  {id:8,question:'PvPro.ch installe-t-il lui-même des panneaux solaires ?',answer:['Non. PvPro.ch est une plateforme indépendante de comparaison et de mise en relation. Nous ne réalisons pas nous-mêmes d’installations photovoltaïques.','Les conseils techniques, les offres fermes et l’installation sont assurés par les entreprises photovoltaïques concernées.']},
  {id:9,question:'Mes données personnelles sont-elles transmises à d’autres entreprises ?',answer:['Pour obtenir des offres, certaines informations de votre demande doivent être transmises aux partenaires installateurs adaptés. La transmission repose sur votre demande et se limite à trois entreprises au maximum.','Ces informations servent à comprendre votre projet, vous contacter et préparer une offre appropriée. Vous trouverez davantage d’informations sur le traitement des données dans notre déclaration de protection des données.']},
  {id:10,question:'Puis-je retirer ma demande ?',answer:['Oui. Si vous ne souhaitez plus poursuivre votre demande, contactez-nous à tout moment par téléphone ou e-mail. Nous traiterons votre message et arrêterons les nouvelles transmissions dans la mesure du possible.','Si vos informations ont déjà été transmises à des partenaires, ceux-ci peuvent vous avoir déjà contacté. Vous pouvez aussi nous contacter pour toute question sur le traitement ou la suppression de vos données, notamment à anfrage@pvpro.ch.']},
  {id:11,question:'Que se passe-t-il si aucune offre ne me convient ?',answer:['Vous n’êtes évidemment pas obligé d’en accepter une. PvPro.ch vise à vous aider à découvrir différentes possibilités et à prendre une décision éclairée.','Si les offres ne correspondent pas à vos attentes, vous pouvez renoncer à l’installation. Cela n’entraîne aucun frais envers PvPro.ch.']},
  {id:12,question:'Puis-je aussi demander une batterie de stockage ?',answer:['Oui. Si une batterie vous intéresse en complément de l’installation photovoltaïque, indiquez-le dans la demande.','Les installateurs peuvent examiner les possibilités adaptées à votre bien et à votre consommation. La taille de l’installation, la consommation électrique et vos besoins individuels sont notamment pris en compte.']},
  {id:13,question:'PvPro.ch est-il disponible dans toute la Suisse ?',answer:['Oui. PvPro.ch est actif dans toute la Suisse. Nous traitons les demandes de Suisse alémanique, de Suisse romande et du Tessin et collaborons avec des entreprises de différents cantons.','Les installateurs disponibles pour un projet donné dépendent du lieu et des exigences du projet.']},
  {id:14,question:'Puis-je faire une demande sans rien connaître au photovoltaïque ?',answer:['Bien sûr. Vous n’avez besoin ni de connaissances techniques ni de savoir quelle puissance votre future installation devrait avoir. Notre formulaire vous aide à réunir les informations essentielles.','L’évaluation professionnelle de la toiture et la planification détaillée sont ensuite réalisées par les entreprises d’installation.']},
  {id:15,question:'Comment reconnaître la meilleure offre photovoltaïque ?',answer:['Le prix le plus bas ne correspond pas automatiquement à la meilleure offre. Comparez notamment la puissance, la qualité des panneaux et des onduleurs, les batteries éventuelles, les garanties, les prestations de montage et les conditions contractuelles.','Les conseils et la disponibilité de l’installateur comptent aussi. Comparer jusqu’à trois offres aide à comprendre les différences et à choisir selon votre projet et votre budget.']},
  {id:16,question:'Qui est responsable des garanties et du service après l’installation ?',answer:['L’entreprise mandatée est responsable de l’installation et des prestations prévues au contrat. Les garanties des panneaux, onduleurs et autres composants dépendent des conditions des fabricants et des accords avec l’installateur.','PvPro.ch met en relation, mais ne réalise pas l’installation et ne fournit pas sa propre garantie d’installation. Nous vous recommandons de vérifier soigneusement les conditions de garantie et les services avant de signer le contrat.']},
  {id:17,question:'Puis-je faire une demande pour une installation dans quelques mois ?',answer:['Oui. Tous les propriétaires ne souhaitent pas une installation immédiate. Vous pouvez faire une demande pour vous informer d’abord sur les prix, les possibilités techniques et les prestataires.','Indiquez votre calendrier approximatif aussi clairement que possible pour que les partenaires comprennent mieux votre situation.']},
  {id:18,question:'Les offres sont-elles directement comparables ?',answer:['Vous pouvez en principe comparer les offres reçues. Toutefois, les installations proposées peuvent différer par la puissance, les composants, les garanties et les prestations incluses.','Nous recommandons donc de ne pas regarder uniquement le prix total. En cas d’incertitude, demandez directement une explication détaillée à l’entreprise d’installation.']},
  {id:19,question:'Puis-je obtenir une offre d’un installateur de mon canton ou à proximité ?',answer:['Nous cherchons à transmettre les demandes à des partenaires actifs au lieu du projet. Nous tenons compte de l’emplacement du bien et des zones d’intervention des installateurs.','La disponibilité d’une entreprise proche dépend du lieu et du projet concernés.']},
  {id:20,question:'Les entreprises photovoltaïques peuvent-elles devenir partenaires de PvPro.ch ?',answer:['Oui. Nous souhaitons régulièrement rencontrer des entreprises photovoltaïques professionnelles intéressées par de nouvelles demandes clients dans leurs zones d’intervention.','Les partenaires reçoivent des contacts préqualifiés dont l’intérêt pour le projet a déjà été vérifié par téléphone. Chaque demande est transmise à trois entreprises au maximum. Les installateurs intéressés peuvent nous contacter directement pour connaître la collaboration et ses conditions. Contact : info@pvpro.ch.']}
];
