import type { CompanyQuestion } from './types';

export const itQuestions: CompanyQuestion[] = [
  {id:1,question:'PvPro.ch è davvero gratuito?',answer:['Sì. PvPro.ch è completamente gratuito e senza impegno per i proprietari. Non paghi per la richiesta, l’intermediazione o il confronto dei preventivi.','La piattaforma è finanziata dalle imprese fotovoltaiche che pagano per contatti clienti qualificati. Non ti vengono addebitati costi di intermediazione.']},
  {id:2,question:'Come funziona il confronto tramite PvPro.ch?',answer:['Prima compili il modulo online con informazioni sull’immobile e sul progetto fotovoltaico. Il team può poi contattarti telefonicamente per confermare i dati e chiarire eventuali domande.','Dopo la verifica, inoltriamo la richiesta a un massimo di tre imprese adatte che lavorano nel luogo del progetto. Possono contattarti direttamente, discutere il progetto e preparare un preventivo individuale. Decidi poi liberamente se collaborare e con quale impresa.']},
  {id:3,question:'Perché ricevo una chiamata dopo la richiesta?',answer:['Vogliamo verificare che la richiesta sia corretta e completa. Il team chiama gli interessati per confermare i dati importanti e conoscere meglio il progetto.','Possiamo così inoltrare la richiesta ai partner più adatti. La chiamata serve alla qualificazione e non ti impegna in alcun modo.']},
  {id:4,question:'Quanti preventivi riceverò?',answer:['Con PvPro.ch puoi ricevere fino a tre preventivi da imprese fotovoltaiche. Limitiamo volutamente l’inoltro a un massimo di tre imprese per consentire il confronto senza troppe chiamate da installatori.','Il numero effettivo dipende dal luogo, dal progetto e dalla disponibilità dei partner adatti. Tre preventivi non sono garantiti.']},
  {id:5,question:'Devo accettare uno dei preventivi?',answer:['No. La richiesta e il confronto sono completamente senza impegno. Puoi esaminare i preventivi con calma e decidere se installare un impianto fotovoltaico. Se nessuno ti convince, non sei tenuto ad accettarne uno.']},
  {id:6,question:'Quanto tempo passa prima di essere contattato?',answer:['Cerchiamo di elaborare tempestivamente le richieste. Dopo la verifica e l’inoltro ai partner adatti, le imprese possono contattarti direttamente.','I tempi per un preventivo concreto dipendono, tra l’altro, dalla disponibilità degli installatori e dalla complessità del progetto. Per alcuni progetti servono prima un’ulteriore consulenza o un sopralluogo. Non possiamo garantire una scadenza fissa per il contatto o il preventivo.']},
  {id:7,question:'Come seleziona PvPro.ch i partner installatori?',answer:['Diamo importanza alla collaborazione con imprese fotovoltaiche serie e professionali. Prima di collaborare ci informiamo sull’impresa, l’attività precedente, le recensioni disponibili, le referenze e i cantoni e le località in cui installa impianti. Anche la professionalità nella comunicazione è un criterio importante.','Vogliamo facilitare il contatto con imprese adatte. La selezione non sostituisce una certificazione tecnica indipendente e non garantisce l’esecuzione. Consulenza, preventivi e installazione sono responsabilità dell’impresa interessata.']},
  {id:8,question:'PvPro.ch installa direttamente impianti solari?',answer:['No. PvPro.ch è una piattaforma indipendente di confronto e intermediazione. Non eseguiamo direttamente installazioni fotovoltaiche.','La consulenza tecnica, i preventivi vincolanti e l’installazione vera e propria sono forniti dalle rispettive imprese fotovoltaiche.']},
  {id:9,question:'I miei dati personali vengono trasmessi ad altre imprese?',answer:['Per ricevere preventivi è necessario trasmettere alcuni dati della richiesta ai partner installatori adatti. La trasmissione avviene sulla base della tua richiesta ed è limitata a un massimo di tre imprese.','I dati servono a comprendere il progetto, contattarti e preparare un preventivo appropriato. Ulteriori informazioni sul trattamento sono disponibili nell’informativa sulla protezione dei dati.']},
  {id:10,question:'Posso ritirare la mia richiesta?',answer:['Sì. Se non vuoi proseguire, puoi contattarci in qualsiasi momento per telefono o e-mail. Elaboreremo il messaggio e interromperemo ulteriori inoltri, per quanto possibile.','Se i dati sono già stati trasmessi ai partner, questi potrebbero averti già contattato. Puoi rivolgerti a noi anche per domande sul trattamento o sulla cancellazione dei dati personali, in particolare scrivendo ad anfrage@pvpro.ch.']},
  {id:11,question:'Che cosa succede se nessun preventivo mi piace?',answer:['Non sei naturalmente obbligato ad accettarne uno. PvPro.ch vuole aiutarti a conoscere diverse possibilità e prendere una decisione informata.','Se i preventivi non corrispondono alle tue aspettative, puoi rinunciare all’installazione. Non ne derivano costi nei confronti di PvPro.ch.']},
  {id:12,question:'Posso richiedere anche un accumulo a batteria?',answer:['Sì. Se ti interessa una batteria oltre all’impianto fotovoltaico, puoi indicarlo nella richiesta.','Gli installatori possono valutare le soluzioni di accumulo adatte all’immobile e al consumo energetico. Contano, tra l’altro, dimensioni dell’impianto, consumo elettrico ed esigenze individuali.']},
  {id:13,question:'PvPro.ch è disponibile in tutta la Svizzera?',answer:['Sì. PvPro.ch opera in tutta la Svizzera. Gestiamo richieste dalla Svizzera tedesca, dalla Svizzera romanda e dal Ticino e collaboriamo con partner in diversi cantoni.','Gli installatori disponibili per un progetto specifico dipendono dal luogo e dalle esigenze del progetto.']},
  {id:14,question:'Posso inviare una richiesta senza conoscere il fotovoltaico?',answer:['Certamente. Non servono conoscenze tecniche né sapere già quale potenza dovrà avere l’impianto. Il modulo ti aiuta a raccogliere le informazioni principali.','La valutazione professionale del tetto e la progettazione concreta vengono poi effettuate dalle imprese installatrici.']},
  {id:15,question:'Come riconosco il miglior preventivo fotovoltaico?',answer:['Il prezzo più basso non è automaticamente il miglior preventivo. Confronta potenza, qualità dei moduli e degli inverter, eventuali batterie, garanzie, prestazioni di montaggio e condizioni contrattuali.','Contano anche consulenza e reperibilità dell’installatore. Il confronto di fino a tre preventivi aiuta a capire le differenze e a decidere secondo progetto e budget.']},
  {id:16,question:'Chi è responsabile delle garanzie e dell’assistenza dopo l’installazione?',answer:['L’impresa incaricata è responsabile dell’installazione e delle prestazioni concordate nel contratto. Le garanzie di moduli, inverter e altri componenti dipendono dalle condizioni dei produttori e dagli accordi con l’installatore.','PvPro.ch mette in contatto le parti ma non esegue installazioni e non offre una propria garanzia sull’installazione. Consigliamo di verificare attentamente garanzie e assistenza prima di firmare il contratto.']},
  {id:17,question:'Posso fare una richiesta se voglio installare tra qualche mese?',answer:['Sì. Non tutti i proprietari vogliono installare subito. Puoi fare una richiesta per informarti prima su prezzi, possibilità tecniche e diversi fornitori.','Indica i tempi approssimativi nel modo più chiaro possibile, così i partner possono valutare meglio la tua situazione.']},
  {id:18,question:'I preventivi sono direttamente confrontabili?',answer:['In linea di principio puoi confrontare i preventivi ricevuti. Tuttavia, gli impianti proposti possono differire per potenza, componenti, garanzie e prestazioni incluse.','Consigliamo quindi di non considerare soltanto il prezzo totale. Se qualcosa non è chiaro, chiedi direttamente all’impresa una spiegazione dettagliata.']},
  {id:19,question:'Posso ottenere un installatore del mio cantone o nelle vicinanze?',answer:['Cerchiamo di inoltrare le richieste a partner che lavorano nel luogo del progetto. Consideriamo l’ubicazione dell’immobile e le aree di intervento dei partner.','La disponibilità di un’impresa vicina dipende dal luogo e dal progetto specifici.']},
  {id:20,question:'Le imprese fotovoltaiche possono diventare partner di PvPro.ch?',answer:['Sì. Desideriamo conoscere regolarmente imprese fotovoltaiche professionali interessate a nuove richieste clienti nelle loro aree di attività.','I partner ricevono contatti prequalificati il cui interesse al progetto è già stato verificato per telefono. Ogni richiesta è inoltrata a un massimo di tre imprese. Gli installatori interessati possono contattarci direttamente per informazioni sulla collaborazione e sulle condizioni. Contatto: anfrage@pvpro.ch.']}
];
