import type { CompanyQuestion } from './types';

export const deQuestions: CompanyQuestion[] = [
  {id:1,question:'Ist PvPro.ch wirklich kostenlos?',answer:['Ja. Die Nutzung von PvPro.ch ist für Hauseigentümer vollständig kostenlos und unverbindlich. Sie bezahlen weder für die Anfrage noch für die Vermittlung oder den Vergleich der Angebote.','Unsere Plattform wird von den Photovoltaikunternehmen finanziert, die für die Vermittlung qualifizierter Kundenkontakte bezahlen. Für Sie entstehen dadurch keine Vermittlungsgebühren.']},
  {id:2,question:'Wie funktioniert der Vergleich über PvPro.ch?',answer:['Zunächst füllen Sie unser Online-Formular aus und beantworten einige Fragen zu Ihrer Immobilie und Ihrem geplanten Photovoltaikprojekt. Anschliessend kann unser Team Sie telefonisch kontaktieren, um Ihre Angaben zu bestätigen und offene Fragen zu klären.','Nach erfolgreicher Prüfung vermitteln wir Ihre Anfrage an maximal drei passende Photovoltaikunternehmen, die am Standort Ihres Projekts tätig sind. Diese können sich direkt mit Ihnen in Verbindung setzen, Ihr Vorhaben besprechen und ein individuelles Angebot erstellen. Anschliessend entscheiden Sie selbst, ob und mit welchem Unternehmen Sie zusammenarbeiten möchten.']},
  {id:3,question:'Warum werde ich nach meiner Anfrage telefonisch kontaktiert?',answer:['Wir möchten sicherstellen, dass Ihre Anfrage korrekt und vollständig ist. Deshalb ruft unser Team Interessenten an, um wichtige Angaben zu bestätigen und mehr über das geplante Projekt zu erfahren.','So können wir Ihre Anfrage möglichst gezielt an passende Installationspartner weiterleiten. Das Telefonat dient der Qualifizierung und verpflichtet Sie zu nichts.']},
  {id:4,question:'Wie viele Angebote erhalte ich?',answer:['Über PvPro.ch können Sie bis zu drei Angebote von Photovoltaik-Fachbetrieben erhalten. Wir beschränken die Weiterleitung bewusst auf maximal drei Unternehmen, damit Sie unterschiedliche Lösungen vergleichen können, ohne von zu vielen Installateuren kontaktiert zu werden.','Die tatsächliche Anzahl hängt von Ihrem Standort, Ihrem Projekt und der Verfügbarkeit geeigneter Partnerunternehmen ab. Drei Angebote sind nicht garantiert.']},
  {id:5,question:'Muss ich eines der Angebote annehmen?',answer:['Nein. Sowohl die Anfrage als auch der Vergleich sind vollständig unverbindlich. Sie können alle Angebote in Ruhe prüfen und selbst entscheiden, ob Sie eine Photovoltaikanlage installieren lassen möchten. Wenn Sie keines der Angebote überzeugt, müssen Sie keines annehmen.']},
  {id:6,question:'Wie lange dauert es, bis ich kontaktiert werde?',answer:['Wir versuchen, eingehende Anfragen möglichst zeitnah zu bearbeiten. Nachdem Ihre Anfrage überprüft und an passende Installationspartner vermittelt wurde, können die Unternehmen direkt mit Ihnen Kontakt aufnehmen.','Wie schnell Sie ein konkretes Angebot erhalten, hängt unter anderem von der Verfügbarkeit der Installateure und der Komplexität Ihres Projekts ab. Bei manchen Projekten ist zunächst eine zusätzliche Beratung oder eine Besichtigung vor Ort erforderlich. Eine feste Kontakt- oder Angebotsfrist können wir nicht garantieren.']},
  {id:7,question:'Wie wählt PvPro.ch seine Installationspartner aus?',answer:['Wir legen Wert auf die Zusammenarbeit mit seriösen und professionellen Photovoltaikunternehmen. Vor einer Zusammenarbeit informieren wir uns über das Unternehmen, seine bisherige Tätigkeit, verfügbare Kundenbewertungen, Referenzen und die Kantone und Orte, in denen es Installationen durchführt. Auch die Professionalität in der Kommunikation ist ein wichtiges Kriterium.','Unser Ziel ist es, Hauseigentümern den Kontakt zu geeigneten Fachbetrieben zu erleichtern. Die Auswahl ersetzt keine unabhängige technische Zertifizierung und ist keine Garantie für die Ausführung. Beratung, Angebote und Installation verantwortet der jeweilige Fachbetrieb.']},
  {id:8,question:'Installiert PvPro.ch selbst Solaranlagen?',answer:['Nein. PvPro.ch ist eine unabhängige Vergleichs- und Vermittlungsplattform. Wir führen selbst keine Photovoltaikinstallationen durch.','Die technische Beratung, die Erstellung verbindlicher Angebote sowie die eigentliche Installation erfolgen durch die jeweiligen Photovoltaikunternehmen.']},
  {id:9,question:'Werden meine persönlichen Daten an andere Unternehmen weitergegeben?',answer:['Damit Sie Angebote erhalten können, ist es notwendig, bestimmte Angaben aus Ihrer Anfrage an geeignete Installationspartner weiterzugeben. Die Weitergabe erfolgt auf Grundlage Ihrer Anfrage und ist auf maximal drei Unternehmen beschränkt.','Diese Informationen dienen dazu, Ihr Projekt zu verstehen, Kontakt mit Ihnen aufzunehmen und ein entsprechendes Angebot vorzubereiten. Weitere Informationen zur Datenbearbeitung finden Sie in unserer Datenschutzerklärung.']},
  {id:10,question:'Kann ich meine Anfrage wieder zurückziehen?',answer:['Ja. Falls Sie Ihre Anfrage nicht weiterverfolgen möchten, können Sie uns jederzeit telefonisch oder per E-Mail kontaktieren. Wir werden Ihre Mitteilung bearbeiten und weitere Vermittlungen Ihrer Anfrage, soweit möglich, stoppen.','Falls Ihre Informationen bereits an Installationspartner übermittelt wurden, können diese Sie unter Umständen bereits kontaktiert haben. Für Fragen zur Bearbeitung oder Löschung Ihrer personenbezogenen Daten können Sie sich ebenfalls an uns wenden, insbesondere unter anfrage@pvpro.ch.']},
  {id:11,question:'Was passiert, wenn mir keines der Angebote gefällt?',answer:['Dann sind Sie selbstverständlich nicht verpflichtet, eines davon anzunehmen. PvPro.ch soll Ihnen helfen, unterschiedliche Möglichkeiten kennenzulernen und eine informierte Entscheidung zu treffen.','Wenn die erhaltenen Angebote nicht Ihren Erwartungen entsprechen, können Sie auf eine Installation verzichten. Es entstehen Ihnen dadurch keine Gebühren gegenüber PvPro.ch.']},
  {id:12,question:'Kann ich auch einen Batteriespeicher anfragen?',answer:['Ja. Wenn Sie sich neben einer Photovoltaikanlage auch für einen Batteriespeicher interessieren, können Sie dies bei Ihrer Anfrage angeben.','Die Installationspartner können prüfen, welche Speichermöglichkeiten für Ihre Immobilie und Ihren Energieverbrauch infrage kommen. Dabei spielen unter anderem die Grösse der Anlage, Ihr Stromverbrauch und Ihre individuellen Bedürfnisse eine Rolle.']},
  {id:13,question:'Ist PvPro.ch in der ganzen Schweiz verfügbar?',answer:['Ja. PvPro.ch ist schweizweit tätig. Wir bearbeiten Anfragen aus der Deutschschweiz, der Romandie und dem Tessin und arbeiten mit Partnerunternehmen aus verschiedenen Kantonen zusammen.','Welche Installateure für ein bestimmtes Projekt verfügbar sind, hängt vom Standort und den Anforderungen des Vorhabens ab.']},
  {id:14,question:'Kann ich eine Anfrage stellen, wenn ich noch keine Ahnung von Photovoltaik habe?',answer:['Natürlich. Sie müssen weder technische Kenntnisse besitzen noch bereits wissen, welche Leistung Ihre zukünftige Solaranlage haben soll. Unser Formular hilft Ihnen dabei, die wichtigsten Informationen zusammenzustellen.','Die fachliche Beurteilung Ihres Daches und die konkrete Planung der Anlage erfolgen anschliessend durch die jeweiligen Installationsbetriebe.']},
  {id:15,question:'Wie erkenne ich, welches Photovoltaikangebot das beste ist?',answer:['Der günstigste Preis ist nicht automatisch das beste Angebot. Beim Vergleich sollten Sie unter anderem auf die Leistung der Anlage, die Qualität der Solarmodule und Wechselrichter, mögliche Batteriespeicher, Garantien, Montageleistungen und Vertragsbedingungen achten.','Auch die Beratung und die Erreichbarkeit des Installationsbetriebs können wichtig sein. Durch den Vergleich von bis zu drei Angeboten können Sie Unterschiede besser erkennen und eine Entscheidung treffen, die zu Ihrem Projekt und Budget passt.']},
  {id:16,question:'Wer ist für die Garantie und den Service nach der Installation verantwortlich?',answer:['Die Verantwortung für die Installation und die vertraglich vereinbarten Leistungen liegt beim beauftragten Installationsunternehmen. Garantien für Solarmodule, Wechselrichter und weitere Komponenten richten sich nach den jeweiligen Herstellerbedingungen und den Vereinbarungen mit dem Installateur.','PvPro.ch vermittelt den Kontakt, führt jedoch selbst keine Installationsarbeiten durch und übernimmt keine eigene Installationsgarantie. Wir empfehlen, Garantiebedingungen und Serviceleistungen vor der Vertragsunterzeichnung sorgfältig zu prüfen.']},
  {id:17,question:'Kann ich auch eine Anfrage stellen, wenn ich erst in einigen Monaten installieren möchte?',answer:['Ja. Nicht jeder Hauseigentümer möchte seine Photovoltaikanlage sofort installieren lassen. Sie können auch eine Anfrage stellen, wenn Sie sich zunächst über Preise, technische Möglichkeiten und verschiedene Anbieter informieren möchten.','Wichtig ist, dass Sie Ihre ungefähren zeitlichen Vorstellungen möglichst klar angeben. So können die Installationspartner Ihre Situation besser einschätzen.']},
  {id:18,question:'Sind die Angebote direkt miteinander vergleichbar?',answer:['Grundsätzlich können Sie die erhaltenen Angebote miteinander vergleichen. Allerdings können sich die vorgeschlagenen Anlagen hinsichtlich Leistung, Komponenten, Garantien und enthaltenen Dienstleistungen unterscheiden.','Deshalb empfehlen wir, nicht nur den Gesamtpreis zu betrachten. Bei Unklarheiten sollten Sie die jeweiligen Installationsunternehmen direkt um eine detaillierte Erklärung bitten.']},
  {id:19,question:'Kann ich einen Installateur aus meinem Kanton oder meiner Umgebung erhalten?',answer:['Unser Ziel ist es, Anfragen möglichst an Partnerunternehmen weiterzuleiten, die am Standort des jeweiligen Projekts tätig sind. Dabei berücksichtigen wir den Standort der Immobilie und die Einsatzgebiete unserer Installationspartner.','Ob ein Unternehmen aus Ihrer Umgebung verfügbar ist, hängt vom jeweiligen Standort und Projekt ab.']},
  {id:20,question:'Können Photovoltaikunternehmen Partner von PvPro.ch werden?',answer:['Ja. Wir möchten laufend professionelle Photovoltaikunternehmen kennenlernen, die neue Kundenanfragen aus ihren Einsatzgebieten erhalten möchten.','Unsere Partner erhalten vorqualifizierte Kundenkontakte, bei denen das Interesse am Projekt bereits telefonisch überprüft wurde. Jede Anfrage wird an maximal drei Unternehmen weitergeleitet. Interessierte Installationsbetriebe können sich direkt bei uns über die Zusammenarbeit und die Konditionen informieren. Kontakt: info@pvpro.ch.']}
];
