import type { CompanyQuestion } from './types';

export const enQuestions: CompanyQuestion[] = [
  {id:1,question:'Is PvPro.ch really free?',answer:['Yes. PvPro.ch is completely free for homeowners, with no obligation. You pay nothing for submitting a request, receiving introductions or comparing quotes.','The platform is funded by photovoltaic companies that pay for qualified customer contacts. You do not incur any referral fees.']},
  {id:2,question:'How does comparison through PvPro.ch work?',answer:['First, complete our online form with details about your property and planned photovoltaic project. Our team may then call you to confirm your information and clarify outstanding questions.','After successful checks, we refer your request to no more than three suitable photovoltaic businesses working at your project location. They may contact you directly, discuss your plans and prepare an individual quote. You then decide whether to proceed and with which company.']},
  {id:3,question:'Why am I called after submitting a request?',answer:['We want to make sure your request is correct and complete. Our team calls prospective customers to confirm important details and learn more about the planned project.','This helps us refer the request to appropriate installation partners. The call is for qualification and does not commit you to anything.']},
  {id:4,question:'How many quotes will I receive?',answer:['Through PvPro.ch you may receive up to three quotes from photovoltaic installation businesses. We deliberately limit forwarding to no more than three companies so you can compare different solutions without being contacted by too many installers.','The actual number depends on your location, project and the availability of suitable partners. Three quotes are not guaranteed.']},
  {id:5,question:'Do I have to accept a quote?',answer:['No. Both the request and the comparison are entirely without obligation. You can review every quote at your own pace and decide whether you want a photovoltaic installation. If none of the quotes convinces you, you do not have to accept any of them.']},
  {id:6,question:'How long will it take before someone contacts me?',answer:['We try to process incoming requests promptly. Once we have checked your request and referred it to suitable partners, the companies may contact you directly.','The time needed to receive a specific quote depends on factors including installer availability and project complexity. Some projects first require further advice or a site visit. We cannot guarantee a fixed deadline for contact or a quote.']},
  {id:7,question:'How does PvPro.ch select installation partners?',answer:['We value cooperation with reputable, professional photovoltaic businesses. Before working together, we learn about their business, previous activity, available customer reviews, references and the cantons and locations where they install systems. Professional communication is also an important criterion.','Our aim is to make it easier for homeowners to contact suitable businesses. Selection is not an independent technical certification or a guarantee of delivery. Advice, quotes and installation are the responsibility of the installer concerned.']},
  {id:8,question:'Does PvPro.ch install solar systems itself?',answer:['No. PvPro.ch is an independent comparison and referral platform. We do not carry out photovoltaic installations ourselves.','Technical advice, binding quotes and the installation itself are provided by the respective photovoltaic companies.']},
  {id:9,question:'Will my personal data be shared with other companies?',answer:['To receive quotes, certain information from your request must be shared with suitable installation partners. Sharing is based on your request and is limited to no more than three companies.','The information helps them understand your project, contact you and prepare an appropriate quote. Our privacy policy provides further information about data processing.']},
  {id:10,question:'Can I withdraw my request?',answer:['Yes. If you no longer wish to pursue your request, you can contact us at any time by phone or email. We will process your message and stop further referrals where possible.','If your details have already been passed to partners, they may already have contacted you. You can also contact us about the processing or deletion of your personal data, particularly at anfrage@pvpro.ch.']},
  {id:11,question:'What if I do not like any of the quotes?',answer:['You are under no obligation to accept any of them. PvPro.ch is intended to help you understand different possibilities and make an informed decision.','If the quotes do not meet your expectations, you can decide not to install a system. This does not result in any fees payable to PvPro.ch.']},
  {id:12,question:'Can I also request battery storage?',answer:['Yes. If you are interested in a battery alongside a photovoltaic installation, you can indicate this in your request.','Installation partners can assess storage options suited to your property and energy use. Factors include system size, electricity consumption and your individual needs.']},
  {id:13,question:'Is PvPro.ch available throughout Switzerland?',answer:['Yes. PvPro.ch operates across Switzerland. We handle requests from German-speaking Switzerland, French-speaking Switzerland and Ticino, working with partners in different cantons.','The installers available for a particular project depend on its location and requirements.']},
  {id:14,question:'Can I submit a request if I know nothing about photovoltaics?',answer:['Of course. You do not need technical knowledge or to know what capacity your future system should have. Our form helps you gather the essential information.','The professional assessment of your roof and the detailed system planning are then carried out by the installation businesses.']},
  {id:15,question:'How do I identify the best photovoltaic quote?',answer:['The lowest price is not automatically the best quote. Compare system capacity, the quality of panels and inverters, possible battery storage, warranties, mounting services and contract terms.','Advice and how accessible the installer is can also matter. Comparing up to three quotes helps you recognise differences and make a decision suited to your project and budget.']},
  {id:16,question:'Who is responsible for warranties and service after installation?',answer:['The company you commission is responsible for the installation and the services agreed in the contract. Warranties for solar panels, inverters and other components depend on the manufacturers’ terms and your agreements with the installer.','PvPro.ch introduces the contact but does not perform installation work or provide its own installation warranty. We recommend carefully checking warranty terms and service arrangements before signing a contract.']},
  {id:17,question:'Can I make a request if I want to install in a few months?',answer:['Yes. Not every homeowner wants an immediate installation. You can submit a request to first learn about prices, technical options and different providers.','Please describe your approximate timescale as clearly as possible so installation partners can better understand your situation.']},
  {id:18,question:'Are the quotes directly comparable?',answer:['You can generally compare the quotes received. However, proposed systems can differ in capacity, components, warranties and included services.','We therefore recommend considering more than the total price. If anything is unclear, ask the installation companies directly for a detailed explanation.']},
  {id:19,question:'Can I receive a quote from an installer in my canton or nearby?',answer:['We aim to refer requests to partners who work at the project location. We consider the property location and the places our installation partners serve.','Whether a nearby company is available depends on your particular location and project.']},
  {id:20,question:'Can photovoltaic companies become PvPro.ch partners?',answer:['Yes. We are always interested in meeting professional photovoltaic companies that want new customer requests from the places they serve.','Partners receive prequalified customer contacts whose project interest has already been checked by phone. Each request is forwarded to no more than three companies. Interested installers can contact us directly for information on cooperation and its terms. Contact: anfrage@pvpro.ch.']}
];
