export default function DossierGuideStyles() {
  return <style>{`
    .dossier-guide{--dossier-forest:#17322d;--dossier-moss:#edf2e9;--dossier-paper:#fffdf7;--dossier-gold:#bd8a18;--dossier-ink:#29453d;--dossier-rule:#d6dbd0}
    .dossier-guide .dossier-guide-hero{padding:4.2rem 0 3.3rem;background:linear-gradient(110deg,#f3efdf 0%,#fffdf7 60%,#e8f0e5 100%)}
    .dossier-hero-frame{display:grid;grid-template-columns:minmax(0,1.34fr) minmax(18rem,.86fr);gap:3rem;align-items:end}.dossier-hero-copy h1{max-width:760px}.dossier-hero-copy .guide-hero-lead{display:grid;gap:.55rem}.dossier-fact-shelf{border-top:3px solid var(--dossier-gold);background:rgba(255,253,247,.83);padding:1.05rem 1.1rem 1.15rem;box-shadow:8px 10px 0 rgba(189,138,24,.1)}.dossier-shelf-label{font-size:.77rem;font-weight:850;letter-spacing:.1em;text-transform:uppercase;color:#786319}.dossier-facts{display:grid;gap:.55rem;margin-top:.8rem}.dossier-facts article{border-top:1px solid var(--dossier-rule);padding-top:.62rem}.dossier-facts strong{display:block;font-size:clamp(1.18rem,2vw,1.55rem);line-height:1.05;letter-spacing:-.035em}.dossier-facts span{display:block;margin-top:.2rem;font-size:.9rem;line-height:1.38;color:var(--guide-muted)}.dossier-fact-sources{display:block;margin-top:.3rem;font-size:.73rem;line-height:1.3;color:#667771}.dossier-fact-sources a{text-decoration:underline}.dossier-facts--4{grid-template-columns:1fr 1fr;column-gap:1rem}.dossier-facts--4 article:nth-child(-n+2){border-top:0;padding-top:0}
    .dossier-guide .guide-section{padding:3.7rem 0}.dossier-guide .guide-module-wrap{margin-top:1.65rem}.dossier-guide .guide-module>h3{font-size:clamp(1.35rem,2.2vw,1.75rem)}.dossier-guide .guide-module-intro{font-size:1rem}.dossier-module{max-width:960px;border-top:1px solid var(--dossier-rule);padding-top:1.3rem}.dossier-module h4{font-size:1rem;font-weight:850;line-height:1.25}.dossier-module p{line-height:1.58;color:var(--guide-muted)}.dossier-module .guide-source-links{margin-top:.5rem}.dossier-item-detail{margin-top:.5rem!important;font-size:.88rem;font-weight:750;color:#756020!important}
    .dossier-roof-paths{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--dossier-rule);border:1px solid var(--dossier-rule)}.dossier-roof-paths li{display:grid;grid-template-columns:2.2rem 1fr;gap:.7rem;background:var(--dossier-paper);padding:1rem}.dossier-step-no{font-size:.78rem;font-weight:900;color:var(--dossier-gold)}.dossier-roof-paths p{margin-top:.42rem;font-size:.92rem}
    .dossier-formula{max-width:700px;border-left:3px solid var(--dossier-gold);padding:.3rem 0 .3rem .85rem;font-size:1.02rem!important;color:var(--dossier-ink)!important}.dossier-checklist{display:grid;grid-template-columns:1fr 1fr;gap:.65rem;margin-top:1rem}.dossier-checklist article{display:grid;grid-template-columns:2.2rem 1fr;gap:.65rem;border:1px solid var(--dossier-rule);background:var(--dossier-paper);padding:1rem}.dossier-checklist article>span{font-size:.75rem;font-weight:900;color:var(--dossier-gold)}.dossier-checklist p{margin-top:.35rem;font-size:.9rem}
    .dossier-power-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border-top:1px solid var(--dossier-rule)}.dossier-power-steps li{position:relative;padding:1rem 1.2rem 0 0}.dossier-power-steps li+li{border-left:1px solid var(--dossier-rule);padding-left:1.2rem}.dossier-power-steps span{font-size:.76rem;font-weight:850;color:#806817}.dossier-power-steps h4{margin-top:.38rem}.dossier-power-steps p{margin-top:.38rem;font-size:.92rem}
    .dossier-winter{display:grid;grid-template-columns:minmax(16rem,.95fr) 1.05fr;gap:1.35rem;align-items:start}.dossier-angle-figure{margin:0;border:1px solid var(--dossier-rule);background:#f4f1e5;padding:.8rem}.dossier-angle-figure svg{display:block;width:100%;height:auto}.dossier-angle-figure figcaption{border-top:1px solid #ddd7c5;padding:.55rem .15rem .05rem;font-size:.86rem;font-weight:700;color:var(--dossier-ink)}.dossier-svg-ground,.dossier-svg-house{fill:none;stroke:#4e655d;stroke-width:3}.dossier-svg-panel{fill:none;stroke:#17322d;stroke-width:12;stroke-linecap:round}.dossier-svg-arc{fill:none;stroke:#bd8a18;stroke-width:6}.dossier-svg-ticks{fill:none;stroke:#bd8a18;stroke-width:3}.dossier-svg-pivot{fill:#17322d}.dossier-svg-label{font-family:var(--font-sans);font-size:20px;font-weight:800;fill:#7b5c12}.dossier-svg-caption{font-family:var(--font-sans);font-size:16px;fill:#4e655d}.dossier-winter-facts{display:grid;gap:.65rem}.dossier-winter-facts article{border-left:3px solid var(--dossier-gold);padding:.05rem 0 .1rem .8rem}.dossier-winter-facts p{margin-top:.28rem;font-size:.91rem}.dossier-sequence{grid-column:1/-1;display:flex;align-items:center;gap:.65rem;border-top:1px solid var(--dossier-rule);padding-top:1rem;font-size:.85rem}.dossier-sequence b{font-weight:800}.dossier-sequence i{font-style:normal;color:var(--dossier-gold)}
    .dossier-law-timeline{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.dossier-law-timeline article{min-height:12rem;padding:1.1rem;border:1px solid var(--dossier-rule);background:var(--dossier-paper)}.dossier-law-timeline .dossier-law-now{border-top:4px solid var(--dossier-forest)}.dossier-law-timeline .dossier-law-transition{border-top:4px solid var(--dossier-gold);background:#fff9e9}.dossier-law-timeline article>span{font-size:.76rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#76601b}.dossier-law-timeline h4{margin-top:.55rem}.dossier-law-timeline p{margin-top:.42rem;font-size:.93rem}.dossier-rows{margin-top:1rem;border-top:1px solid var(--dossier-rule)}.dossier-rows>div{display:grid;grid-template-columns:1fr 1fr 1fr;gap:.6rem;padding:.75rem 0;border-bottom:1px solid var(--dossier-rule);font-size:.9rem}.dossier-rows dt{font-weight:800}.dossier-rows dd{color:var(--guide-muted)}.dossier-rows>div>div{grid-column:1/-1}
    .dossier-guide .dossier-guide-map .guide-module-wrap{max-width:960px}.dossier-guide .dossier-guide-map [class*="map"]{min-height:300px!important;height:min(360px,58vw)!important}.dossier-guide .guide-cta-band{padding:2.2rem 0}
    .dossier-item-value{display:block;margin-bottom:.32rem;font-size:.78rem;font-weight:900;letter-spacing:.035em;color:#806817}.dossier-roof-outcomes{margin-top:1rem;border-top:1px solid var(--dossier-rule);padding-top:.9rem}.dossier-roof-outcomes>h4{font-size:.85rem;letter-spacing:.06em;text-transform:uppercase;color:#756020}.dossier-roof-outcomes>div{display:grid;grid-template-columns:1fr 1fr;gap:.65rem;margin-top:.6rem}.dossier-roof-outcomes article{border-left:3px solid var(--dossier-gold);background:#f7f6ef;padding:.85rem .9rem}.dossier-roof-outcomes p{margin-top:.35rem;font-size:.9rem}
    .dossier-svg-wedge{fill:rgba(213,163,41,.2);stroke:none}.dossier-svg-panel rect{fill:#17322d;stroke:#f4f1e5;stroke-width:2}.dossier-svg-panel path{fill:none;stroke:#92b4a6;stroke-width:1.5}.dossier-svg-panel{stroke:none}.dossier-rows .dossier-row-sources{grid-column:1/-1}.dossier-guide .dossier-guide-map>section{padding-block:2.75rem}.dossier-guide .dossier-guide-map .relative{height:360px!important;min-height:0!important}
    @media(max-width:1000px){.dossier-hero-frame{grid-template-columns:1fr;gap:1.55rem}.dossier-fact-shelf{max-width:760px}.dossier-facts--4{grid-template-columns:1fr 1fr}}@media(max-width:767px){.dossier-guide .dossier-guide-hero{padding:3.1rem 0 2.55rem}.dossier-hero-frame{grid-template-columns:1fr;gap:1.55rem}.dossier-fact-shelf{box-shadow:5px 6px 0 rgba(189,138,24,.1)}.dossier-facts--4{grid-template-columns:1fr}.dossier-facts--4 article:nth-child(2){border-top:1px solid var(--dossier-rule);padding-top:.62rem}.dossier-guide .guide-section{padding:3rem 0}.dossier-roof-paths,.dossier-checklist,.dossier-law-timeline,.dossier-winter,.dossier-roof-outcomes>div{grid-template-columns:1fr}.dossier-power-steps{grid-template-columns:1fr;gap:.8rem}.dossier-power-steps li+li{border-left:0;border-top:1px solid var(--dossier-rule);padding-left:0;padding-top:1rem}.dossier-winter{gap:1rem}.dossier-angle-figure{padding:.45rem}.dossier-sequence{display:grid;grid-template-columns:1fr auto;gap:.45rem .8rem}.dossier-sequence i{transform:rotate(90deg)}.dossier-sequence b{padding:.5rem 0}.dossier-rows>div{grid-template-columns:1fr}.dossier-rows .dossier-row-sources{grid-column:auto}.dossier-guide .dossier-guide-map .relative{height:300px!important}.dossier-guide .dossier-guide-map>section{padding-block:2rem}}
    @media (max-width: 767px) {
      .dossier-sequence { grid-template-columns: 1fr; gap: 0; text-align: center; }
      .dossier-sequence i { justify-self: center; width: 1rem; height: 1rem; line-height: 1; }
    }
  `}</style>;
}