export default function NextGuideAdditions() {
  return <style>{`
    .next-guide-hero .guide-visual-sources,.next-programme dd,.next-selector-result,.next-trigger-card,.next-traffic-card{overflow-wrap:anywhere}
    .next-fr-question{margin-top:1rem;font-size:.82rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#786319}.next-fr-primary{margin-top:.55rem;border-radius:.75rem;background:var(--guide-ink);padding:1rem;color:#fffdf7}.next-fr-primary strong{display:block;font-size:2rem;line-height:1}.next-fr-primary span{display:block;margin-top:.35rem;font-size:.85rem;line-height:1.4;color:#d7e1d6}.next-fr-primary .guide-visual-sources{color:#d7e1d6}.next-fr-limits{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;margin-top:.65rem}.next-fr-limits .next-hero-fact{display:block;padding:.7rem}.next-fr-limits .next-hero-fact strong{font-size:1rem}.next-fr-limits .next-hero-fact span{display:block;margin-top:.3rem;font-size:.72rem}.next-fr-limits .guide-visual-sources{font-size:.62rem}
    .next-ge-trigger-row{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;margin-top:1rem}.next-ge-trigger-row article{min-width:0;border-radius:.65rem;background:#edf2e9;padding:.75rem}.next-ge-trigger-row b{display:block;font-size:.67rem;color:#786319}.next-ge-trigger-row strong{display:block;margin-top:.35rem;font-size:.88rem;overflow-wrap:anywhere}.next-ge-trigger-row span{display:block;margin-top:.25rem;font-size:.71rem;line-height:1.35;color:var(--guide-muted);overflow-wrap:anywhere}.next-ge-trigger-row .guide-visual-sources{font-size:.6rem}.next-ge-deadline{display:grid;grid-template-columns:5rem 1fr;gap:.6rem;align-items:start;margin-top:.65rem;border-top:1px solid var(--guide-line);padding-top:.7rem}.next-ge-deadline strong{font-size:1.1rem}.next-ge-deadline span{font-size:.78rem;line-height:1.4;color:var(--guide-muted)}.next-ge-deadline .guide-visual-sources{grid-column:2}
    .next-gl-hero{margin-top:1rem}.next-gl-angle{position:relative;min-height:8.5rem;overflow:hidden;border-radius:.75rem;background:#e7eee3;padding:1rem 1rem 1rem 53%}.next-gl-baseline{position:absolute;bottom:20%;left:8%;right:8%;border-top:2px solid var(--guide-ink)}.next-gl-panel{position:absolute;bottom:20%;left:31%;height:7.3rem;width:5px;transform:rotate(-15deg);transform-origin:bottom;background:var(--guide-accent)}.next-gl-angle strong{display:block;font-size:2rem;line-height:1}.next-gl-angle span{display:block;margin-top:.35rem;font-size:.8rem;line-height:1.35;color:var(--guide-muted)}.next-gl-rest{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;margin-top:.65rem}.next-gl-rest .next-hero-fact{display:block;padding:.65rem}.next-gl-rest .next-hero-fact strong{font-size:1rem}.next-gl-rest .next-hero-fact span{display:block;margin-top:.25rem;font-size:.7rem}.next-gl-rest .guide-visual-sources{font-size:.6rem}
    @media(max-width:900px){.next-guide-hero .guide-hero-layout{grid-template-columns:1fr;gap:1.8rem}}
    .next-guide-hero .next-gl-baseline{right:55%}
    @media(max-width:767px){.next-fr-limits,.next-ge-trigger-row,.next-gl-rest{grid-template-columns:1fr}.next-gl-angle{padding-left:48%}}
  `}</style>;
}