import type { SubsidyContent } from './types';

export const de: SubsidyContent = {
  home: 'Startseite',
  breadcrumb: 'Brotkrümelnavigation',
  overview: 'Alle Förderungen im Überblick',
  quote: 'Kostenlose Solarofferten anfordern',
  contents: 'Auf dieser Seite',
  modelNote: 'Diese Angaben übernehmen das bestehende Rechenmodell von PvPro.ch mit Stand September 2026. Die Quellenangabe des Modells ist keine neue Prüfung der aktuell gültigen Tarife. Alle Beträge sind unverbindliche Richtwerte, kein Förderanspruch und keine verbindliche Zusage.',
  official: 'Verbindliche Bedingungen bei Pronovo prüfen',
  officialNote: 'Massgebend sind die für Ihr Projekt geltenden Bedingungen, Tarife und Entscheide. Die offizielle Pronovo-Website ist die Anlaufstelle für die Bundesförderung.',
  crossFederal: 'Einmalvergütung des Bundes im Detail',
  crossCantonal: 'Kantonale und kommunale Förderung abklären',
  calculatorTitle: 'Variable Komponente abschätzen',
  calculatorNote: 'Dieser Rechner modelliert ausschliesslich den indikativen variablen Leistungsbeitrag. Der zusätzliche Grundbeitrag ist nicht beziffert und nicht enthalten. «Förderung» bezeichnet hier nur diese variable Komponente; «Effektiv» ist lediglich Bruttokosten minus Modellbeitrag, keine garantierte Nettoinvestition.',
  examplesId: 'rechenbeispiele',
  examplesTitle: 'Vier Anlagengrössen – transparent gerechnet',
  examplesIntro: 'Vergleichen Sie die Bruttokosten mit dem reinen Modellabzug. Der Grundbeitrag, zusätzliche Programme und steuerliche Effekte sind nicht eingerechnet.',
  tableHeaders: ['Anlagenleistung', 'Bruttokosten, Richtwert', 'Variable Komponente, Richtwert', 'Kosten minus variable Komponente'],
  tableCaption: 'Indikative Modellbeispiele ohne Batteriespeicher, keine verbindliche Förderberechnung',
  tableNote: 'Die letzte Spalte zeigt nur eine Rechendifferenz. Finanzieren Sie die Bruttokosten und klären Sie Auszahlung und bewilligte Beiträge separat. Die tatsächliche Offerte und der Förderentscheid können abweichen.',
  rateLabels: ['Je kWp für die ersten 30 kWp', 'Je zusätzlichem kWp oberhalb 30 kWp'],
  rateNote: 'Variable Sätze des bestehenden Seitenmodells, nicht neu verifizierte aktuelle Tarife. Die Leistungsgrenze in diesem Rechenmodell ist keine Aussage zur Einteilung in KLEIV oder GREIV.',
  directoryId: 'kantonsverzeichnis',
  directoryTitle: 'Lokale Solarratgeber nach Kanton',
  directoryIntro: 'Alle Einträge unseres bestehenden Kantonsverzeichnisses führen zu lokalen Solarratgebern von PvPro.ch. Sie sind keine verifizierten offiziellen Fördertabellen. Erkundigen Sie sich zusätzlich bei Kanton, Gemeinde und Elektrizitätswerk.',
  directoryNote: 'Der gemeinsame Eintrag Basel deckt Basel-Stadt und Basel-Landschaft ab. Das Verzeichnis bildet die bestehende Seitenabdeckung ab und behauptet nicht, für jeden Kanton eine eigene Förderübersicht zu enthalten.',
  zurichTitle: 'Bestehender Förderratgeber für den Kanton Zürich',
  zurichNote: 'Dieser Ratgeber ergänzt die lokale Orientierung. Lassen Sie allgemeine Aussagen zu Zürcher Programmen für Ihr Vorhaben bestätigen. Daraus folgt weder ein zugesicherter Speicherbeitrag noch ein auf andere Kantone übertragbarer Anspruch.',
  federal: {
    title: 'Einmalvergütung für Solaranlagen in der Schweiz',
    shortTitle: 'Einmalvergütung',
    description: 'Einmalvergütung verstehen: Pronovo, KLEIV und GREIV, indikative Rechenbeispiele, Unterlagen und Ablauf der Bundesförderung.',
    eyebrow: 'Bundesförderung · Pronovo',
    intro: 'Was gehört zur Einmalvergütung, was zeigt der Rechner – und was muss vor der Investition geklärt sein? Hier finden Sie den Weg von der Vorbereitung bis zum Förderentscheid, ohne eine Auszahlung vorwegzunehmen.',
    summaryTitle: 'Das Wichtigste vor der Planung',
    summary: ['Pronovo verwaltet die Einmalvergütung des Bundes.', 'Grundbeitrag und variable Komponente auseinanderhalten.', 'Projektbedingungen und bewilligte Höhe individuell bestätigen lassen.'],
    sections: [
      {
        id: 'einmalverguetung-verstehen',
        title: 'Was die Einmalvergütung ist – und was nicht',
        intro: 'Die Einmalvergütung unterstützt die Investition in eine Photovoltaikanlage. Sie ist eine einmalige Förderung und nicht die Vergütung für laufend eingespeisten Strom.',
        cards: [
          { title: 'Bund und Pronovo', text: 'Die Förderung kommt vom Bund und wird durch Pronovo administriert. Pronovo ist für das Förderverfahren zuständig; eine Installateurofferte oder Berechnung von PvPro.ch ersetzt keinen Entscheid.' },
          { title: 'Grundbeitrag und Leistungsbeitrag', text: 'Im bestehenden Seitenmodell wird nur die leistungsabhängige variable Komponente berechnet. Der zusätzliche Grundbeitrag bleibt unbeziffert und ausgeschlossen. Ein gültiger Gesamtbetrag lässt sich daraus nicht ableiten.' },
          { title: 'KLEIV: kleinere Anlagen', text: 'KLEIV bezeichnet die kleine Einmalvergütung. Prüfen Sie mit Pronovo, welche Kategorie und welche Bedingungen für das konkrete Projekt gelten. Eine private Nutzung allein bestätigt die Berechtigung nicht.' },
          { title: 'GREIV: grössere Anlagen', text: 'GREIV bezeichnet die grosse Einmalvergütung. Bei grösseren Vorhaben müssen das passende Verfahren und mögliche zusätzliche Anforderungen geprüft werden. Dieser Ratgeber legt keine Leistungsgrenzen für die Programme fest.' },
        ],
      },
      {
        id: 'anspruch-und-finanzierung',
        title: 'Berechtigung und Finanzierung getrennt prüfen',
        intro: 'Ein rechnerischer Betrag sagt weder aus, ob Ihr Vorhaben förderfähig ist, noch wann Geld verfügbar wäre. Lassen Sie die Zuordnung vor der verbindlichen Investitionsentscheidung prüfen.',
        cards: [
          { title: 'Projekt statt Pauschalzusage', text: 'Anlagenart, Leistungsdaten, Standort, geplante Inbetriebnahme und die zum Projekt gehörenden Bedingungen müssen zusammenpassen. Klären Sie auch, wie Erweiterungen oder Änderungen behandelt werden.' },
          { title: 'Bruttokosten einplanen', text: 'Der Förderbeitrag wird nicht automatisch mit der Installateurrechnung verrechnet. Vereinbaren Sie die Finanzierung und Zahlungsbedingungen unabhängig von einem noch offenen Förderentscheid.' },
          { title: 'Weitere Beiträge separat', text: 'Kantonale oder kommunale Programme haben eigene Anträge und Fristen. Prüfen Sie diese vor einem bindenden Auftrag; eine Anmeldung bei Pronovo ersetzt den lokalen Antrag nicht.' },
          { title: 'Zuständigkeiten festhalten', text: 'Vereinbaren Sie schriftlich, wer registriert, Unterlagen einreicht, Rückfragen beantwortet und Änderungen meldet. Auch wenn der Installateur unterstützt, sollten Sie Bestätigungen und Aktenzeichen aufbewahren.' },
        ],
      },
    ],
    process: {
      id: 'anmeldung-und-auszahlung',
      title: 'Von der Vorbereitung bis zur möglichen Auszahlung',
      intro: 'Die Reihenfolge und die notwendigen Unterlagen müssen zum anwendbaren Verfahren passen. Die folgenden Stationen beschreiben den Ablauf, ohne eine Bearbeitungs- oder Auszahlungsfrist zu versprechen.',
      cards: [
        { title: 'Bedingungen vorab abklären', text: 'Passendes Pronovo-Verfahren, Projektberechtigung und erforderliche Nachweise prüfen. Lokale Förderfristen vor Bestellung separat kontrollieren und Verantwortlichkeiten vereinbaren.' },
        { title: 'Installation und Inbetriebnahme dokumentieren', text: 'Die Anlage fachgerecht erstellen lassen. Leistungsdaten, technische Nachweise, Inbetriebnahme und Rechnungen für das Verfahren nachvollziehbar sammeln.' },
        { title: 'Bei Pronovo registrieren', text: 'Anlage nach den Vorgaben des zuständigen Verfahrens anmelden und vollständige Unterlagen übermitteln. Der Installateur kann dies übernehmen, wenn es vereinbart ist.' },
        { title: 'Prüfung und Rückfragen', text: 'Pronovo beziehungsweise die zuständigen Stellen prüfen Anlage und Dossier. Fehlende Nachweise ergänzen und Änderungen transparent melden. Die Berechnung allein ist keine Bewilligung.' },
        { title: 'Entscheid und Zahlung abgleichen', text: 'Bewilligte Höhe, Bedingungen und Zahlungsangaben prüfen. Eine Auszahlung richtet sich nach dem Verfahren und dessen Bearbeitung; ein fixer Termin wird hier nicht zugesichert.' },
      ],
    },
    checklistTitle: 'Unterlagen für die Vorbereitung',
    checklistIntro: 'Diese Liste hilft beim Gespräch mit dem Installateur. Pronovo kann je nach Verfahren weitere oder anders ausgestaltete Nachweise verlangen.',
    checklist: ['Adresse der Anlage, Eigentumsverhältnisse und Kontakt der antragstellenden Person.', 'Offerte mit klarer Anlagenleistung, Komponenten und getrennten Kostenpositionen.', 'Technische Planung und die für das Projekt geforderten Anschluss- und Bewilligungsnachweise.', 'Geplante sowie später dokumentierte Inbetriebnahme und Leistungsdaten.', 'Rechnungen, Ausführungsnachweise und die verlangten Bestätigungen.', 'Vereinbarung zur Anmeldung, Aktenzeichen, Rückfragen und Zahlungsangaben.', 'Liste anderer beantragter Beiträge zur Prüfung der Kumulationsregeln.'],
    faqTitle: 'Häufige Fragen zur Einmalvergütung',
    faqs: [
      { question: 'Ist der Rechnerbetrag meine vollständige Einmalvergütung?', answer: 'Nein. Er zeigt ausschliesslich die indikative variable Komponente des bestehenden Seitenmodells. Der Grundbeitrag ist nicht enthalten und nicht beziffert. Massgebend sind die gültigen Bedingungen und der individuelle Entscheid.' },
      { question: 'Kann ich die angegebenen Sätze als aktuelle Tarife verwenden?', answer: 'Nein. Die Zahlen stammen aus dem bestehenden September-2026-Modell von PvPro.ch. Eine neue Tarifprüfung wurde für diesen Ratgeber nicht vorgenommen. Prüfen Sie die für Ihr Projekt verbindlichen Angaben direkt bei Pronovo.' },
      { question: 'Wie weiss ich, ob KLEIV oder GREIV gilt?', answer: 'Lassen Sie die Anlagenkategorie und das anwendbare Verfahren anhand Ihres konkreten Projekts bei Pronovo bestätigen. Die Zweiteilung der variablen Modellrechnung ist keine KLEIV-/GREIV-Grenze.' },
      { question: 'Meldet der Installateur die Anlage automatisch an?', answer: 'Nur wenn dies vereinbart ist. Halten Sie fest, wer die Registrierung, Nachweise und Antworten auf Rückfragen übernimmt, und verlangen Sie eine Bestätigung der Anmeldung.' },
      { question: 'Wann wird die Förderung ausbezahlt?', answer: 'Das hängt vom anwendbaren Verfahren, der Vollständigkeit der Unterlagen, der Prüfung und dem Entscheid ab. Dieser Ratgeber verspricht weder eine feste Wartezeit noch eine Auszahlung.' },
      { question: 'Sind Speicher und zusätzliche lokale Beiträge enthalten?', answer: 'Nein. Die Beispiele gelten für die PV-Anlage ohne Batteriespeicher und ohne zusätzliche Programme. Lokale Beiträge sowie deren Kombinierbarkeit müssen separat geprüft werden.' },
      { question: 'Was bedeutet Kosten minus variable Komponente?', answer: 'Das ist eine reine Rechendifferenz zwischen den indikativen Bruttokosten und dem Modellbeitrag. Sie ist weder eine verbindliche Nettoofferte noch ein gesicherter Finanzierungsbetrag.' },
    ],
    ctaTitle: 'Offerten mit nachvollziehbarer Förderannahme vergleichen',
    ctaText: 'Fordern Sie getrennte Bruttokosten und Förderannahmen an. Klären Sie mit dem Fachbetrieb, wer das Pronovo-Dossier vorbereitet. PvPro.ch vermittelt Offerten und erteilt keine Förderzusagen.',
  },
  cantonal: {
    title: 'Kantonale Förderung für Solaranlagen abklären',
    shortTitle: 'Kantonale Förderung',
    description: 'Kantonale und kommunale Solarprogramme prüfen: Zuständigkeiten, Fristen vor Bestellung, Unterlagen, Kumulation und steuerliche Abzüge.',
    eyebrow: 'Kanton · Gemeinde · Elektrizitätswerk',
    intro: 'Nicht jeder Standort hat dieselben Programme. Entscheidend sind die Adresse Ihres Projekts, die geplante Massnahme und der richtige Zeitpunkt für den Antrag – nicht eine pauschale Förderzahl für die ganze Schweiz.',
    summaryTitle: 'Vor einem bindenden Auftrag',
    summary: ['Programm am tatsächlichen Anlagenstandort prüfen.', 'Frist, Budget und erforderliche Zusage klären.', 'PV, Speicher und Gebäudemassnahmen einzeln prüfen.'],
    sections: [
      {
        id: 'foerderebenen',
        title: 'Vier Ebenen – vier unterschiedliche Wirkungen',
        intro: 'Ein Bundesbeitrag, ein lokales Programm und ein Steuerabzug sind nicht dasselbe. Führen Sie diese Positionen im Finanzierungsplan getrennt und rechnen Sie ungeklärte Beträge nicht als gesichert ein.',
        cards: [
          { title: 'Bundesförderung', text: 'Die Einmalvergütung wird durch Pronovo verwaltet. Ihr Verfahren gilt unabhängig von der Suche nach lokalen Programmen. Ein lokales Gespräch ersetzt die bundesrechtliche Prüfung nicht.' },
          { title: 'Kantonale Programme', text: 'Die zuständige kantonale Energiefachstelle kann über Programme, förderfähige Massnahmen, Budget und Antragswege informieren. Ein Programm muss nicht direkte PV-Zuschüsse anbieten.' },
          { title: 'Gemeinde und Elektrizitätswerk', text: 'Gemeinde und örtlicher Versorger können eigene Angebote haben. Fragen Sie nach Standort- oder Kundenvoraussetzungen, separaten Fristen und Abgrenzung zu Einspeisevergütungen.' },
          { title: 'Steuerlicher Abzug', text: 'Bei bestehenden Gebäuden können qualifizierende energiesparende Investitionen das steuerbare Einkommen vermindern; Neubauten sind davon zu unterscheiden und fallen nicht unter diesen Abzug. Das ist keine Förderauszahlung oder Erstattung der Investition. Bestätigen Sie die Behandlung mit der Steuerbehörde, auch bezüglich erhaltener Beiträge.' },
        ],
      },
      {
        id: 'massnahmen-und-bedingungen',
        title: 'Was Sie für jede Massnahme einzeln prüfen sollten',
        intro: 'PV, Batteriespeicher, Eigenverbrauchslösungen und Gebäudemassnahmen sind mögliche Gegenstände einer Anfrage – keine automatisch förderfähigen Leistungen.',
        cards: [
          { title: 'Photovoltaik und Standort', text: 'Nennen Sie die genaue Adresse, Gebäudetyp und geplante Leistung. Prüfen Sie, ob das Programm PV ausdrücklich erfasst und wie Neubau, Bestand oder Erweiterung behandelt werden.' },
          { title: 'Speicher und Eigenverbrauch', text: 'Fragen Sie ausdrücklich, ob Speicher, Steuerung oder Eigenverbrauchskonzepte berücksichtigt werden. Aus einer PV-Förderung folgt kein Speicheranspruch. Auch technische Mindestanforderungen müssen bestätigt werden.' },
          { title: 'Gebäude und kombinierte Vorhaben', text: 'Dämmung, Gebäudetechnik oder eine Wärmepumpe können anderen Regeln und Zuständigkeiten unterliegen. Trennen Sie die Kosten und Anträge; eine gemeinsame Offerte bestätigt keine gemeinsame Förderfähigkeit.' },
          { title: 'Budget und Kombination', text: 'Fragen Sie nach offenen Budgets, Förderobergrenzen, anrechenbaren Kosten und Ausschlüssen. Bundes-, Kantons- und Gemeindebeiträge sind nicht automatisch kumulierbar. Andere Anträge offenlegen und die Kombination bestätigen lassen.' },
        ],
      },
      {
        id: 'fristen-vor-bestellung',
        title: 'Fristen vor der verbindlichen Bestellung klären',
        intro: 'Der Auslöser für eine Frist kann je nach Programm Antrag, Auftrag, Baubeginn oder Inbetriebnahme sein. Übertragen Sie deshalb den Pronovo-Ablauf nicht ungeprüft auf eine lokale Förderung.',
        cards: [
          { title: 'Vorher schriftlich fragen', text: 'Lassen Sie sich vor einem bindenden Auftrag sagen, wann der Antrag eingehen muss und ob eine Bewilligung vor Bestellung oder Baustart erforderlich ist. Nachträgliche Anträge können ausgeschlossen sein.' },
          { title: 'Änderungen nicht übergehen', text: 'Eine andere Leistung, ein geänderter Speicher, neue Komponenten oder verschobene Termine können relevant sein. Klären Sie vor der Änderung, ob eine Zustimmung oder neue Unterlagen nötig sind.' },
        ],
      },
    ],
    process: {
      id: 'lokaler-antragsablauf',
      title: 'So wird aus einer Förderfrage ein prüfbares Dossier',
      intro: 'Der konkrete Antrag richtet sich nach dem jeweiligen Programm. Dieser Ablauf hilft, Fragen und Nachweise vor der Auftragserteilung vollständig zu erfassen.',
      cards: [
        { title: 'Standort und Vorhaben festhalten', text: 'Projektadresse, Eigentümer, Gebäudestatus und Massnahmen beschreiben. Die zuständige Stelle am Anlagenstandort zählt, nicht nur der Wohnsitz oder Sitz des Installateurs.' },
        { title: 'Drei lokale Anlaufstellen kontaktieren', text: 'Kantonale Energiefachstelle, Gemeinde und örtlichen Versorger nach passenden Programmen fragen. Bedingungen schriftlich einholen; fehlende lokale Programme nicht durch pauschale Schätzbeträge ersetzen.' },
        { title: 'Frist und Berechtigung bestätigen', text: 'Vor einem bindenden Auftrag Fördergegenstand, Budget, Terminregeln, Kombination und erforderliche Zusage klären. Datum und Antwort der zuständigen Stelle dokumentieren.' },
        { title: 'Separat beantragen und belegen', text: 'Anträge je Programm über dessen vorgesehenen Weg einreichen. Offerte, Pläne und geforderte Nachweise vollständig beilegen. Bestätigungen und Aktenzeichen sichern.' },
        { title: 'Umsetzung und Schlussprüfung', text: 'Nach den bestätigten Bedingungen umsetzen, Änderungen melden und Rechnungen sowie Inbetriebnahmenachweise nachreichen. Erst den Entscheid und Zahlungsbedingungen prüfen; keine feste Auszahlung einplanen.' },
      ],
    },
    checklistTitle: 'Ihre Checkliste für die lokale Förderanfrage',
    checklistIntro: 'Bereiten Sie diese Informationen vor und stellen Sie die offenen Fragen direkt der zuständigen Stelle. Eine Installateurberatung ist hilfreich, ersetzt aber keine Programmbestätigung.',
    checklist: ['Exakte Projektadresse, Gemeinde, örtlicher Versorger und Eigentumsnachweis soweit verlangt.', 'Bestandsgebäude oder Neubau, geplante PV-Leistung und getrennte Angaben zu Speicher und Gebäudetechnik.', 'Aufgeschlüsselte Offerte, technische Datenblätter und Pläne nach Programmanforderung.', 'Geplante Bestellung, Baubeginn und Inbetriebnahme: Welche Frist gilt vor welchem Ereignis?', 'Gibt es ein verfügbares Budget, eine Obergrenze oder eine Zusage vor der Bestellung?', 'Welche Kosten sind anrechenbar und welche technischen Anforderungen gelten?', 'Sind andere Förderbeiträge kombinierbar, und müssen sie im Antrag aufgeführt werden?', 'Wer reicht den Antrag ein, welche Schlussnachweise sind nötig und wie werden Änderungen behandelt?', 'Rechnungen und Beitragsentscheide für die separate steuerliche Prüfung aufbewahren.'],
    faqTitle: 'Häufige Fragen zu lokalen Förderungen',
    faqs: [
      { question: 'Gibt es in jedem Kanton einen zusätzlichen PV-Beitrag?', answer: 'Das wird hier nicht behauptet. Programme können andere Energiemassnahmen betreffen oder für Ihr Projekt nicht offenstehen. Prüfen Sie das Angebot am konkreten Standort bei den zuständigen Stellen.' },
      { question: 'Kann ich erst nach der Installation einen Antrag stellen?', answer: 'Das hängt vom Programm ab. Manche Regeln knüpfen bereits an Auftrag oder Baubeginn an. Prüfen Sie vor einer verbindlichen Bestellung die Antragsfrist und eine eventuell erforderliche vorherige Bewilligung.' },
      { question: 'Kann ich Bundes- und lokale Förderung immer addieren?', answer: 'Nein. Kumulationsregeln, Ausschlüsse und anrechenbare Kosten sind programmspezifisch. Melden Sie andere beantragte oder erhaltene Beiträge und lassen Sie die Kombination bestätigen.' },
      { question: 'Wird ein Batteriespeicher automatisch mitgefördert?', answer: 'Nein. Fragen Sie getrennt nach Speicher, Steuerung und Eigenverbrauchslösung. Es werden hier keine Speicherzuschüsse zugesichert, auch nicht für Zürich.' },
      { question: 'Ist ein Steuerabzug eine Rückzahlung der Anlagekosten?', answer: 'Nein. Ein zulässiger Abzug für qualifizierende Massnahmen an bestehenden Gebäuden reduziert das steuerbare Einkommen, nicht die Rechnung um denselben Betrag. Neubauten sind ausgeschlossen; die konkrete Steuerwirkung und Behandlung von Beiträgen müssen geprüft werden.' },
      { question: 'Sind die verlinkten Kantonsseiten offizielle Fördertabellen?', answer: 'Nein. Sie sind bestehende lokale Solarratgeber von PvPro.ch. Basel wird gemeinsam für Basel-Stadt und Basel-Landschaft geführt. Verbindliche Programminformationen erhalten Sie bei Kanton, Gemeinde oder Versorger.' },
      { question: 'Wer trägt die Verantwortung für den Antrag?', answer: 'Vereinbaren Sie ausdrücklich, welche Arbeiten der Installateur übernimmt. Behalten Sie Zugang zu Bestätigungen und Entscheiden und klären Sie, wer Fristen, Nachweise und Rückfragen bearbeitet.' },
      { question: 'Kann ich die Angaben aus Zürich in einem anderen Kanton nutzen?', answer: 'Nein. Zürcher Angaben ersetzen keine Prüfung am eigenen Standort. Auch im Kanton Zürich müssen das aktuelle Programm, die Massnahme und die Projektbedingungen bestätigt werden.' },
    ],
    ctaTitle: 'Mit einer klaren Projektbeschreibung starten',
    ctaText: 'Vergleichen Sie Solarofferten mit getrennten Kostenpositionen. Fragen Sie die Fachbetriebe nach der Unterstützung bei lokalen Anträgen und bestätigen Sie offene Programme vor einer bindenden Bestellung.',
  },
};
