import type { SubsidyContent } from './types';

export const en: SubsidyContent = {
  home: 'Home',
  breadcrumb: 'Breadcrumb',
  overview: 'All solar support options',
  quote: 'Request free solar quotes',
  contents: 'On this page',
  modelNote: 'These figures use the existing PvPro.ch calculation model labelled September 2026. Its source attribution is not a new check of currently applicable tariffs. All amounts are indicative, not an entitlement or a binding award.',
  official: 'Check authoritative conditions with Pronovo',
  officialNote: 'The conditions, tariffs and decisions applicable to your project take precedence. The official Pronovo website is the reference for federal support.',
  crossFederal: 'Understand the federal one-time payment',
  crossCantonal: 'Check cantonal and municipal support',
  calculatorTitle: 'Estimate the variable component',
  calculatorNote: 'This calculator models only the indicative power-based variable contribution. The additional base contribution is neither quantified nor included. “Subsidy” here means only that variable component; “Net” is simply gross cost minus the model contribution, not a guaranteed net investment.',
  examplesId: 'calculation-examples',
  examplesTitle: 'Four system sizes, a transparent calculation',
  examplesIntro: 'Compare gross costs with the model deduction alone. The base contribution, additional programmes and tax effects are excluded.',
  tableHeaders: ['System capacity', 'Indicative gross cost', 'Indicative variable component', 'Cost minus variable component'],
  tableCaption: 'Indicative model examples without battery storage, not an authoritative grant calculation',
  tableNote: 'The final column is only an arithmetic difference. Plan for the gross cost and confirm approved contributions and payment separately. Your actual quote and award may differ.',
  rateLabels: ['Per kWp for the first 30 kWp', 'Per additional kWp above 30 kWp'],
  rateNote: 'Variable rates from the existing site model, not newly verified current tariffs. This calculation boundary does not define the KLEIV/GREIV programme categories.',
  directoryId: 'canton-directory',
  directoryTitle: 'Local solar guides by canton',
  directoryIntro: 'Every entry in our existing canton directory links to a local PvPro.ch solar guide. These are not verified official subsidy schedules. Also contact the canton, municipality and electricity utility.',
  directoryNote: 'The combined Basel entry covers Basel-Stadt and Basel-Landschaft. This directory reflects existing page coverage, not a claim to provide a separate subsidy schedule for every canton.',
  zurichTitle: 'Existing Canton Zurich solar support guide',
  zurichNote: 'Use this guide for additional local context. Have general statements about Zurich programmes confirmed for your project. They do not establish a storage grant or an entitlement transferable to other cantons.',
  federal: {
    title: 'The federal solar one-time payment in Switzerland',
    shortTitle: 'Federal solar subsidy',
    description: 'Understand Pronovo’s one-time payment: KLEIV and GREIV, indicative examples, required documents and the federal application process.',
    eyebrow: 'Federal support · Pronovo',
    intro: 'What belongs in the one-time payment, what does the calculator actually show, and what should you check before investing? Follow the path from preparation to the decision without treating a payment as assured.',
    summaryTitle: 'Before planning your system',
    summary: ['Pronovo administers the federal one-time payment.', 'Keep the base and variable contributions separate.', 'Confirm project conditions and the approved amount individually.'],
    sections: [
      {
        id: 'understanding-the-payment',
        title: 'What the one-time payment is – and is not',
        intro: 'The one-time payment supports investment in a photovoltaic system. It is a one-off contribution, not ongoing compensation for electricity exported to the grid.',
        cards: [
          { title: 'Federal support, administered by Pronovo', text: 'The contribution is federal and administered by Pronovo. An installer’s quote or a PvPro.ch calculation does not replace the competent body’s decision.' },
          { title: 'Base and power-based contributions', text: 'The existing site model calculates only the capacity-based variable component. The additional base contribution remains unquantified and excluded. An authoritative total award cannot be derived from this calculation.' },
          { title: 'KLEIV: smaller installations', text: 'KLEIV refers to the small one-time payment. Check the category and conditions for your specific project with Pronovo. Residential use alone does not establish eligibility.' },
          { title: 'GREIV: larger installations', text: 'GREIV refers to the large one-time payment. Larger projects need the appropriate procedure and any additional requirements checked. This guide does not set capacity thresholds for the programmes.' },
        ],
      },
      {
        id: 'eligibility-and-financing',
        title: 'Check eligibility and financing separately',
        intro: 'A calculated amount establishes neither project eligibility nor when funds would become available. Confirm the applicable procedure before a binding investment decision.',
        cards: [
          { title: 'A project assessment, not a blanket promise', text: 'System type, capacity, project address, planned commissioning and applicable conditions must be assessed together. Also ask how extensions and modifications are treated.' },
          { title: 'Budget for gross costs', text: 'The contribution is not automatically deducted from the installer’s invoice. Agree funding and payment terms independently of an outstanding subsidy decision.' },
          { title: 'Other support needs separate checks', text: 'Cantonal and municipal programmes have their own applications and deadlines. Check these before a binding order; Pronovo registration does not replace a local application.' },
          { title: 'Record responsibilities', text: 'Agree in writing who registers the installation, supplies evidence, answers questions and reports changes. Keep confirmations and case references even if the installer handles the process.' },
        ],
      },
    ],
    process: {
      id: 'registration-and-payment',
      title: 'From preparation to a possible payment',
      intro: 'The sequence and evidence must match the applicable procedure. These stages describe the process without promising a review or payment deadline.',
      cards: [
        { title: 'Clarify conditions first', text: 'Check the appropriate Pronovo procedure, project eligibility and required evidence. Separately check local deadlines before ordering and allocate responsibilities.' },
        { title: 'Document installation and commissioning', text: 'Have the system professionally installed. Collect technical specifications, required evidence, commissioning information and invoices in a traceable dossier.' },
        { title: 'Register with Pronovo', text: 'Register according to the competent procedure and submit the complete documentation. The installer can handle this if you have agreed that service.' },
        { title: 'Review and follow-up questions', text: 'Pronovo or the competent bodies review the system and dossier. Supply missing evidence and report changes transparently. A calculation alone is not approval.' },
        { title: 'Check the decision and payment', text: 'Review the approved amount, conditions and payment details. Payment depends on the procedure and its processing; this guide guarantees no fixed date.' },
      ],
    },
    checklistTitle: 'Documents to prepare',
    checklistIntro: 'Use this list in discussions with your installer. Pronovo may require additional evidence or a different format depending on the procedure.',
    checklist: ['Installation address, ownership details and applicant contact information.', 'Quote clearly separating system capacity, components and cost items.', 'Technical plans and connection or permission evidence required for the project.', 'Planned and subsequently documented commissioning and capacity data.', 'Invoices, completion evidence and required attestations.', 'Agreement on registration, case reference, follow-up questions and payment details.', 'List of other support applications to check combination rules.'],
    faqTitle: 'Questions about the federal one-time payment',
    faqs: [
      { question: 'Does the calculator show my complete one-time payment?', answer: 'No. It shows only the indicative variable component of the existing site model. The base contribution is not quantified or included. Applicable conditions and the individual decision take precedence.' },
      { question: 'Can I treat the displayed rates as current tariffs?', answer: 'No. They come from the existing PvPro.ch September 2026 model. No new tariff verification was carried out for this guide. Check the authoritative figures for your project directly with Pronovo.' },
      { question: 'How do I know whether KLEIV or GREIV applies?', answer: 'Have Pronovo confirm the system category and procedure for your specific project. The two tiers of the variable calculation are not a KLEIV/GREIV boundary.' },
      { question: 'Will the installer automatically register the system?', answer: 'Only if agreed. Specify who handles registration, supporting evidence and follow-up questions, and request confirmation of the submission.' },
      { question: 'When will the contribution be paid?', answer: 'This depends on the applicable procedure, completeness of documentation, review and decision. This guide promises neither a fixed waiting period nor a payment.' },
      { question: 'Are battery storage and local grants included?', answer: 'No. The examples cover PV without battery storage or additional programmes. Local contributions and their compatibility need separate checks.' },
      { question: 'What does cost minus variable component mean?', answer: 'It is just the arithmetic difference between indicative gross costs and the model contribution. It is not a binding net quote or an assured funding amount.' },
    ],
    ctaTitle: 'Compare quotes with clear subsidy assumptions',
    ctaText: 'Request gross costs separately from subsidy assumptions. Agree who prepares the Pronovo dossier. PvPro.ch introduces homeowners to installers for quotes; it does not award subsidies.',
  },
  cantonal: {
    title: 'Check cantonal solar support in Switzerland',
    shortTitle: 'Cantonal solar subsidies',
    description: 'Check cantonal and municipal solar support: responsible bodies, deadlines before ordering, documents, combination rules and tax deductions.',
    eyebrow: 'Canton · Municipality · Electricity utility',
    intro: 'Not every location has the same programmes. Your project address, proposed measure and application timing matter more than a blanket subsidy figure for the whole country.',
    summaryTitle: 'Before a binding order',
    summary: ['Check the programme at the actual installation address.', 'Clarify deadlines, budget and any prior approval.', 'Check PV, storage and building measures individually.'],
    sections: [
      {
        id: 'support-levels',
        title: 'Four levels, four different effects',
        intro: 'A federal contribution, local programme and tax deduction are not interchangeable. Keep them separate in the financing plan and do not count unconfirmed amounts as secured.',
        cards: [
          { title: 'Federal support', text: 'Pronovo administers the one-time payment. Its procedure is separate from the search for local programmes. A local enquiry does not replace the federal eligibility check.' },
          { title: 'Cantonal programmes', text: 'The cantonal energy office can advise on programmes, eligible measures, budgets and application channels. An energy programme need not offer direct PV subsidies.' },
          { title: 'Municipality and utility', text: 'Your municipality and local electricity supplier may have their own offers. Ask about address or customer requirements, separate deadlines and how support differs from feed-in compensation.' },
          { title: 'Tax deduction', text: 'Qualifying energy-saving investment in existing buildings can reduce taxable income; new builds are not covered by this deduction. It is not a subsidy payment or a refund of the investment. Confirm treatment with the tax authority, including how received contributions affect the deduction.' },
        ],
      },
      {
        id: 'measures-and-conditions',
        title: 'Check each measure on its own merits',
        intro: 'PV, batteries, self-consumption solutions and building measures are possible topics for an enquiry, not automatically eligible items.',
        cards: [
          { title: 'PV and project location', text: 'Give the exact address, building type and planned capacity. Confirm whether PV is expressly covered and how new builds, existing buildings and extensions are treated.' },
          { title: 'Storage and self-consumption', text: 'Explicitly ask whether storage, controls or self-consumption arrangements qualify. PV support does not establish a battery entitlement. Technical minimum requirements also need confirmation.' },
          { title: 'Building and combined works', text: 'Insulation, building systems and heat pumps may have different rules and responsible bodies. Separate costs and applications; a combined quote does not establish joint eligibility.' },
          { title: 'Budget and combination rules', text: 'Ask about available budgets, caps, eligible costs and exclusions. Federal, cantonal and municipal support cannot automatically be combined. Disclose other applications and confirm compatibility.' },
        ],
      },
      {
        id: 'deadlines-before-ordering',
        title: 'Clarify deadlines before a binding order',
        intro: 'Depending on the programme, application, ordering, start of works or commissioning may trigger a timing condition. Do not automatically apply the Pronovo process to local support.',
        cards: [
          { title: 'Get a written answer first', text: 'Before a binding order, ask when the application must arrive and whether approval is required before ordering or starting work. Retrospective applications may be excluded.' },
          { title: 'Do not overlook changes', text: 'Different capacity, storage, components or dates can matter. Before making a change, ask whether consent or new documents are required.' },
        ],
      },
    ],
    process: {
      id: 'local-application-process',
      title: 'Turn a support enquiry into a reviewable dossier',
      intro: 'The actual application follows the rules of each programme. This process helps you collect answers and evidence before commissioning the work.',
      cards: [
        { title: 'Record the location and project', text: 'Describe the project address, owner, building status and measures. The competent body at the installation address matters, not just your residence or the installer’s office.' },
        { title: 'Contact three local bodies', text: 'Ask the cantonal energy office, municipality and local supplier about suitable programmes. Obtain conditions in writing; do not replace an absent programme with a blanket estimate.' },
        { title: 'Confirm deadlines and eligibility', text: 'Before a binding order, clarify coverage, budget, timing rules, combination and required approval. Record the date and the competent body’s reply.' },
        { title: 'Apply separately with evidence', text: 'Use each programme’s prescribed channel. Include the quote, plans and required documents. Retain acknowledgements and case references.' },
        { title: 'Complete works and final checks', text: 'Work within the confirmed conditions, report changes and submit invoices and commissioning evidence. Then review the decision and payment terms; do not presume a fixed payment date.' },
      ],
    },
    checklistTitle: 'Your local support enquiry checklist',
    checklistIntro: 'Prepare these details and put open questions to the responsible body. Installer advice is useful, but not a programme confirmation.',
    checklist: ['Exact address, municipality, local utility and ownership evidence if required.', 'Existing building or new build, PV capacity and separate storage and building-system specifications.', 'Itemised quote, data sheets and plans required by the programme.', 'Planned order, start of works and commissioning: which deadline precedes which event?', 'Available budget, caps and any approval needed before ordering.', 'Eligible costs and applicable technical requirements.', 'Compatibility with other contributions and disclosure requirements.', 'Who submits the application, which final documents are required and how changes are handled.', 'Keep invoices and award decisions for a separate tax assessment.'],
    faqTitle: 'Questions about local support',
    faqs: [
      { question: 'Does every canton offer an extra PV contribution?', answer: 'This guide makes no such claim. Programmes may cover other energy measures or not be open to your project. Check availability at the actual address with the competent bodies.' },
      { question: 'Can I apply after installation?', answer: 'It depends on the programme. Some conditions already attach to the order or start of work. Before a binding order, check the deadline and any required prior approval.' },
      { question: 'Can I always add federal and local contributions?', answer: 'No. Combination rules, exclusions and eligible costs are programme-specific. Declare other requested or received contributions and have compatibility confirmed.' },
      { question: 'Is a battery automatically subsidised?', answer: 'No. Ask separately about storage, controls and self-consumption. This guide promises no storage grant, including in Zurich.' },
      { question: 'Does a tax deduction refund the installation cost?', answer: 'No. An eligible deduction for measures in an existing building reduces taxable income, not the invoice by the same amount. New builds are excluded. Check the actual tax effect and treatment of received contributions.' },
      { question: 'Are the linked canton pages official subsidy schedules?', answer: 'No. They are existing local PvPro.ch solar guides. Basel-Stadt and Basel-Landschaft share one entry. Authoritative programme information comes from the canton, municipality or utility.' },
      { question: 'Who is responsible for the application?', answer: 'Explicitly agree which tasks the installer will perform. Keep access to confirmations and decisions, and establish who follows deadlines, evidence requirements and questions.' },
      { question: 'Can I apply Zurich information to another canton?', answer: 'No. Zurich guidance does not replace checks at your own project address. In Zurich too, the current programme, measure and project conditions must be confirmed.' },
    ],
    ctaTitle: 'Start with a clear project description',
    ctaText: 'Compare solar quotes with separate cost items. Ask installers about support with local applications and confirm open programmes before placing a binding order.',
  },
};
