import type { SubsidyContent } from './types';

export const fr: SubsidyContent = {
  home: 'Accueil',
  breadcrumb: 'Fil d’Ariane',
  overview: 'Toutes les aides solaires',
  quote: 'Demander des offres solaires gratuites',
  contents: 'Sur cette page',
  modelNote: 'Ces indications reprennent le modèle de calcul existant de PvPro.ch, daté de septembre 2026. La mention des sources du modèle ne constitue pas une nouvelle vérification des tarifs en vigueur. Tous les montants sont indicatifs : ils ne confèrent aucun droit à une aide et ne valent pas décision d’octroi.',
  official: 'Vérifier les conditions faisant foi auprès de Pronovo',
  officialNote: 'Les conditions, tarifs et décisions applicables à votre projet font foi. Le site officiel de Pronovo est le point de référence pour l’aide fédérale.',
  crossFederal: 'Comprendre la rétribution unique fédérale',
  crossCantonal: 'Vérifier les aides cantonales et communales',
  calculatorTitle: 'Estimer la composante variable',
  calculatorNote: 'Ce calculateur modélise uniquement la contribution variable indicative liée à la puissance. La contribution de base supplémentaire n’est ni chiffrée ni incluse. « Subvention » désigne ici cette seule composante ; « Net » signifie simplement coût brut moins contribution du modèle, et non investissement net garanti.',
  examplesId: 'exemples-de-calcul',
  examplesTitle: 'Quatre puissances, un calcul explicite',
  examplesIntro: 'Comparez le coût brut à la seule déduction du modèle. La contribution de base, les autres programmes et les effets fiscaux ne sont pas intégrés.',
  tableHeaders: ['Puissance', 'Coût brut indicatif', 'Composante variable indicative', 'Coût moins composante variable'],
  tableCaption: 'Exemples indicatifs sans batterie, ne constituant pas un calcul d’aide faisant foi',
  tableNote: 'La dernière colonne est uniquement une différence arithmétique. Prévoyez le financement du coût brut et vérifiez séparément l’octroi et le paiement. L’offre réelle et la décision peuvent être différents.',
  rateLabels: ['Par kWp pour les premiers 30 kWp', 'Par kWp supplémentaire au-delà de 30 kWp'],
  rateNote: 'Taux variables du modèle existant du site, et non tarifs actuels nouvellement vérifiés. Cette limite de calcul ne définit pas la distinction entre PRU et GRU.',
  directoryId: 'annuaire-des-cantons',
  directoryTitle: 'Guides solaires locaux par canton',
  directoryIntro: 'Tous les liens de notre annuaire existant mènent à des guides solaires locaux de PvPro.ch. Ce ne sont pas des barèmes officiels d’aides vérifiés. Consultez également le canton, la commune et le fournisseur d’électricité.',
  directoryNote: 'L’entrée commune Bâle couvre Bâle-Ville et Bâle-Campagne. L’annuaire reflète les pages existantes et ne prétend pas proposer un barème distinct pour chaque canton.',
  zurichTitle: 'Guide existant des aides solaires dans le canton de Zurich',
  zurichNote: 'Ce guide complète votre recherche locale. Faites confirmer pour votre projet les indications générales sur les programmes zurichois. Elles ne garantissent ni aide au stockage ni droit transposable à un autre canton.',
  federal: {
    title: 'La rétribution unique pour le solaire en Suisse',
    shortTitle: 'Rétribution unique',
    description: 'Comprendre la rétribution unique : Pronovo, PRU et GRU, exemples indicatifs, documents et étapes de l’aide fédérale.',
    eyebrow: 'Aide fédérale · Pronovo',
    intro: 'Que comprend la rétribution unique, que calcule l’outil et quelles vérifications précèdent l’investissement ? Suivez les étapes jusqu’à la décision, sans considérer une aide comme acquise.',
    summaryTitle: 'Avant de préparer votre projet',
    summary: ['Pronovo administre la rétribution unique fédérale.', 'Distinguez contribution de base et composante variable.', 'Faites confirmer les conditions du projet et le montant accordé.'],
    sections: [
      {
        id: 'comprendre-la-retribution',
        title: 'Ce qu’est la rétribution unique – et ce qu’elle n’est pas',
        intro: 'La rétribution unique soutient l’investissement dans une installation photovoltaïque. Il s’agit d’une aide versée une fois, distincte de la rémunération de l’électricité injectée.',
        cards: [
          { title: 'Confédération et Pronovo', text: 'L’aide est fédérale et administrée par Pronovo. Une offre d’installateur ou une estimation de PvPro.ch ne remplace pas la décision de l’organisme compétent.' },
          { title: 'Contribution de base et de puissance', text: 'Le modèle existant du site calcule uniquement la composante variable liée à la puissance. La contribution de base supplémentaire reste non chiffrée et exclue. Ce calcul ne permet donc pas d’établir une rétribution totale faisant foi.' },
          { title: 'PRU : petites installations', text: 'La petite rétribution unique correspond à la KLEIV en allemand. Faites vérifier auprès de Pronovo la catégorie et les conditions du projet. Un usage résidentiel ne suffit pas à confirmer l’admissibilité.' },
          { title: 'GRU : grandes installations', text: 'La grande rétribution unique correspond à la GREIV. Pour un projet plus important, vérifiez la procédure appropriée et les exigences complémentaires éventuelles. Ce guide ne fixe aucun seuil de puissance pour ces catégories.' },
        ],
      },
      {
        id: 'admissibilite-et-financement',
        title: 'Vérifier séparément admissibilité et financement',
        intro: 'Un montant calculé ne confirme ni l’admissibilité du projet ni la date à laquelle des fonds seraient disponibles. Vérifiez la procédure avant une décision d’investissement engageante.',
        cards: [
          { title: 'Le projet, pas une promesse générale', text: 'Type d’installation, puissance, adresse, mise en service prévue et conditions applicables doivent être examinés ensemble. Demandez aussi comment sont traitées les extensions et modifications.' },
          { title: 'Prévoir le coût brut', text: 'L’aide n’est pas automatiquement déduite de la facture de l’installateur. Organisez le financement et les échéances de paiement indépendamment d’une décision encore attendue.' },
          { title: 'Autres aides, autres démarches', text: 'Les programmes cantonaux ou communaux ont leurs propres demandes et délais. Vérifiez-les avant une commande ferme ; l’inscription auprès de Pronovo ne remplace pas une demande locale.' },
          { title: 'Définir les responsabilités', text: 'Convenez par écrit de qui inscrit l’installation, transmet les justificatifs, répond aux demandes et signale les changements. Conservez confirmations et références du dossier, même si l’installateur vous accompagne.' },
        ],
      },
    ],
    process: {
      id: 'inscription-et-versement',
      title: 'De la préparation au versement éventuel',
      intro: 'L’ordre des démarches et les justificatifs doivent correspondre à la procédure applicable. Les étapes suivantes ne promettent aucun délai de traitement ou de paiement.',
      cards: [
        { title: 'Clarifier les conditions', text: 'Vérifiez procédure Pronovo, admissibilité et justificatifs nécessaires. Contrôlez séparément les délais des programmes locaux avant la commande et attribuez les responsabilités.' },
        { title: 'Documenter pose et mise en service', text: 'Faites réaliser l’installation dans les règles de l’art. Rassemblez les caractéristiques techniques, justificatifs, date de mise en service et factures utiles au dossier.' },
        { title: 'Inscrire l’installation chez Pronovo', text: 'Suivez les exigences de la procédure compétente et transmettez un dossier complet. L’installateur peut s’en charger si cette prestation a été convenue.' },
        { title: 'Examen et compléments', text: 'Pronovo ou les services compétents examinent installation et dossier. Fournissez les pièces manquantes et signalez les changements. Une simulation n’est pas une autorisation.' },
        { title: 'Contrôler décision et paiement', text: 'Vérifiez montant accordé, conditions et coordonnées de paiement. Le versement dépend de la procédure et de son traitement ; aucune date fixe n’est garantie ici.' },
      ],
    },
    checklistTitle: 'Documents à préparer',
    checklistIntro: 'Cette liste prépare votre échange avec l’installateur. Pronovo peut demander des pièces supplémentaires ou sous une autre forme selon la procédure.',
    checklist: ['Adresse de l’installation, propriété et coordonnées du demandeur.', 'Offre détaillant puissance, composants et postes de coût séparés.', 'Étude technique et justificatifs de raccordement ou d’autorisation exigés pour le projet.', 'Mise en service prévue, puis documentée, et caractéristiques de puissance.', 'Factures, preuves de réalisation et attestations demandées.', 'Accord sur l’inscription, référence du dossier, suivi des questions et coordonnées de paiement.', 'Liste des autres aides demandées pour vérifier les règles de cumul.'],
    faqTitle: 'Questions sur la rétribution unique',
    faqs: [
      { question: 'Le calculateur donne-t-il ma rétribution unique complète ?', answer: 'Non. Il montre uniquement la composante variable indicative du modèle existant du site. La contribution de base n’est pas chiffrée ni incluse. Les conditions applicables et la décision individuelle font foi.' },
      { question: 'Puis-je considérer ces taux comme les tarifs en vigueur ?', answer: 'Non. Ils proviennent du modèle existant de septembre 2026 de PvPro.ch. Aucune nouvelle vérification tarifaire n’a été effectuée pour ce guide. Consultez Pronovo pour les données faisant foi pour votre projet.' },
      { question: 'Comment savoir si la PRU ou la GRU s’applique ?', answer: 'Faites confirmer la catégorie et la procédure par Pronovo à partir du projet concret. Les deux tranches du calcul variable ne sont pas une limite PRU/GRU.' },
      { question: 'L’installateur inscrit-il automatiquement mon installation ?', answer: 'Seulement si cela est convenu. Précisez qui assure l’inscription, les justificatifs et le suivi des questions, puis demandez une confirmation du dépôt.' },
      { question: 'Quand l’aide est-elle versée ?', answer: 'Cela dépend de la procédure, du dossier complet, de son examen et de la décision. Ce guide ne promet ni attente fixe ni versement.' },
      { question: 'La batterie et les autres aides sont-elles comprises ?', answer: 'Non. Les exemples portent sur le photovoltaïque sans batterie ni programme complémentaire. Les aides locales et leur cumul doivent être vérifiés séparément.' },
      { question: 'Que signifie coût moins composante variable ?', answer: 'Il s’agit d’une différence arithmétique entre coût brut indicatif et contribution du modèle, pas d’une offre nette ferme ni d’un montant de financement assuré.' },
    ],
    ctaTitle: 'Comparer des offres et des hypothèses d’aide explicites',
    ctaText: 'Demandez des coûts bruts séparés des hypothèses de financement. Clarifiez qui prépare le dossier Pronovo. PvPro.ch met en relation pour des offres et ne décide pas de l’octroi des aides.',
  },
  cantonal: {
    title: 'Vérifier les subventions cantonales pour le solaire',
    shortTitle: 'Subventions cantonales',
    description: 'Vérifier les aides solaires cantonales et communales : interlocuteurs, délais avant commande, pièces, cumul et déductions fiscales.',
    eyebrow: 'Canton · Commune · Fournisseur d’électricité',
    intro: 'Les programmes diffèrent selon le lieu. L’adresse du projet, la mesure envisagée et le moment du dépôt comptent davantage qu’un montant prétendument valable dans toute la Suisse.',
    summaryTitle: 'Avant une commande ferme',
    summary: ['Vérifiez le programme à l’adresse de l’installation.', 'Clarifiez délai, budget et accord préalable requis.', 'Examinez séparément PV, batterie et travaux sur le bâtiment.'],
    sections: [
      {
        id: 'niveaux-d-aide',
        title: 'Quatre niveaux, quatre effets distincts',
        intro: 'Aide fédérale, programme local et déduction fiscale ne sont pas interchangeables. Séparez-les dans votre financement et ne comptez pas un montant non confirmé comme acquis.',
        cards: [
          { title: 'Aide fédérale', text: 'Pronovo administre la rétribution unique. Sa procédure est distincte de la recherche des programmes locaux. Une discussion locale ne remplace pas la vérification fédérale.' },
          { title: 'Programmes cantonaux', text: 'Le service cantonal de l’énergie peut renseigner sur les programmes, mesures admissibles, budgets et demandes. Un programme énergétique ne propose pas nécessairement un soutien direct au photovoltaïque.' },
          { title: 'Commune et fournisseur', text: 'La commune et le fournisseur local peuvent proposer leurs propres offres. Vérifiez les exigences liées à l’adresse ou au contrat client, les délais séparés et la distinction avec la rémunération de l’injection.' },
          { title: 'Déduction fiscale', text: 'Dans un bâtiment existant, des investissements énergétiques admissibles peuvent réduire le revenu imposable ; les constructions neuves ne relèvent pas de cette déduction. Il ne s’agit ni d’une subvention versée ni d’un remboursement de l’investissement. Confirmez le traitement auprès du fisc, y compris celui des aides reçues.' },
        ],
      },
      {
        id: 'mesures-et-conditions',
        title: 'Examiner chaque mesure séparément',
        intro: 'PV, stockage, autoconsommation et travaux sur le bâtiment sont des sujets possibles pour votre demande, pas des prestations automatiquement couvertes.',
        cards: [
          { title: 'Photovoltaïque et adresse', text: 'Indiquez l’adresse exacte, le type de bâtiment et la puissance prévue. Vérifiez que le PV est expressément couvert et comment sont traités construction neuve, bâtiment existant et extension.' },
          { title: 'Stockage et autoconsommation', text: 'Demandez explicitement si batterie, pilotage ou dispositifs d’autoconsommation sont admissibles. Une aide au PV ne crée aucun droit pour la batterie. Faites confirmer les exigences techniques.' },
          { title: 'Bâtiment et travaux combinés', text: 'Isolation, équipements du bâtiment ou pompe à chaleur peuvent relever d’autres règles et services. Séparez coûts et demandes : une offre commune ne prouve pas une admissibilité commune.' },
          { title: 'Budget et cumul', text: 'Demandez les budgets disponibles, plafonds, coûts admissibles et exclusions. Les aides fédérales, cantonales et communales ne sont pas automatiquement cumulables. Déclarez les autres demandes et faites confirmer la combinaison.' },
        ],
      },
      {
        id: 'delais-avant-commande',
        title: 'Clarifier les délais avant de commander',
        intro: 'Selon le programme, le dépôt, la commande, le début des travaux ou la mise en service peuvent déclencher une condition de délai. Ne transposez pas automatiquement la procédure Pronovo.',
        cards: [
          { title: 'Demander une réponse écrite avant de s’engager', text: 'Avant toute commande ferme, demandez quand le dossier doit être reçu et si l’octroi doit précéder la commande ou le chantier. Un dépôt après les travaux peut être exclu.' },
          { title: 'Faire valider les changements', text: 'Une puissance différente, un nouveau stockage, des composants modifiés ou un report peuvent avoir un effet. Vérifiez avant le changement si un accord ou de nouvelles pièces sont nécessaires.' },
        ],
      },
    ],
    process: {
      id: 'demarche-locale',
      title: 'Transformer une question en dossier vérifiable',
      intro: 'Chaque demande suit les règles du programme concerné. Cette démarche vous aide à recueillir les réponses et pièces avant de vous engager.',
      cards: [
        { title: 'Décrire adresse et projet', text: 'Précisez adresse, propriétaire, statut du bâtiment et mesures. Le service compétent au lieu de l’installation compte, pas seulement le domicile ou l’adresse de l’installateur.' },
        { title: 'Contacter les trois interlocuteurs locaux', text: 'Demandez au service cantonal de l’énergie, à la commune et au fournisseur local quels programmes existent. Obtenez les conditions par écrit ; ne remplacez pas un programme absent par une estimation forfaitaire.' },
        { title: 'Confirmer délais et admissibilité', text: 'Avant une commande ferme, vérifiez mesure couverte, budget, dates, cumul et accord requis. Conservez la date et la réponse du service compétent.' },
        { title: 'Déposer séparément les demandes', text: 'Utilisez la voie prévue par chaque programme. Joignez offre, plans et justificatifs demandés. Conservez accusés de réception et références.' },
        { title: 'Réaliser et faire contrôler', text: 'Respectez les conditions confirmées, signalez les modifications et fournissez factures et preuve de mise en service. Examinez ensuite décision et modalités de paiement sans présumer une date de versement.' },
      ],
    },
    checklistTitle: 'Votre liste pour une demande locale',
    checklistIntro: 'Préparez ces informations et adressez les questions ouvertes au service compétent. Le conseil d’un installateur ne remplace pas la confirmation du programme.',
    checklist: ['Adresse exacte, commune, fournisseur local et preuve de propriété si requise.', 'Bâtiment existant ou neuf, puissance PV et détails distincts du stockage et des équipements.', 'Offre ventilée, fiches techniques et plans exigés par le programme.', 'Commande, début des travaux et mise en service prévus : quelle démarche doit précéder quel événement ?', 'Budget disponible, plafond et éventuel accord avant commande.', 'Coûts admissibles et exigences techniques applicables.', 'Possibilité de cumul et obligation de déclarer les autres contributions.', 'Responsable du dépôt, justificatifs finaux et traitement des changements.', 'Factures et décisions d’octroi à conserver pour l’examen fiscal séparé.'],
    faqTitle: 'Questions sur les aides locales',
    faqs: [
      { question: 'Chaque canton verse-t-il une aide PV supplémentaire ?', answer: 'Ce guide ne l’affirme pas. Un programme peut couvrir d’autres mesures ou ne pas être ouvert à votre projet. Vérifiez l’offre à l’adresse exacte auprès des services compétents.' },
      { question: 'Puis-je déposer la demande après l’installation ?', answer: 'Cela dépend du programme. Certaines règles se rattachent déjà à la commande ou au début du chantier. Vérifiez avant une commande ferme le délai et l’éventuelle autorisation préalable.' },
      { question: 'Puis-je toujours additionner aides fédérales et locales ?', answer: 'Non. Cumul, exclusions et coûts admissibles dépendent du programme. Déclarez les autres contributions demandées ou reçues et faites confirmer leur combinaison.' },
      { question: 'La batterie est-elle automatiquement subventionnée ?', answer: 'Non. Interrogez séparément le service sur stockage, pilotage et autoconsommation. Aucun soutien au stockage n’est garanti ici, y compris à Zurich.' },
      { question: 'La déduction fiscale rembourse-t-elle les travaux ?', answer: 'Non. Une déduction admissible pour un bâtiment existant réduit le revenu imposable, pas la facture du même montant. Les constructions neuves sont exclues. Vérifiez l’effet fiscal concret et le traitement des contributions reçues.' },
      { question: 'Les pages cantonales liées sont-elles des barèmes officiels ?', answer: 'Non. Il s’agit de guides solaires locaux existants de PvPro.ch. Bâle-Ville et Bâle-Campagne partagent une entrée. Les conditions faisant foi sont fournies par le canton, la commune ou le fournisseur.' },
      { question: 'Qui est responsable de la demande ?', answer: 'Convenez explicitement des tâches confiées à l’installateur. Conservez l’accès aux confirmations et décisions et définissez le suivi des délais, pièces et questions.' },
      { question: 'Puis-je appliquer les indications zurichoises ailleurs ?', answer: 'Non. Elles ne remplacent pas une vérification sur votre lieu de projet. À Zurich aussi, programme en vigueur, mesure et conditions doivent être confirmés.' },
    ],
    ctaTitle: 'Commencer avec un projet bien décrit',
    ctaText: 'Comparez des offres avec des coûts séparés. Demandez aux installateurs quel accompagnement ils proposent pour les dossiers locaux et faites confirmer les programmes ouverts avant une commande ferme.',
  },
};
