import type { SubsidyContent } from './types';

export const it: SubsidyContent = {
  home: 'Home',
  breadcrumb: 'Percorso di navigazione',
  overview: 'Tutti gli incentivi solari',
  quote: 'Richiedi preventivi solari gratuiti',
  contents: 'In questa pagina',
  modelNote: 'Questi dati riprendono il modello di calcolo esistente di PvPro.ch, riferito a settembre 2026. Le fonti citate dal modello non costituiscono una nuova verifica delle tariffe in vigore. Tutti gli importi sono indicativi: non conferiscono un diritto e non rappresentano una decisione vincolante di concessione.',
  official: 'Verifica le condizioni ufficiali presso Pronovo',
  officialNote: 'Fanno fede le condizioni, le tariffe e le decisioni applicabili al tuo progetto. Il sito ufficiale di Pronovo è il riferimento per il sostegno federale.',
  crossFederal: 'Comprendere la remunerazione unica federale',
  crossCantonal: 'Verificare incentivi cantonali e comunali',
  calculatorTitle: 'Stimare la componente variabile',
  calculatorNote: 'Questo calcolatore modella soltanto il contributo variabile indicativo legato alla potenza. Il contributo di base aggiuntivo non è quantificato né incluso. « Incentivo » indica qui solo questa componente; « Netto » è semplicemente costo lordo meno contributo del modello, non un investimento netto garantito.',
  examplesId: 'esempi-di-calcolo',
  examplesTitle: 'Quattro potenze, un calcolo trasparente',
  examplesIntro: 'Confronta i costi lordi con la sola deduzione del modello. Il contributo di base, gli altri programmi e gli effetti fiscali sono esclusi.',
  tableHeaders: ['Potenza impianto', 'Costo lordo indicativo', 'Componente variabile indicativa', 'Costo meno componente variabile'],
  tableCaption: 'Esempi indicativi senza accumulo, non un calcolo vincolante del contributo',
  tableNote: 'L’ultima colonna è solo una differenza aritmetica. Prevedi il finanziamento del costo lordo e verifica separatamente contributi approvati e versamento. Il preventivo effettivo e la decisione possono differire.',
  rateLabels: ['Per kWp per i primi 30 kWp', 'Per ogni kWp aggiuntivo oltre 30 kWp'],
  rateNote: 'Tariffe variabili del modello esistente del sito, non tariffe attuali nuovamente verificate. Questo limite di calcolo non definisce la distinzione tra PRU e GRU.',
  directoryId: 'elenco-dei-cantoni',
  directoryTitle: 'Guide solari locali per cantone',
  directoryIntro: 'Tutte le voci del nostro elenco esistente portano a guide solari locali di PvPro.ch. Non sono tariffari ufficiali degli incentivi verificati. Consulta anche cantone, comune e azienda elettrica.',
  directoryNote: 'La voce unica Basilea copre Basilea Città e Basilea Campagna. L’elenco riflette le pagine esistenti e non pretende di offrire un tariffario distinto per ogni cantone.',
  zurichTitle: 'Guida esistente agli incentivi nel Cantone di Zurigo',
  zurichNote: 'Questa guida aggiunge informazioni locali. Fai confermare per il tuo progetto le indicazioni generali sui programmi zurighesi. Non garantiscono un contributo all’accumulo né un diritto trasferibile ad altri cantoni.',
  federal: {
    title: 'La remunerazione unica per il solare in Svizzera',
    shortTitle: 'Remunerazione unica',
    description: 'Comprendere la remunerazione unica: Pronovo, PRU e GRU, esempi indicativi, documenti e procedura del sostegno federale.',
    eyebrow: 'Sostegno federale · Pronovo',
    intro: 'Che cosa comprende la remunerazione unica, che cosa calcola lo strumento e quali verifiche precedono l’investimento? Segui il percorso fino alla decisione senza considerare il versamento già acquisito.',
    summaryTitle: 'Prima di pianificare l’impianto',
    summary: ['Pronovo amministra la remunerazione unica federale.', 'Distingui contributo di base e componente variabile.', 'Fai confermare condizioni del progetto e importo approvato.'],
    sections: [
      {
        id: 'comprendere-la-remunerazione',
        title: 'Che cos’è la remunerazione unica – e che cosa non è',
        intro: 'La remunerazione unica sostiene l’investimento in un impianto fotovoltaico. È un contributo una tantum, distinto dal compenso per l’energia immessa in rete.',
        cards: [
          { title: 'Confederazione e Pronovo', text: 'Il sostegno è federale ed è amministrato da Pronovo. Un preventivo dell’installatore o una stima di PvPro.ch non sostituiscono la decisione dell’organismo competente.' },
          { title: 'Contributo di base e di potenza', text: 'Il modello esistente calcola soltanto la componente variabile legata alla potenza. Il contributo di base aggiuntivo resta non quantificato ed escluso. Non è quindi possibile ricavare un importo totale vincolante da questo calcolo.' },
          { title: 'PRU: piccoli impianti', text: 'La piccola remunerazione unica corrisponde alla KLEIV in tedesco. Verifica con Pronovo categoria e condizioni del progetto concreto. L’uso residenziale da solo non conferma l’ammissibilità.' },
          { title: 'GRU: grandi impianti', text: 'La grande remunerazione unica corrisponde alla GREIV. Per impianti più grandi occorre verificare procedura appropriata ed eventuali requisiti aggiuntivi. Questa guida non stabilisce soglie di potenza per i programmi.' },
        ],
      },
      {
        id: 'ammissibilita-e-finanziamento',
        title: 'Verificare separatamente ammissibilità e finanziamento',
        intro: 'Un importo calcolato non conferma né l’ammissibilità né quando sarebbero disponibili i fondi. Chiarisci la procedura prima di una decisione d’investimento vincolante.',
        cards: [
          { title: 'Il progetto, non una promessa generale', text: 'Tipo d’impianto, potenza, indirizzo, messa in servizio prevista e condizioni applicabili vanno esaminati insieme. Chiedi anche come vengono trattati ampliamenti e modifiche.' },
          { title: 'Prevedere i costi lordi', text: 'Il contributo non viene automaticamente sottratto dalla fattura dell’installatore. Concorda finanziamento e scadenze indipendentemente da una decisione sugli incentivi ancora aperta.' },
          { title: 'Altri contributi, altre verifiche', text: 'Programmi cantonali e comunali hanno domande e scadenze proprie. Verificali prima di un ordine vincolante: la registrazione presso Pronovo non sostituisce una domanda locale.' },
          { title: 'Definire le responsabilità', text: 'Concorda per iscritto chi registra l’impianto, invia i documenti, risponde alle richieste e segnala i cambiamenti. Conserva conferme e riferimenti della pratica anche se l’installatore ti assiste.' },
        ],
      },
    ],
    process: {
      id: 'registrazione-e-versamento',
      title: 'Dalla preparazione all’eventuale versamento',
      intro: 'Ordine delle operazioni e documentazione devono corrispondere alla procedura applicabile. Queste fasi non promettono tempi fissi di esame o di pagamento.',
      cards: [
        { title: 'Chiarire prima le condizioni', text: 'Verifica procedura Pronovo, ammissibilità e documenti necessari. Controlla separatamente le scadenze locali prima dell’ordine e assegna le responsabilità.' },
        { title: 'Documentare installazione e messa in servizio', text: 'Fai realizzare l’impianto a regola d’arte. Raccogli dati tecnici, prove richieste, informazioni sulla messa in servizio e fatture in una pratica tracciabile.' },
        { title: 'Registrare presso Pronovo', text: 'Segui i requisiti della procedura competente e trasmetti tutti i documenti. Può occuparsene l’installatore se questa prestazione è stata concordata.' },
        { title: 'Esame e richieste di integrazione', text: 'Pronovo o gli organismi competenti verificano impianto e pratica. Integra i documenti mancanti e comunica le modifiche. Una simulazione non è un’approvazione.' },
        { title: 'Controllare decisione e pagamento', text: 'Verifica importo approvato, condizioni e dati di pagamento. Il versamento dipende dalla procedura e dal suo esame; qui non viene garantita alcuna data fissa.' },
      ],
    },
    checklistTitle: 'Documenti da preparare',
    checklistIntro: 'Usa questa lista nel colloquio con l’installatore. Pronovo può richiedere ulteriori documenti o formati diversi secondo la procedura.',
    checklist: ['Indirizzo dell’impianto, proprietà e contatti del richiedente.', 'Preventivo con potenza, componenti e voci di costo separate.', 'Progetto tecnico e prove di allacciamento o autorizzazione richieste.', 'Messa in servizio prevista e poi documentata, con dati sulla potenza.', 'Fatture, prove di realizzazione e attestazioni richieste.', 'Accordo sulla registrazione, riferimento della pratica, richieste di integrazione e dati di pagamento.', 'Elenco degli altri contributi richiesti per verificare le regole di cumulo.'],
    faqTitle: 'Domande sulla remunerazione unica',
    faqs: [
      { question: 'Il calcolatore mostra la remunerazione unica completa?', answer: 'No. Mostra solo la componente variabile indicativa del modello esistente del sito. Il contributo di base non è quantificato né incluso. Fanno fede condizioni applicabili e decisione individuale.' },
      { question: 'Posso considerare questi importi come tariffe attuali?', answer: 'No. Provengono dal modello esistente di settembre 2026 di PvPro.ch. Per questa guida non è stata effettuata una nuova verifica tariffaria. Consulta Pronovo per i dati vincolanti del progetto.' },
      { question: 'Come sapere se si applica PRU o GRU?', answer: 'Fai confermare da Pronovo categoria e procedura per il progetto concreto. Le due fasce del calcolo variabile non sono una soglia PRU/GRU.' },
      { question: 'L’installatore registra automaticamente l’impianto?', answer: 'Solo se concordato. Definisci chi gestisce registrazione, documenti e richieste di integrazione e chiedi una conferma dell’invio.' },
      { question: 'Quando viene versato il contributo?', answer: 'Dipende da procedura, completezza dei documenti, esame e decisione. Questa guida non promette né un’attesa fissa né il versamento.' },
      { question: 'Sono inclusi accumulo e altri incentivi locali?', answer: 'No. Gli esempi riguardano il fotovoltaico senza accumulo e senza programmi aggiuntivi. I contributi locali e la loro cumulabilità vanno verificati separatamente.' },
      { question: 'Che cosa significa costo meno componente variabile?', answer: 'È solo la differenza aritmetica tra costi lordi indicativi e contributo del modello, non un preventivo netto vincolante né un finanziamento assicurato.' },
    ],
    ctaTitle: 'Confrontare preventivi con ipotesi di incentivo chiare',
    ctaText: 'Richiedi costi lordi separati dalle ipotesi sui contributi. Concorda chi prepara la pratica Pronovo. PvPro.ch mette in contatto per i preventivi e non decide la concessione degli incentivi.',
  },
  cantonal: {
    title: 'Verificare gli incentivi cantonali per il solare',
    shortTitle: 'Incentivi cantonali',
    description: 'Verificare incentivi solari cantonali e comunali: referenti, scadenze prima dell’ordine, documenti, cumulo e deduzioni fiscali.',
    eyebrow: 'Cantone · Comune · Azienda elettrica',
    intro: 'I programmi cambiano secondo il luogo. Contano l’indirizzo del progetto, la misura prevista e il momento della domanda, non un importo generico valido per tutta la Svizzera.',
    summaryTitle: 'Prima di un ordine vincolante',
    summary: ['Verifica il programma all’indirizzo dell’impianto.', 'Chiarisci scadenza, budget e approvazione preventiva.', 'Esamina separatamente FV, accumulo e lavori sull’edificio.'],
    sections: [
      {
        id: 'livelli-di-sostegno',
        title: 'Quattro livelli, quattro effetti diversi',
        intro: 'Contributo federale, programma locale e deduzione fiscale non sono intercambiabili. Separali nel piano finanziario e non considerare assicurati importi non confermati.',
        cards: [
          { title: 'Sostegno federale', text: 'Pronovo amministra la remunerazione unica. La procedura è distinta dalla ricerca di programmi locali. Un colloquio locale non sostituisce la verifica federale.' },
          { title: 'Programmi cantonali', text: 'Il servizio cantonale dell’energia può informare su programmi, misure ammissibili, budget e modalità di domanda. Un programma energetico non offre necessariamente un incentivo diretto al fotovoltaico.' },
          { title: 'Comune e azienda elettrica', text: 'Comune e fornitore locale possono avere offerte proprie. Chiedi requisiti legati all’indirizzo o al contratto cliente, scadenze separate e differenze rispetto alla remunerazione dell’immissione.' },
          { title: 'Deduzione fiscale', text: 'Per edifici esistenti, investimenti energetici ammissibili possono ridurre il reddito imponibile; le nuove costruzioni non rientrano in questa deduzione. Non è un versamento di incentivo né un rimborso dell’investimento. Conferma il trattamento con l’autorità fiscale, anche per i contributi ricevuti.' },
        ],
      },
      {
        id: 'misure-e-condizioni',
        title: 'Verificare ogni misura separatamente',
        intro: 'FV, batterie, autoconsumo e lavori sull’edificio sono possibili temi della domanda, non prestazioni automaticamente coperte.',
        cards: [
          { title: 'Fotovoltaico e luogo del progetto', text: 'Indica indirizzo esatto, tipo d’edificio e potenza prevista. Verifica che il FV sia espressamente incluso e come vengono trattati nuovo edificio, edificio esistente e ampliamento.' },
          { title: 'Accumulo e autoconsumo', text: 'Chiedi esplicitamente se batteria, gestione o soluzioni di autoconsumo sono ammissibili. Un incentivo al FV non crea un diritto per l’accumulo. Fai confermare anche i requisiti tecnici.' },
          { title: 'Edificio e lavori combinati', text: 'Isolamento, impianti dell’edificio o pompa di calore possono seguire regole e referenti diversi. Separa costi e domande: un preventivo comune non conferma un’ammissibilità comune.' },
          { title: 'Budget e cumulo', text: 'Chiedi budget disponibili, massimali, costi ammissibili ed esclusioni. Contributi federali, cantonali e comunali non sono automaticamente cumulabili. Dichiara le altre domande e fai confermare la combinazione.' },
        ],
      },
      {
        id: 'scadenze-prima-dell-ordine',
        title: 'Chiarire le scadenze prima di ordinare',
        intro: 'Secondo il programma, domanda, ordine, inizio lavori o messa in servizio possono attivare una condizione temporale. Non trasferire automaticamente la procedura Pronovo al sostegno locale.',
        cards: [
          { title: 'Chiedere prima una risposta scritta', text: 'Prima di un ordine vincolante, verifica quando deve arrivare la domanda e se serve un’approvazione prima dell’ordine o del cantiere. Le domande successive ai lavori possono essere escluse.' },
          { title: 'Fare approvare i cambiamenti', text: 'Potenza diversa, nuovo accumulo, componenti cambiati o date spostate possono avere effetti. Prima della modifica, chiedi se occorrono consenso o nuovi documenti.' },
        ],
      },
    ],
    process: {
      id: 'procedura-locale',
      title: 'Trasformare una domanda in una pratica verificabile',
      intro: 'La domanda concreta segue le regole del rispettivo programma. Questo percorso aiuta a raccogliere risposte e documenti prima di affidare i lavori.',
      cards: [
        { title: 'Descrivere luogo e progetto', text: 'Specifica indirizzo, proprietario, stato dell’edificio e misure. Conta l’organismo competente dove si trova l’impianto, non solo il domicilio o la sede dell’installatore.' },
        { title: 'Contattare tre referenti locali', text: 'Chiedi al servizio cantonale dell’energia, al comune e al fornitore locale quali programmi sono pertinenti. Ottieni le condizioni per iscritto; non sostituire un programma assente con una stima generica.' },
        { title: 'Confermare scadenze e ammissibilità', text: 'Prima di un ordine vincolante, chiarisci misure coperte, budget, date, cumulo e approvazione richiesta. Conserva data e risposta dell’organismo competente.' },
        { title: 'Presentare domande separate e complete', text: 'Usa il canale previsto da ciascun programma. Allega preventivo, piani e prove richieste. Conserva ricevute e riferimenti della pratica.' },
        { title: 'Realizzare e completare la verifica', text: 'Rispetta le condizioni confermate, segnala modifiche e trasmetti fatture e prova della messa in servizio. Controlla poi decisione e modalità di pagamento senza presumere una data fissa.' },
      ],
    },
    checklistTitle: 'La lista per la richiesta di incentivi locali',
    checklistIntro: 'Prepara queste informazioni e poni le domande aperte all’organismo competente. Il consiglio dell’installatore è utile, ma non conferma il programma.',
    checklist: ['Indirizzo esatto, comune, fornitore locale e prova di proprietà se richiesta.', 'Edificio esistente o nuovo, potenza FV e dati separati su accumulo e impianti dell’edificio.', 'Preventivo suddiviso, schede tecniche e piani richiesti dal programma.', 'Ordine, inizio lavori e messa in servizio previsti: quale scadenza precede quale evento?', 'Budget disponibile, massimale ed eventuale approvazione prima dell’ordine.', 'Costi ammissibili e requisiti tecnici applicabili.', 'Cumulabilità e obbligo di dichiarare gli altri contributi.', 'Responsabile dell’invio, documenti finali e gestione delle modifiche.', 'Fatture e decisioni da conservare per la verifica fiscale separata.'],
    faqTitle: 'Domande sugli incentivi locali',
    faqs: [
      { question: 'Ogni cantone versa un contributo FV aggiuntivo?', answer: 'Questa guida non lo afferma. I programmi possono coprire altre misure o non essere aperti al progetto. Verifica l’offerta all’indirizzo esatto presso gli organismi competenti.' },
      { question: 'Posso presentare la domanda dopo l’installazione?', answer: 'Dipende dal programma. Alcune condizioni riguardano già ordine o inizio lavori. Prima di un ordine vincolante, verifica scadenza ed eventuale approvazione preventiva.' },
      { question: 'Posso sempre sommare contributi federali e locali?', answer: 'No. Cumulo, esclusioni e costi ammissibili dipendono dal programma. Dichiara gli altri contributi richiesti o ricevuti e fai confermare la combinazione.' },
      { question: 'La batteria è automaticamente incentivata?', answer: 'No. Chiedi separatamente per accumulo, gestione e autoconsumo. Non viene garantito alcun contributo all’accumulo, neppure a Zurigo.' },
      { question: 'La deduzione fiscale rimborsa il costo dei lavori?', answer: 'No. Una deduzione ammissibile per un edificio esistente riduce il reddito imponibile, non la fattura dello stesso importo. Le nuove costruzioni sono escluse. Verifica effetto fiscale concreto e trattamento dei contributi ricevuti.' },
      { question: 'Le pagine cantonali collegate sono tariffari ufficiali?', answer: 'No. Sono guide solari locali esistenti di PvPro.ch. Basilea Città e Basilea Campagna hanno una voce comune. Le informazioni vincolanti provengono da cantone, comune o fornitore.' },
      { question: 'Chi è responsabile della domanda?', answer: 'Concorda esplicitamente i compiti dell’installatore. Mantieni accesso a conferme e decisioni e definisci chi segue scadenze, documenti e richieste di integrazione.' },
      { question: 'Posso usare le indicazioni di Zurigo in un altro cantone?', answer: 'No. Non sostituiscono le verifiche nel luogo del tuo progetto. Anche a Zurigo vanno confermati programma attuale, misura e condizioni.' },
    ],
    ctaTitle: 'Iniziare con un progetto descritto chiaramente',
    ctaText: 'Confronta preventivi solari con voci di costo separate. Chiedi alle imprese quale assistenza offrono per le pratiche locali e conferma i programmi aperti prima di un ordine vincolante.',
  },
};
