import type { FactsLocale } from '@/lib/facts';

export type SubsidyLocale = FactsLocale;
export type GuideKind = 'federal' | 'cantonal';
export type TextCard = { title: string; text: string };
export type GuideSection = {
  id: string;
  title: string;
  intro: string;
  cards: TextCard[];
};
export type GuideContent = {
  title: string;
  shortTitle: string;
  description: string;
  eyebrow: string;
  intro: string;
  summaryTitle: string;
  summary: string[];
  sections: GuideSection[];
  process: GuideSection;
  checklistTitle: string;
  checklistIntro: string;
  checklist: string[];
  faqTitle: string;
  faqs: { question: string; answer: string }[];
  ctaTitle: string;
  ctaText: string;
};
export type SubsidyContent = {
  home: string;
  breadcrumb: string;
  overview: string;
  quote: string;
  contents: string;
  modelNote: string;
  official: string;
  officialNote: string;
  crossFederal: string;
  crossCantonal: string;
  calculatorTitle: string;
  calculatorNote: string;
  examplesId: string;
  examplesTitle: string;
  examplesIntro: string;
  tableHeaders: [string, string, string, string];
  tableCaption: string;
  tableNote: string;
  rateLabels: [string, string];
  rateNote: string;
  directoryId: string;
  directoryTitle: string;
  directoryIntro: string;
  directoryNote: string;
  zurichTitle: string;
  zurichNote: string;
  federal: GuideContent;
  cantonal: GuideContent;
};
