export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  image: string;
  author: string;
  date: string;
  readMin: number;
  tag: string;
  href?: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'balkonkraftwerk-schweiz',
    title: 'Balkonkraftwerk Schweiz: erlaubt, Kosten und lohnt es sich wirklich?',
    excerpt: 'Sind Balkonkraftwerke in der Schweiz erlaubt? Kosten, Regeln und ob sich ein Balkonkraftwerk lohnt – mit ehrlichem Vergleich zur vollwertigen Solaranlage.',
    image: '/images/balkonkraftwerk-schweiz.png',
    author: 'PVPro Redaktion',
    date: '17. März 2026',
    readMin: 7,
    tag: 'Ratgeber',
  },
  {
    slug: 'solaranlage-winter-schweiz',
    title: 'Solaranlage im Winter: Wie effizient sind Panels bei Schnee und Kälte?',
    excerpt: 'Viele Hausbesitzer fragen sich, ob sich eine Solaranlage in der Schweiz auch im Winter lohnt. Die Antwort überrascht: Moderne PV-Anlagen produzieren auch bei Schnee und Kälte zuverlässig Strom.',
    image: '/images/blog-1.png',
    author: 'PVPro Redaktion',
    date: '12. März 2026',
    readMin: 5,
    tag: 'Ratgeber',
  },
  {
    slug: 'foerderungen-photovoltaik-2026',
    title: 'Photovoltaik-Förderungen in der Schweiz 2026: Alles was Sie wissen müssen',
    excerpt: 'Die Schweiz bietet attraktive Förderungen für Solaranlagen. Von der Einmalvergütung (EIV) bis zu kantonalen Programmen — hier finden Sie alle aktuellen Subventionen auf einen Blick.',
    image: '/images/blog-2.png',
    author: 'PVPro Redaktion',
    date: '5. März 2026',
    readMin: 7,
    tag: 'Förderungen',
  },
  {
    slug: 'batteriespeicher-solaranlage-lohnt-sich',
    title: 'Batteriespeicher für Ihre Solaranlage: Lohnt sich die Investition?',
    excerpt: 'Ein Batteriespeicher erhöht den Eigenverbrauch Ihrer Solaranlage erheblich. Wir analysieren Kosten, Amortisationszeit und wann sich ein Speicher für Schweizer Haushalte wirklich rentiert.',
    image: '/images/blog-3.png',
    author: 'PVPro Redaktion',
    date: '27. Februar 2026',
    readMin: 6,
    tag: 'Speicher',
  },
  {
    slug: 'richtigen-solarinstallateur-schweiz-waehlen',
    title: 'Den richtigen Solarinstallateur in der Schweiz wählen: 7 wichtige Kriterien',
    excerpt: 'Die Wahl des Installateurs ist entscheidend für Qualität und Wirtschaftlichkeit Ihrer Solaranlage. Mit diesen 7 Kriterien finden Sie den besten Anbieter in Ihrer Region.',
    image: '/images/blog-4.png',
    author: 'PVPro Redaktion',
    date: '18. Februar 2026',
    readMin: 4,
    tag: 'Ratgeber',
  },
  {
    slug: 'eigenverbrauch-optimieren-solar',
    title: 'Eigenverbrauch maximieren: So nutzen Sie Ihre Solarenergie optimal',
    excerpt: 'Mit cleveren Strategien können Sie bis zu 80% Ihrer Solarenergie selbst verbrauchen. Von der Verbrauchsplanung bis zur Wärmepumpe — diese Tipps helfen Ihnen, das Maximum herauszuholen.',
    image: '/images/blog-5.png',
    author: 'PVPro Redaktion',
    date: '10. Februar 2026',
    readMin: 5,
    tag: 'Tipps',
  },
  {
    slug: 'roi-photovoltaik-schweiz',
    title: 'ROI einer Solaranlage in der Schweiz: Wann amortisiert sich die Investition?',
    excerpt: 'Wie lange dauert es, bis sich eine Solaranlage in der Schweiz rechnet? Wir rechnen durch, welche Faktoren die Amortisationszeit beeinflussen und wann Sie mit Gewinnen rechnen können.',
    image: '/images/blog-6.png',
    author: 'PVPro Redaktion',
    date: '2. Februar 2026',
    readMin: 8,
    tag: 'Finanzen',
  },
  {
    slug: 'vergleichsportal-photovoltaik-schweiz',
    title: 'Photovoltaik Anbieter vergleichen Schweiz: So finden Sie den besten Installateur',
    excerpt: 'Mit dem richtigen Vergleich sparen Schweizer Hausbesitzer Tausende von Franken. Wie Sie Photovoltaik-Anbieter systematisch vergleichen und den optimalen Installateur finden.',
    image: '/images/asset-installateur-tablet.png',
    author: 'PVPro Redaktion',
    date: '28. Januar 2026',
    readMin: 6,
    tag: 'Ratgeber',
    href: '/vergleichsportal-photovoltaik-schweiz',
  },
  {
    slug: 'solaranlage-installieren-schweiz',
    title: 'Solaranlage installieren in der Schweiz: Schritt für Schritt zum eigenen PV-System',
    excerpt: 'Von der Planung bis zur Inbetriebnahme: Alles, was Sie über die Installation einer Solaranlage in der Schweiz wissen müssen – Ablauf, Kosten und worauf Sie achten sollten.',
    image: '/images/asset-installateur-dach-1.png',
    author: 'PVPro Redaktion',
    date: '22. Januar 2026',
    readMin: 7,
    tag: 'Ratgeber',
    href: '/solaranlage-installieren-schweiz',
  },
  {
    slug: 'solaranlage-offerte-einholen',
    title: 'Solaranlage Offerte einholen: So vergleichen Sie Angebote richtig',
    excerpt: 'Mehrere Offerten einzuholen ist der wichtigste Schritt vor dem Kauf einer Solaranlage. Wir zeigen, worauf Sie beim Vergleich achten sollten und wie Sie das beste Angebot erkennen.',
    image: '/images/asset-beratung-indoor-1.png',
    author: 'PVPro Redaktion',
    date: '16. Januar 2026',
    readMin: 5,
    tag: 'Ratgeber',
    href: '/solaranlage-offerte-einholen',
  },
  {
    slug: 'foerderungen-kanton-zuerich',
    title: 'Förderung Kanton Zürich: Solaranlage Subventionen und Förderprogramme 2026',
    excerpt: 'Der Kanton Zürich bietet attraktive Förderungen für Solaranlagen. Einmalvergütung, kantonale Programme und Gemeindesubventionen – alle Fördermöglichkeiten auf einen Blick.',
    image: '/images/blog-2.png',
    author: 'PVPro Redaktion',
    date: '10. Januar 2026',
    readMin: 6,
    tag: 'Förderungen',
    href: '/foerderungen-kanton-zuerich',
  },
  {
    slug: 'photovoltaik-schweizer-klima',
    title: 'Photovoltaik im Schweizer Klima: Ertrag in Alpen, Mittelland und Tessin',
    excerpt: 'Wie beeinflusst das Schweizer Klima den Solarertrag? Von Zürich bis Lugano – regionale Unterschiede, saisonale Produktion und warum sich PV überall in der Schweiz lohnt.',
    image: '/images/asset-haus-alpen-1.png',
    author: 'PVPro Redaktion',
    date: '5. Januar 2026',
    readMin: 8,
    tag: 'Ratgeber',
    href: '/photovoltaik-schweizer-klima',
  },
  {
    slug: 'photovoltaik-installation-schweiz',
    title: 'Photovoltaik Installation Schweiz: Ablauf, Dauer und was Sie erwarten können',
    excerpt: 'Wie läuft eine Photovoltaik-Installation in der Schweiz ab? Von der Erstberatung bis zur Netzanmeldung: Der komplette Prozess in 7 Schritten mit Zeitplan und Kosten.',
    image: '/images/asset-installateur-montage-1.png',
    author: 'PVPro Redaktion',
    date: '30. Dezember 2025',
    readMin: 7,
    tag: 'Ratgeber',
    href: '/photovoltaik-installation-schweiz',
  },
  {
    slug: 'photovoltaik-komplettloesung-schweiz',
    title: 'Photovoltaik Komplettlösung Schweiz: Alles aus einer Hand inkl. Speicher',
    excerpt: 'Eine Photovoltaik-Komplettlösung umfasst Solaranlage, Batteriespeicher, Wallbox und Smart-Home-Integration. Was kostet das Rundum-Paket und für wen lohnt es sich?',
    image: '/images/asset-haus-solar-ev-1.png',
    author: 'PVPro Redaktion',
    date: '22. Dezember 2025',
    readMin: 9,
    tag: 'Ratgeber',
    href: '/photovoltaik-komplettloesung-schweiz',
  },
  {
    slug: 'photovoltaik-wartung-kosten',
    title: 'Photovoltaik Wartung und Kosten: Was kostet der Unterhalt einer Solaranlage?',
    excerpt: 'Solaranlagen gelten als wartungsarm – aber ganz ohne Pflege geht es nicht. Wir erklären, welche Wartungsarbeiten nötig sind, was sie kosten und wie Sie die Lebensdauer maximieren.',
    image: '/images/asset-installateur-inspektion.png',
    author: 'PVPro Redaktion',
    date: '15. Dezember 2025',
    readMin: 6,
    tag: 'Tipps',
    href: '/photovoltaik-wartung-kosten',
  },
  {
    slug: 'solaranlagen-typen-vergleich',
    title: 'Solaranlagen Typen Vergleich: Monokristallin, Polykristallin oder Dünnschicht?',
    excerpt: 'Welcher Solaranlagentyp ist der richtige für Ihr Dach? Wir vergleichen monokristalline, polykristalline und Dünnschichtmodule – Wirkungsgrad, Kosten und Empfehlung für die Schweiz.',
    image: '/images/asset-panel-closeup-1.png',
    author: 'PVPro Redaktion',
    date: '8. Dezember 2025',
    readMin: 7,
    tag: 'Ratgeber',
    href: '/solaranlagen-typen-vergleich',
  },
];
