// Auto-generated by scripts/compute-image-focus.js (sharp attention/saliency analysis)
// Maps blog image paths to their smart focal point for CSS object-position.

export const imageFocus: Record<string, string> = {
  '/images/solaranlage-chalet-bewoelkt.webp': '25% 53%',
  '/images/solarmodul-regentropfen-alpen.webp': '75% 22%',
  '/images/solaranlage-chalet-alpen-sommer.webp': '25% 66%',
  '/images/solaranlage-bauernhaus-alpen.webp': '66% 69%',
  '/images/aurora-energy-batteriespeicher.webp': '25% 28%',
  '/images/installateur-solarmodul-dach-alpen.webp': '69% 83%',
  '/images/solaranlage-waermepumpe-chalet-winter.webp': '75% 69%',
  '/images/steuererklaerung-solaranlage-schweiz.webp': '63% 63%',
  '/images/bauernhaus-solaranlage-abend-eiger.webp': '25% 72%',
  '/images/balkonkraftwerk-schweiz.webp': '75% 34%',
  '/images/solarmodule-nass-alpen-eiger.webp': '75% 47%',
  '/images/solarinstallateure-vergleich-beratung.webp': '66% 53%',
  '/images/swissvolt-batteriespeicher-keller.webp': '59% 59%',
  '/images/solarinstallateure-offerte-beratung.webp': '25% 81%',
  '/images/solar-energieertrag-tablet-chalet.webp': '75% 47%',
  '/images/solar-monitoring-tablet-haus.webp': '31% 53%',
  '/images/asset-installateur-tablet.webp': '41% 22%',
  '/images/asset-installateur-dach-1.webp': '41% 22%',
  '/images/asset-beratung-indoor-1.webp': '75% 28%',
  '/images/solardaecher-quartier-see-schweiz.webp': '56% 72%',
  '/images/asset-haus-alpen-1.webp': '75% 82%',
  '/images/asset-installateur-montage-1.webp': '25% 82%',
  '/images/asset-haus-solar-ev-1.webp': '75% 63%',
  '/images/asset-installateur-inspektion.webp': '25% 19%',
  '/images/asset-panel-closeup-1.webp': '25% 66%',
};

export function getImageFocus(src: string): string {
  return imageFocus[src] ?? '50% 50%';
}
