export const roofCopy = {
  de: {
    title: 'Dachanalyse', analyze: 'Dach analysieren', loading: 'Dachdaten werden geladen…',
    mapLoading: 'Satellitenkarte wird geladen…', mapUnavailable: 'Die Satellitenkarte ist derzeit nicht verfügbar. Sie können die Dachflächen unten auswählen.',
    unavailable: 'Die Dachdaten sind derzeit nicht verfügbar. Sie können trotzdem fortfahren.',
    notFound: 'Für diese Adresse wurden keine Dachflächen gefunden. Sie können trotzdem fortfahren.',
    ambiguous: 'Die Zuordnung des Dachs ist nicht eindeutig. Prüfen Sie die Karte und wählen Sie Ihr Gebäude aus.',
    ambiguousNoMap: 'Ohne Satellitenkarte können wir das Gebäude nicht sicher zuordnen. Sie können ohne Dachanalyse fortfahren.',
    chooseBuilding: 'Gebäude auswählen', building: 'Gebäude', roof: 'Dachfläche',
    roofs: 'Dachflächen auswählen', area: 'Dachfläche', yield: 'Jahresertrag', orientation: 'Ausrichtung',
    suitability: 'Eignung', flat: 'Flachdach', multiple: 'Mehrere', mixed: 'Gemischt',
    north: 'N', northEast: 'NO', east: 'O', southEast: 'SO', south: 'S', southWest: 'SW', west: 'W', northWest: 'NW',
    classes: ['Gering', 'Mittel', 'Gut', 'Sehr gut', 'Hervorragend'],
    disclaimer: 'Richtwerte basierend auf Daten des Bundesamts für Energie (BFE) und geo.admin.ch.',
  },
  fr: {
    title: 'Analyse du toit', analyze: 'Analyser le toit', loading: 'Chargement des données du toit…',
    mapLoading: 'Chargement de la carte satellite…', mapUnavailable: 'La carte satellite est indisponible. Vous pouvez sélectionner les pans de toit ci-dessous.',
    unavailable: 'Les données du toit sont indisponibles pour le moment. Vous pouvez tout de même continuer.',
    notFound: 'Aucun pan de toit trouvé pour cette adresse. Vous pouvez tout de même continuer.',
    ambiguous: 'L’attribution du toit est incertaine. Vérifiez la carte et choisissez votre bâtiment.',
    ambiguousNoMap: 'Sans carte satellite, le bâtiment ne peut pas être identifié avec certitude. Vous pouvez continuer sans analyse du toit.',
    chooseBuilding: 'Choisir un bâtiment', building: 'Bâtiment', roof: 'Pan de toit',
    roofs: 'Sélectionner les pans de toit', area: 'Surface du toit', yield: 'Production annuelle', orientation: 'Orientation',
    suitability: 'Aptitude', flat: 'Toit plat', multiple: 'Plusieurs', mixed: 'Mixte',
    north: 'N', northEast: 'NE', east: 'E', southEast: 'SE', south: 'S', southWest: 'SO', west: 'O', northWest: 'NO',
    classes: ['Faible', 'Moyenne', 'Bonne', 'Très bonne', 'Excellente'],
    disclaimer: 'Valeurs indicatives basées sur les données de l’Office fédéral de l’énergie (OFEN) et de geo.admin.ch.',
  },
  it: {
    title: 'Analisi del tetto', analyze: 'Analizza il tetto', loading: 'Caricamento dei dati del tetto…',
    mapLoading: 'Caricamento della mappa satellitare…', mapUnavailable: 'La mappa satellitare non è disponibile. Puoi selezionare le falde qui sotto.',
    unavailable: 'I dati del tetto non sono attualmente disponibili. Puoi comunque continuare.',
    notFound: 'Nessuna falda trovata per questo indirizzo. Puoi comunque continuare.',
    ambiguous: 'L’attribuzione del tetto è incerta. Controlla la mappa e seleziona il tuo edificio.',
    ambiguousNoMap: 'Senza la mappa satellitare non possiamo identificare l’edificio con certezza. Puoi continuare senza l’analisi del tetto.',
    chooseBuilding: 'Seleziona un edificio', building: 'Edificio', roof: 'Falda',
    roofs: 'Seleziona le falde', area: 'Superficie del tetto', yield: 'Produzione annua', orientation: 'Orientamento',
    suitability: 'Idoneità', flat: 'Tetto piano', multiple: 'Multipli', mixed: 'Mista',
    north: 'N', northEast: 'NE', east: 'E', southEast: 'SE', south: 'S', southWest: 'SO', west: 'O', northWest: 'NO',
    classes: ['Bassa', 'Moderata', 'Buona', 'Molto buona', 'Eccellente'],
    disclaimer: 'Valori indicativi basati sui dati dell’Ufficio federale dell’energia (UFE) e di geo.admin.ch.',
  },
  en: {
    title: 'Roof analysis', analyze: 'Analyze roof', loading: 'Loading roof data…',
    mapLoading: 'Loading satellite map…', mapUnavailable: 'The satellite map is unavailable. You can select roof faces below.',
    unavailable: 'Roof data is currently unavailable. You can still continue.',
    notFound: 'No roof faces were found for this address. You can still continue.',
    ambiguous: 'The roof-to-building match is uncertain. Check the map and choose your building.',
    ambiguousNoMap: 'Without the satellite map, we cannot confidently identify the building. You can continue without roof analysis.',
    chooseBuilding: 'Choose a building', building: 'Building', roof: 'Roof face',
    roofs: 'Select roof faces', area: 'Roof area', yield: 'Annual output', orientation: 'Orientation',
    suitability: 'Suitability', flat: 'Flat roof', multiple: 'Multiple', mixed: 'Mixed',
    north: 'N', northEast: 'NE', east: 'E', southEast: 'SE', south: 'S', southWest: 'SW', west: 'W', northWest: 'NW',
    classes: ['Low', 'Moderate', 'Good', 'Very good', 'Excellent'],
    disclaimer: 'Indicative values based on data from the Swiss Federal Office of Energy (SFOE) and geo.admin.ch.',
  },
} as const;