import type { CantonGuide } from '../types';

export const guide: CantonGuide = {
  id: 'basel', path: '/fr/solaire-bale', canton: 'Bâle-Ville / Bâle-Campagne',
  title: 'Solaire à Bâle en 2026 : Ville ou Campagne | PvPro.ch',
  description: 'Photovoltaïque à Bâle : subventions, permis et obligation solaire diffèrent nettement entre Bâle-Ville et Bâle-Campagne.',
  h1: 'Installation solaire à Bâle : Bâle-Ville ou Bâle-Campagne ?',
  intro: ['Les subventions et règles applicables dépendent du côté de la limite cantonale où se trouve votre bien immobilier.'],
  quickFacts: [
    { value: 'jusqu’à CHF 100/m²', label: 'Toit : rénovation avec photovoltaïque', sourceIds: ['bs-solarkraftwerk'] },
    { value: 'jusqu’à CHF 140/m²', label: 'Façade : rénovation avec photovoltaïque', sourceIds: ['bs-solarkraftwerk'] },
    { value: 'CHF 40/m²', label: 'Toit : bonus photovoltaïque uniquement avec isolation thermique', sourceIds: ['bl-energie'] },
    { value: 'CHF 120/m²', label: 'Façade : bonus photovoltaïque uniquement avec isolation thermique', sourceIds: ['bl-energie'] },
  ],
  sections: [
    { id: 'vergleich', title: 'Bâle-Ville et Bâle-Campagne : cinq différences', paragraphs: [
      'L’emplacement détermine d’abord la règle applicable. Bâle-Ville et Bâle-Campagne ont des subventions et procédures différentes.',
      'Les montants ne sont pas une rétribution forfaitaire pour chaque installation photovoltaïque. À Bâle-Ville, ils relèvent de « Solarkraftwerk Basel » ; à Bâle-Campagne, d’une demande pour l’isolation thermique. Examinez séparément l’aide fédérale de Pronovo, la rétribution unique (RU).',
    ], sourceIds: ['bs-solarkraftwerk', 'bl-energie'], module: { kind: 'comparison', title: 'La limite cantonale est déterminante', intro: 'Même technique, mais règles différentes selon le canton :', columns: ['Bâle-Ville', 'Bâle-Campagne'], items: [], rows: [
      { label: 'Subvention photovoltaïque', left: 'Examiner séparément l’aide fédérale. Le supplément cantonal vaut uniquement pour une rénovation énergétique avec photovoltaïque.', right: 'Examiner séparément l’aide fédérale. Le bonus cantonal vaut uniquement avec une isolation thermique admissible.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
      { label: 'Rénovation + photovoltaïque', left: 'Toit : CHF 50/m², CHF 100/m² sur la surface des modules avec photovoltaïque. Façade : CHF 70/m², CHF 140/m² avec photovoltaïque.', right: 'Bonus photovoltaïque : CHF 40/m² pour le toit ou CHF 120/m² pour la façade. Uniquement avec isolation thermique.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
      { label: 'Permis', left: 'Une annonce peut suffire pour une installation bien intégrée. Les zones protégées et monuments peuvent exiger un permis.', right: 'Dans les zones à bâtir et agricoles, annonce en général au moins 30 jours avant les travaux. Les zones protégées exigent un permis.', sourceIds: ['bs-permit', 'bl-permit'] },
      { label: 'Obligation solaire', left: 'L’offensive solaire n’est qu’un projet. Une obligation photovoltaïque et une transition de 15 ans pour les bâtiments existants sont prévues.', right: 'L’initiative énergétique « Utiliser le potentiel » a été rejetée le 8 mars 2026 par 67,6 % de non. Il n’y a donc pas de nouvelle obligation générale d’équipement ultérieur.', sourceIds: ['bs-offensive', 'bl-abstimmung'] },
      { label: 'Particularité 2026', left: 'L’action soutient uniquement les grandes installations en toiture. Il faut couvrir 90 % de la surface bien ou très bien adaptée, ou du potentiel techniquement réalisable.', right: 'De nouvelles demandes sont possibles depuis le 12 janvier 2026. Maximum de CHF 100’000 par demande et de 50 % des coûts admis par mesure.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    ] } },
    { id: 'pflichten', title: 'Obligation solaire : qu’en est-il aujourd’hui ?', paragraphs: [
      'Non. L’offensive solaire de Bâle-Ville n’est pas encore du droit en vigueur et Bâle-Campagne n’a pas de nouvelle obligation générale d’équipement ultérieur.',
      'À Bâle-Ville, le gouvernement cantonal a transmis une proposition révisée au parlement cantonal. Une obligation pour les surfaces bien adaptées et une transition de 15 ans pour les bâtiments existants sont prévues.',
      'Tant que le projet n’est pas adopté et entré en vigueur, il n’impose aucune installation. Le projet estime le potentiel des toits et façades à environ 40 % de la consommation cantonale actuelle d’électricité.',
      'Ce chiffre n’est ni une promesse de rendement ni un taux de subvention. À Bâle-Campagne, l’initiative législative « Utiliser le potentiel – assurer l’approvisionnement » (initiative solaire) a été rejetée le 8 mars 2026 par 67,6 % de non.',
    ], bullets: ['Bâle-Ville : offensive solaire prévue, transition de 15 ans envisagée — pas encore du droit en vigueur.', 'Bâle-Campagne : 67,6 % de non à l’initiative énergétique — aucune nouvelle obligation générale d’équipement ultérieur.', 'Pour votre projet, l’emplacement et la procédure en vigueur comptent aujourd’hui, pas une annonce politique.'], sourceIds: ['bs-offensive', 'bl-abstimmung', 'bs-permit', 'bl-permit'], notice: { title: 'Prévu — pas encore du droit en vigueur', text: 'Les règles actuelles s’appliquent jusqu’à ce qu’une décision déploie ses effets juridiques. Vérifiez l’aptitude, la zone et le statut de protection du bâtiment, puis déposez la procédure adaptée.', status: 'future' } },
    { id: 'foerderung', title: 'Quelles subventions s’appliquent en 2026 ?', paragraphs: [
      'La limite cantonale détermine la subvention. Bâle-Ville paie uniquement pour une rénovation énergétique avec photovoltaïque ; Bâle-Campagne uniquement pour une isolation thermique qui remplit les conditions.',
      'À Bâle-Ville, « Solarkraftwerk Basel » prévoit en 2026 CHF 50 par m² de toit, ou CHF 100 sur la surface des modules photovoltaïques. Pour la façade, les montants sont respectivement de CHF 70 et CHF 140.',
      'Le doublement vaut pour la surface des modules photovoltaïques, pas automatiquement pour toute l’enveloppe du bâtiment. Une installation en toiture doit en principe couvrir 90 % de la surface adaptée.',
      'Il s’agit de la surface indiquée comme bien ou très bien adaptée dans la carte d’aptitude (cadastre solaire), ou du potentiel techniquement réalisable.',
      'La demande doit être déposée sur le portail avant le début des travaux. Une installation photovoltaïque seule sur un toit qui n’est pas rénové ne reçoit pas ces contributions.',
      'Dès 2026, Bâle-Campagne verse en plus CHF 40 par m² de modules sur le toit ou CHF 120 en façade. Le bonus s’intègre à la demande d’isolation et ne vaut pas pour une installation photovoltaïque planifiée seule.',
      'Le maximum est de CHF 100’000 par demande et de 50 % des coûts admis par mesure. De nouvelles demandes sont possibles depuis le 12 janvier 2026.',
      'Examinez séparément l’aide fédérale de Pronovo, la rétribution unique (RU). Elle ne remplace ni la demande cantonale de rénovation, ni une annonce, ni un permis.',
      'Avant l’offre, déterminez si vous prévoyez uniquement le photovoltaïque, le photovoltaïque avec isolation ou une rénovation globale.',
    ], bullets: ['Bâle-Ville : CHF 50/100 par m² de toit et CHF 70/140 par m² de façade — uniquement rénovation avec photovoltaïque.', 'Bâle-Ville : 90 % de la surface de toiture adaptée ou techniquement réalisable ; demande avant les travaux.', 'Bâle-Campagne : CHF 40/120 par m² de modules — uniquement avec isolation thermique.', 'Bâle-Campagne : au maximum CHF 100’000 par demande et 50 % des coûts admis par mesure.'], sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { id: 'bewilligung', title: 'Ai-je besoin d’un permis ou une annonce suffit-elle ?', paragraphs: [
      'Le canton, la zone et le statut de protection déterminent si une annonce suffit ou si un permis est nécessaire. Subventions et prescriptions de construction sont distinctes.',
      'À Bâle-Ville, une annonce peut suffire dans certaines zones pour une installation bien intégrée. Un permis peut être nécessaire dans les zones spécialement protégées et pour les monuments.',
      'Pour les façades visibles et bâtiments historiques, consultez tôt l’autorité compétente. À Bâle-Campagne, les installations photovoltaïques en toiture sont en principe dispensées de permis dans les zones à bâtir et agricoles.',
      'Elles doivent toutefois être annoncées au moins 30 jours avant le début. Un permis peut être nécessaire dans les zones centrales, de protection des sites et monuments, pour les monuments culturels et naturels importants, ainsi qu’hors de la zone à bâtir.',
      'Une demande de subvention ne remplace ni une annonce ni un permis. À Bâle-Ville, la demande doit précéder les travaux ; dans le paquet énergétique de Bâle-Campagne, le bonus photovoltaïque figure dans la demande d’isolation.',
    ], bullets: ['Noter l’adresse et le canton. Vérifier ensuite la zone, la protection du bâtiment et la solution en toiture ou façade.', 'Déposer l’annonce ou la demande de permis avant le début et prévoir les délais de l’autorité compétente.', 'Examiner séparément la demande de subvention, notamment son dépôt avant les travaux.'], sourceIds: ['bs-permit', 'bl-permit', 'bs-solarkraftwerk', 'bl-energie'] },
    { id: 'kosten', title: 'Combien coûte une installation solaire ici ?', paragraphs: ['Le canton ne publie aucun prix photovoltaïque fixe. La toiture, la taille de l’installation et l’équipement souhaité sont les principaux facteurs.', 'La comparaison la plus utile ne porte donc pas sur un prix forfaitaire en ligne, mais sur plusieurs offres pour le même projet.'], bullets: ['Surface et forme du toit, surface utile des modules, structure porteuse et état de la couverture', 'Puissance de l’installation et modules choisis', 'Échafaudage, accès et logistique du chantier', 'Travaux électriques, compteur et raccordement au réseau', 'Batterie de stockage et autres composants supplémentaires', 'Consommation propre et profil de charge attendu', 'Onduleur', 'Installateur, étendue des prestations, garanties et suivi'], sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { id: 'fuer-wen', title: 'À qui une installation solaire convient-elle particulièrement ici ?', paragraphs: [
      'Une installation solaire convient particulièrement si vous planifiez ensemble rénovation et photovoltaïque. À Bâle-Ville, cela concerne « Solarkraftwerk Basel » ; à Bâle-Campagne, l’isolation thermique avec photovoltaïque.',
      'À Bâle-Ville, il faut pouvoir atteindre l’exigence de 90 %. Sans rénovation, n’intégrez pas l’action cantonale au calcul, mais examinez séparément l’aide fédérale et la consommation propre.',
      'À Bâle-Campagne, le bonus convient aux propriétaires qui planifient ensemble isolation thermique et photovoltaïque. Pour les immeubles loués, collectifs ou les petites toitures, il faut aussi clarifier la propriété, les compteurs, la statique et la répartition de la consommation électrique.',
    ], sourceIds: ['bs-solarkraftwerk', 'bl-energie'], module: { kind: 'jurisdiction-steps', title: 'Quelle règle bâloise s’applique à mon cas ?', intro: 'Vérifiez d’abord de quel côté de la limite cantonale se trouve votre bien :', columns: ['Bien à Bâle-Ville', 'Bien à Bâle-Campagne'], items: [
      { title: 'Bien à Bâle-Ville', text: '1. Vérifier l’emplacement et le cadastre solaire. 2. Planifier une rénovation de toiture ou façade avec photovoltaïque et vérifier si 90 % sont atteignables. 3. Clarifier protection et procédure ; déposer la demande avant les travaux.', detail: 'Seule la rénovation avec photovoltaïque relève de « Solarkraftwerk Basel ». Une installation photovoltaïque seule ne devient pas pour autant un projet de rénovation.', sourceIds: ['bs-solarkraftwerk', 'bs-permit'] },
      { title: 'Bien à Bâle-Campagne', text: '1. Planifier ensemble isolation thermique et photovoltaïque. 2. Vérifier la demande d’isolation, le bonus pour les modules, CHF 100’000 et 50 %. 3. Annoncer au moins 30 jours avant les travaux ou déposer une demande de permis en cas de protection.', detail: 'Le bonus photovoltaïque est lié à une isolation thermique admissible. Ce n’est pas une subvention autonome pour une installation photovoltaïque ordinaire.', sourceIds: ['bl-energie', 'bl-permit'] },
    ] } },
  ],
  faqs: [
    { question: 'Existe-t-il une subvention cantonale pour le photovoltaïque à Bâle ?', answer: 'Oui, mais il n’existe pas de bonus bâlois uniforme. À Bâle-Ville, « Solarkraftwerk Basel » est lié à une rénovation énergétique avec photovoltaïque. À Bâle-Campagne, le bonus photovoltaïque ne vaut qu’avec isolation thermique ; examinez séparément la rétribution unique fédérale (RU) de Pronovo.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { question: 'Quelle est la différence entre Bâle-Ville et Bâle-Campagne ?', answer: 'Les cantons ont des règles différentes. Bâle-Ville soutient la rénovation avec photovoltaïque à raison de CHF 50/100 par m² de toit et CHF 70/140 par m² de façade ; les installations en toiture suivent en principe la règle des 90 %. Bâle-Campagne complète l’isolation thermique de CHF 40/120 par m² de modules et applique ses propres règles aux demandes et constructions.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { question: 'L’offensive solaire de Bâle-Ville est-elle déjà une loi ?', answer: 'Non. C’est un projet visant davantage de photovoltaïque et une obligation pour les surfaces adaptées. Une transition de 15 ans est prévue pour les bâtiments existants. Jusqu’à l’entrée en vigueur, cette obligation n’est pas du droit applicable.', sourceIds: ['bs-offensive'] },
    { question: 'Comment fonctionne « Solarkraftwerk Basel » ?', answer: 'Vous combinez une rénovation énergétique du toit ou de la façade avec du photovoltaïque sur la surface rénovée. Déposez la demande avant les travaux. Les montants sont de CHF 50/100 en toiture et CHF 70/140 par m² en façade ; la règle des 90 % doit être respectée pour le toit.', sourceIds: ['bs-solarkraftwerk'] },
    { question: 'Quel est le montant du bonus photovoltaïque à Bâle-Campagne en 2026 ?', answer: 'Le bonus est de CHF 40 par m² de modules sur le toit et CHF 120 en façade. Il s’intègre à la demande d’isolation, pas à une installation photovoltaïque planifiée seule. Maximum de CHF 100’000 par demande et de 50 % des coûts admis par mesure.', sourceIds: ['bl-energie'] },
    { question: 'Bâle-Campagne impose-t-il le solaire à toutes les maisons existantes ?', answer: 'Non. L’initiative législative « Utiliser le potentiel – assurer l’approvisionnement » a été rejetée le 8 mars 2026 par 67,6 % de non. Elle n’a créé aucune nouvelle obligation générale d’équipement. La zone, la protection du bâtiment et l’installation déterminent toujours l’annonce ou le permis.', sourceIds: ['bl-abstimmung', 'bl-permit'] },
    { question: 'Quand ai-je besoin d’un permis à Bâle-Ville ?', answer: 'Cela dépend de l’installation et de l’emplacement. Une annonce peut suffire pour une installation bien intégrée. Un permis peut être nécessaire dans les zones protégées, pour les monuments et pour les solutions sensibles en toiture ou façade ; l’autorité compétente devrait classer le cas avant l’offre.', sourceIds: ['bs-permit', 'bs-offensive'] },
  ],
  sources: [
    { id: 'bs-solarkraftwerk', authority: 'Canton de Bâle-Ville', title: 'Action Solarkraftwerk Basel : contributions d’encouragement', url: 'https://www.bs.ch/wsu/aue/abteilung-energie/aktion-solarkraftwerk-basel' },
    { id: 'bs-permit', authority: 'Canton de Bâle-Ville', title: 'Ai-je besoin d’un permis de construire ?', url: 'https://www.bs.ch/themen/umwelt-und-bauen/bauen-im-kanton-basel-stadt/brauche-ich-eine-baubewilligung' },
    { id: 'bs-offensive', authority: 'Grand Conseil de Bâle-Ville', title: 'Rapport du Conseil d’État sur l’offensive solaire (25.06.2025, affaire 25.0921.01)', url: 'https://grosserrat.bs.ch/dokumente/100410/000000410351.pdf' },
    { id: 'bl-energie', authority: 'Canton de Bâle-Campagne', title: 'Nouvelles incitations du programme cantonal 2026', url: 'https://www.baselland.ch/politik-und-behorden/direktionen/bau-und-umweltschutzdirektion/umweltschutz-energie/medienmitteilungen/neue-anreize-im-kantonalen-foerderprogramm' },
    { id: 'bl-permit', authority: 'Canton de Bâle-Campagne', title: 'Installations solaires / pompes à chaleur : annonce et permis', url: 'https://www.baselland.ch/politik-und-behorden/direktionen/bau-und-umweltschutzdirektion/bauinspektorat/solaranlagen-waermepumpen' },
    { id: 'bl-abstimmung', authority: 'Canton de Bâle-Campagne', title: 'Résultat du vote : « Utiliser le potentiel – assurer l’approvisionnement » (8 mars 2026)', url: 'https://abstimmungen.bl.ch/app/archive/de/vote/ct-13-160.html' },
  ],
};