import type { CantonGuide } from '../types';

const sources = [
  { id: 'fr-solar-permit', authority: 'Canton de Fribourg / État de Fribourg', title: 'Installations solaires – permis de construire', url: 'https://www.fr.ch/territoire-amenagement-et-constructions/permis-de-construire-et-autorisations/permis-de-construire/permis-de-construire-installations-solaires' },
  { id: 'fr-energy-law', authority: 'Canton de Fribourg', title: 'Règlement sur l’énergie (RSF 770.11), art. 25', url: 'https://bdlf.fr.ch/app/de/texts_of_law/770.11' },
  { id: 'fr-energy-subsidies', authority: 'Canton de Fribourg / État de Fribourg', title: 'Programme de subventions en matière d’énergie', url: 'https://www.fr.ch/deef/sde/programmes-de-subventions-en-matiere-denergie' },
  { id: 'fr-pronovo-faq', authority: 'Pronovo AG sur mandat de la Confédération', title: 'Questions fréquentes sur la rétribution unique (RU) et l’encouragement solaire en Suisse', url: 'https://pronovo.ch/de/foerderung/photovoltaik/haeufige-fragen/' },
] as const;

export const guide: CantonGuide = {
  id: 'freiburg', path: '/fr/solaire-fribourg', canton: 'Fribourg',
  title: 'Solaire à Fribourg : obligation et permis 2026 | PvPro.ch',
  description: 'Photovoltaïque dans le canton de Fribourg : électricité propre des constructions, subventions Pronovo et procédure d’annonce pour toits et façades.',
  h1: 'Installation solaire dans le canton de Fribourg : ce qui vaut pour les propriétaires en 2026',
  intro: [
    'Dans le canton de Fribourg, une construction doit produire elle-même une partie de son électricité. Il ne s’agit pas d’une obligation photovoltaïque générale pour chaque maison existante.',
    'Depuis 2026, une annonce peut suffire au lieu d’une demande de permis complète pour les installations suffisamment adaptées en toiture et en façade. Voici une explication claire de la règle de production propre, du délai, des subventions et des principales exceptions.',
  ],
  quickFacts: [
    { value: '10 W/m²', label: 'Puissance minimale de production propre pour une construction concernée', sourceIds: ['fr-energy-law'] },
    { value: '30 kW', label: 'Puissance maximale pouvant être exigée au titre de l’obligation des constructions', sourceIds: ['fr-energy-law'] },
    { value: '30 jours', label: 'Délai de principe pour l’annonce correspondante avant le début des travaux', sourceIds: ['fr-solar-permit'] },
    { value: '2026', label: 'Depuis lors, les installations en façade adaptées peuvent être examinées par voie d’annonce', sourceIds: ['fr-solar-permit'] },
  ],
  sections: [
    { id: 'neubau', title: 'Les constructions fribourgeoises doivent-elles produire leur propre électricité ?', paragraphs: [
      'Oui. Les constructions sont soumises à une obligation de production propre d’électricité. Dans la pratique, elle est souvent remplie par le photovoltaïque, mais la loi n’impose pas forfaitairement une installation photovoltaïque à chaque maison.',
      'L’exigence est d’au moins 10 W/m² de surface de référence énergétique (SRE). La SRE est la surface du bâtiment déterminante pour le calcul énergétique ; elle ne correspond pas simplement à la surface de toiture disponible. Au total, la puissance exigée ne peut pas dépasser 30 kW.',
      'Certains petits agrandissements sont exemptés. L’exception légale s’applique à un agrandissement inférieur à 50 m², ou représentant au plus 20 % du bâtiment existant et au plus 1 000 m² ; le projet concret doit être vérifié dans le justificatif énergétique.',
    ], sourceIds: ['fr-energy-law'], notice: { title: 'Pas d’obligation photovoltaïque générale pour chaque maison', text: 'La règle fribourgeoise concerne la production propre d’électricité des constructions. Elle n’entraîne pas automatiquement l’obligation d’équiper une maison existante d’une installation photovoltaïque.', status: 'important' }, module: { kind: 'project-check', title: 'Quelle règle s’applique à mon projet ?', intro: 'Examinez successivement et séparément ces deux questions : d’abord la règle de production propre, puis la procédure adaptée à l’installation.', items: [
      { title: '1. S’agit-il d’une construction ?', text: 'Oui : vérifier la production propre, soit au moins 10 W/m² de SRE ; la loi permet d’exiger au maximum 30 kW. Non : cette règle des constructions ne crée pas d’obligation générale de production propre pour une maison existante.', detail: 'Les petits agrandissements peuvent être exemptés : moins de 50 m², ou au plus 20 % de l’existant et au plus 1 000 m².', sourceIds: ['fr-energy-law'] },
      { title: '2. Le toit ou la façade sont-ils suffisamment adaptés ?', text: 'Oui : vérifier la procédure d’annonce et envoyer en principe l’annonce à la commune 30 jours avant le début des travaux. Non : clarifier le permis de construire avec la commune ; il peut rester nécessaire pour un objet protégé ou un site construit sensible.', detail: 'Depuis le 1er janvier 2026, les installations en façade suffisamment adaptées peuvent aussi être annoncées aux conditions de la procédure.', sourceIds: ['fr-solar-permit'] },
    ] } },
    { id: 'bewilligung', title: 'Annonce ou permis de construire ?', paragraphs: [
      'Pour de nombreux projets solaires suffisamment adaptés, une annonce peut suffire au lieu d’une demande de permis complète. Selon le cas, cela vaut pour les installations en toiture et, depuis le 1er janvier 2026, pour les installations en façade adaptées.',
      'Une annonce est une communication simplifiée à la commune, et non une autorisation automatique de chaque projet. Un permis de construire peut être requis pour les objets protégés, les sites construits sensibles ou une installation insuffisamment adaptée.',
      'Pour la règle correspondante concernant les façades, l’annonce intervient en principe 30 jours avant le début des travaux. Si une procédure ordinaire est nécessaire, les demandes de permis passent dans le canton de Fribourg par FRIAC, le portail cantonal en ligne.',
    ], bullets: ['Procédure d’annonce : déposer à temps les documents du projet auprès de la commune.', 'Objet protégé ou site construit sensible : clarifier tôt le permis avec l’autorité compétente.', 'Demande de permis ordinaire : utiliser le portail cantonal FRIAC.'], sourceIds: ['fr-solar-permit'] },
    { id: 'foerderung', title: 'Subventions dans le canton de Fribourg', paragraphs: [
      'L’encouragement d’une installation photovoltaïque relève principalement de la Confédération et de Pronovo. Selon la FAQ de Pronovo, la rétribution unique ordinaire (RU) est possible dès une puissance minimale de 2 kW ; son montant concret dépend du projet, de la puissance, du type d’installation et du modèle d’encouragement.',
      'Les bonus fédéraux supplémentaires ne forment pas automatiquement un montant global. Selon le projet, un bonus d’angle d’inclinaison dès 75°, un bonus pour les aires de stationnement pour les installations admissibles dès 100 kW ou, depuis 2026, un bonus d’électricité hivernale à certaines conditions pour les installations dès 100 kW peuvent par exemple entrer en ligne de compte. Chaque bonus a ses propres conditions et ne peut pas simplement être additionné aux autres contributions.',
      'Le Programme Bâtiments cantonal en est distinct. Il ne faut pas le présenter comme une subvention fribourgeoise générale pour toute installation photovoltaïque ; une mesure concrète sur le bâtiment et sa demande doivent être examinées séparément selon les conditions officielles.',
    ], sourceIds: ['fr-pronovo-faq', 'fr-energy-subsidies'], notice: { title: 'Distinguer l’encouragement fédéral du programme cantonal', text: 'Pronovo examine l’encouragement fédéral du photovoltaïque. Les programmes cantonaux des bâtiments peuvent soutenir leurs propres mesures énergétiques, mais ne constituent pas une contribution photovoltaïque forfaitaire pour chaque habitation.', status: 'important' } },
    { id: 'begriffe', title: 'Les principaux termes, simplement expliqués', paragraphs: [
      'W/m² signifie watts par mètre carré. Les 10 W/m² se rapportent à la surface de référence énergétique de la construction et décrivent la puissance exigée pour la production propre d’électricité.',
      'SRE signifie surface de référence énergétique. Il s’agit de la surface de bâtiment calculée pour les prescriptions énergétiques, et non automatiquement de la surface disponible pour les modules solaires.',
      'Une procédure d’annonce est la communication simplifiée d’un projet à la commune. Le permis de construire est en revanche la procédure ordinaire lorsque le projet doit être examiné de plus près pour des raisons de conception, de protection ou autres.',
    ], sourceIds: ['fr-energy-law', 'fr-solar-permit'] },
    { id: 'kosten', title: 'Combien coûte une installation solaire ici ?', paragraphs: [
      'Le canton ne publie aucun prix fixe pour les installations solaires. La toiture, la taille de l’installation, les travaux électriques et l’équipement sont déterminants.',
      'Comparez plusieurs offres pour le même projet. Vous verrez ainsi si les travaux de toiture, le raccordement, le stockage et la puissance souhaitée sont intégrés intégralement et de manière compréhensible.',
    ], bullets: ['Surface et forme du toit, surface utile pour les modules', 'Taille et puissance de l’installation', 'Échafaudage, accès et travaux de chantier', 'Travaux électriques, compteur et raccordement au réseau', 'Onduleur', 'Batterie de stockage et infrastructure de recharge', 'Consommation propre, pompe à chaleur et voiture électrique', 'Installateur, étendue des prestations et garanties'], sourceIds: ['fr-pronovo-faq', 'fr-solar-permit'] },
    { id: 'fuer-wen', title: 'À qui le solaire convient-il particulièrement à Fribourg ?', paragraphs: [
      'Les propriétaires d’une construction doivent planifier particulièrement tôt, car la production propre d’électricité fait partie du justificatif énergétique. Une grande surface de toiture adaptée ou une rénovation de toiture ou de façade déjà prévue peut aussi être le bon moment pour une planification commune.',
      'Le solaire convient également bien à un ménage doté d’une pompe à chaleur ou d’une voiture électrique lorsque la consommation propre et le raccordement sont planifiés ensemble. La pertinence de l’installation dépend du toit, de la consommation, de la procédure et de l’offre concrète ; on ne peut en déduire aucun rendement fixe.',
    ], sourceIds: ['fr-energy-law', 'fr-solar-permit', 'fr-pronovo-faq'] },
  ],
  faqs: [
    { question: 'Une obligation solaire s’applique-t-elle dans le canton de Fribourg ?', answer: 'Les constructions sont soumises à une obligation de production propre d’électricité, mais il n’existe pas d’obligation photovoltaïque générale pour chaque maison existante. Dans la pratique, le photovoltaïque peut remplir cette exigence. Les petits agrandissements peuvent être exemptés sous les seuils légaux.', sourceIds: ['fr-energy-law'] },
    { question: 'Combien d’électricité propre une construction doit-elle produire ?', answer: 'Une construction concernée doit prévoir au moins 10 W/m² de surface de référence énergétique pour la production propre. Au total, il ne peut être exigé plus de 30 kW. La surface de référence énergétique est la surface du bâtiment déterminante pour le calcul énergétique.', sourceIds: ['fr-energy-law'] },
    { question: 'Que signifie 10 W/m² ?', answer: 'W/m² signifie watts par mètre carré. Les 10 W/m² s’appliquent à la surface de référence énergétique de la construction, pas simplement à la surface de toiture utilisable. La puissance exigée pour la production propre en découle.', sourceIds: ['fr-energy-law'] },
    { question: 'Les petites annexes et les agrandissements sont-ils concernés ?', answer: 'Certains petits agrandissements sont exemptés. L’exception légale concerne un agrandissement inférieur à 50 m², ou représentant au plus 20 % de l’existant et au plus 1 000 m². Le classement exact doit être vérifié pour le projet de construction concret.', sourceIds: ['fr-energy-law'] },
    { question: 'Dois-je déposer une demande de permis pour une installation photovoltaïque ?', answer: 'Pas toujours. Une annonce peut suffire pour une installation suffisamment adaptée. Un permis de construire peut être nécessaire pour les objets protégés, les sites construits sensibles ou si l’intégration est insuffisante ; en procédure ordinaire, la demande passe par FRIAC.', sourceIds: ['fr-solar-permit'] },
    { question: 'Qu’est-ce qui a changé pour les façades en 2026 ?', answer: 'Depuis le 1er janvier 2026, les installations solaires en façade suffisamment adaptées peuvent aussi suivre une procédure d’annonce aux conditions en vigueur. Cela ne s’applique pas automatiquement à chaque façade. Les objets protégés et sites construits sensibles peuvent toujours exiger un permis.', sourceIds: ['fr-solar-permit'] },
    { question: 'Combien de temps à l’avance faut-il annoncer une installation en façade correspondante ?', answer: 'Dans cette procédure, l’annonce est en principe adressée à la commune 30 jours avant le début des travaux. L’intégration, le statut de protection et l’exhaustivité des documents doivent être clarifiés auparavant. Le délai ne remplace pas un permis supplémentaire si celui-ci est nécessaire.', sourceIds: ['fr-solar-permit'] },
    { question: 'Quelles subventions existent pour une installation solaire à Fribourg ?', answer: 'L’aide à l’investissement photovoltaïque relève principalement de la Confédération et de Pronovo. Selon la FAQ de Pronovo, la rétribution unique ordinaire est possible dès 2 kW, le soutien concret dépendant du projet et des conditions fédérales. Les programmes cantonaux des bâtiments sont distincts et ne constituent pas une subvention photovoltaïque générale.', sourceIds: ['fr-pronovo-faq', 'fr-energy-subsidies'] },
    { question: 'Quels bonus fédéraux supplémentaires peuvent être pertinents ?', answer: 'Selon le projet, il existe des bonus fédéraux facultatifs assortis de conditions propres, par exemple un bonus d’angle d’inclinaison dès 75°, un bonus pour les aires de stationnement destiné aux installations admissibles dès 100 kW ou, depuis 2026, un bonus d’électricité hivernale à certaines conditions dès 100 kW. Ces bonus ne sont pas garantis et ne doivent pas être additionnés en un montant forfaitaire.', sourceIds: ['fr-pronovo-faq'] },
    { question: 'Qu’en est-il d’un bâtiment protégé ?', answer: 'Les objets protégés et les sites construits sensibles peuvent toujours nécessiter un permis de construire. Une annonce simplifiée pour une installation suffisamment adaptée n’est donc pas automatiquement possible. Clarifiez tôt le statut de protection avec la commune ou l’autorité compétente.', sourceIds: ['fr-solar-permit'] },
  ],
  sources: [...sources],
};