import type { CantonGuide } from '../types';

const sources = [
  { id: 'ju-programme', authority: 'République et Canton du Jura', title: 'Programme Bâtiments – état des subventions 2026', url: 'https://www.jura.ch/fr/Autorites/Administration/DEC/SDT/Energie/Subventions/Programme-Batiments/Programme-Batiments.html' },
  { id: 'ju-energy-law', authority: 'République et Canton du Jura', title: 'Ordonnance sur l’énergie, règle relative à la production propre', url: 'https://rsju.jura.ch/fr/viewdocument.html?download=1&id=38231&idn=20131' },
  { id: 'ju-solar-permit', authority: 'République et Canton du Jura', title: 'Panneaux solaires – permis de construire', url: 'https://www.jura.ch/fr/Autorites/Administration/DEC/SDT/Permis-de-construire/Panneaux-solaires/Panneaux-solaires.html' },
  { id: 'ju-jurac', authority: 'République et Canton du Jura', title: 'JURAC – portail électronique des demandes de permis de construire', url: 'https://www.jura.ch/fr/Autorites/JURAC/Requerants-Auteurs-du-projet/JURAC-Requerants-auteurs-du-projet.html' },
  { id: 'ju-foerderportal', authority: 'Promotion énergétique cantonale', title: 'Portail des subventions pour les programmes cantonaux', url: 'https://portal.energie-foerderung.ch' },
  { id: 'ju-pronovo', authority: 'Pronovo SA sur mandat de la Confédération', title: 'Questions fréquentes sur la rétribution unique (RU) et les subventions solaires en Suisse', url: 'https://pronovo.ch/de/foerderung/photovoltaik/haeufige-fragen/' },
] as const;

export const guide: CantonGuide = {
  id: 'jura', path: '/fr/solaire-jura', canton: 'Jura', title: 'Solaire dans le Jura en 2026 : subventions et règles | PvPro.ch',
  description: 'Photovoltaïque dans le Jura : état des subventions en septembre 2026, production propre dans les bâtiments neufs, Pronovo, annonce et JURAC.',
  h1: 'Installation solaire dans le Jura : subventions et règles – état en septembre 2026',
  intro: ['Dans le Jura, la situation au 15 septembre 2026 fait foi. Le budget ordinaire du Programme Bâtiments est en grande partie épuisé ; la mesure M-01 est sur liste d’attente.', 'Vérifiez séparément Pronovo et les éventuels fonds résiduels du Programme d’impulsion. Les bâtiments neufs doivent produire 10 W/m² de SRE, avec un maximum de 30 kW. Selon l’installation, une annonce peut suffire ; la commune décide de la procédure.'],
  quickFacts: [
    { value: 'À vérifier séparément', label: 'Pronovo / Confédération : subventions photovoltaïques actuelles', sourceIds: ['ju-pronovo'] },
    { value: 'Liste d’attente', label: 'M-01 enveloppe du bâtiment', sourceIds: ['ju-programme'] },
    { value: 'Vérifier les fonds résiduels', label: 'Programme d’impulsion : état actuel', sourceIds: ['ju-programme'] },
  ],
  sections: [
    { id: 'foerderung', title: 'Quelles subventions sont encore disponibles ?', paragraphs: [
      'Selon l’état cantonal au 15 septembre 2026, le budget ordinaire 2026 du Programme Bâtiments est en grande partie épuisé. La mesure M-01 est sur liste d’attente ; Pronovo et le Programme d’impulsion doivent être vérifiés séparément.',
      'Les subventions fédérales actuelles pour les installations photovoltaïques passent par Pronovo. La rétribution unique ordinaire (RU) s’applique actuellement dès 2 kW. Les bonus fédéraux supplémentaires, par exemple pour l’inclinaison, les aires de stationnement ou l’électricité hivernale, ont leurs propres conditions et ne peuvent pas être simplement additionnés en une somme commune.',
      'Le Programme d’impulsion et les mesures pour les bâtiments financées exclusivement par la Confédération doivent être examinés séparément du budget cantonal ordinaire. M-01 concerne l’enveloppe du bâtiment et ne constitue pas une subvention photovoltaïque générale. Un budget cantonal épuisé ne signifie donc pas que toute autre aide est également épuisée.',
    ], sourceIds: ['ju-programme', 'ju-pronovo'], module: { kind: 'funding-status', title: 'Feu des subventions du Jura', intro: 'État : 15 septembre 2026. Vérifiez de nouveau la situation avant de passer commande et de commencer les travaux.', items: [
      { title: 'Pronovo / Confédération', text: 'Vérifiez séparément les subventions fédérales actuelles pour le photovoltaïque. La rétribution unique et les éventuels bonus fédéraux dépendent de leurs conditions respectives.', detail: 'RU actuellement dès 2 kW ; les bonus facultatifs ne s’additionnent pas automatiquement.', value: 'À vérifier séparément', sourceIds: ['ju-pronovo'] },
      { title: 'Programme d’impulsion', text: 'Les éventuels fonds résiduels du Programme d’impulsion doivent être évalués séparément du budget ordinaire du Programme Bâtiments. Vérifiez le montant actuel avant de passer commande.', value: 'Vérifier les fonds résiduels', sourceIds: ['ju-programme'] },
      { title: 'M-01 enveloppe du bâtiment', text: 'M-01 concerne l’enveloppe du bâtiment, et non une subvention photovoltaïque générale. Cette mesure fait actuellement l’objet d’une liste d’attente.', value: 'Liste d’attente', sourceIds: ['ju-programme'] },
    ] } },
    { id: 'jahresbudget', title: 'Pourquoi l’état actuel compte davantage que le budget annuel', paragraphs: ['Le programme global a débuté en 2026 avec CHF 3,893 millions : environ CHF 1,18 million provenait du Canton et CHF 2,713 millions de la Confédération.', 'Cette répartition décrit le budget du début de l’année. Elle ne signifie pas que le même montant est encore disponible en septembre. L’information actuelle sur chaque programme est donc déterminante, et non l’ancienne brochure du début d’année.'], sourceIds: ['ju-programme'] },
    { id: 'neubau', title: 'Production propre dans les bâtiments neufs', paragraphs: ['Dans le Jura, les bâtiments neufs sont soumis à une obligation de production propre de 10 W/m² de SRE, avec un maximum de 30 kW.', 'SRE signifie surface de référence énergétique. Il s’agit de la surface prise en compte pour le calcul énergétique du bâtiment. La règle porte sur la production propre d’électricité et n’instaure pas automatiquement une obligation photovoltaïque générale pour chaque bâtiment existant.', 'Les unités se lisent simplement : W/m² décrit la puissance requise par mètre carré de SRE, et kW la puissance totale de l’installation. Le respect de l’exigence et le choix de la solution adaptée doivent être intégrés dès les premières phases de conception du bâtiment neuf.'], sourceIds: ['ju-energy-law'] },
    { id: 'bewilligung', title: 'Annonce ou demande de permis de construire ?', paragraphs: ['Non, un permis de construire n’est pas toujours nécessaire. Si les conditions du droit fédéral sont respectées, certaines installations solaires peuvent faire l’objet d’une annonce à la commune.', 'L’annonce est une notification à la commune qui remplace une demande de permis complète. La commune décide si une procédure ordinaire est nécessaire.', 'Lorsqu’une demande de permis est nécessaire, elle passe par JURAC. JURAC est le portail électronique cantonal des demandes de permis de construire.'], sourceIds: ['ju-solar-permit', 'ju-jurac'] },
    { id: 'vor-bestellung', title: 'Ce qu’il faut vérifier avant de passer commande', paragraphs: ['Clarifiez les subventions, la procédure et la compétence communale avant de passer commande. Les demandes concernant les programmes pour les bâtiments visés doivent en principe être déposées avant le début des travaux subventionnés.', 'Vous évitez ainsi de confier un mandat avant que l’état actuel des subventions ou la procédure requise ne soit établi.', 'Pour les demandes relevant des programmes cantonaux pour les bâtiments, utilisez le portail portal.energie-foerderung.ch. Il faut le distinguer du portail des constructions JURAC et des subventions photovoltaïques fédérales gérées par Pronovo.'], bullets: ['Pronovo et la RU actuelle pour votre installation', 'état cantonal actuel des programmes pour les bâtiments et du Programme d’impulsion', 'commune : procédure d’annonce ou demande de permis ordinaire', 'procédure de construction et JURAC si une demande de permis est nécessaire', 'demande de subvention avant le début des travaux subventionnés'], sourceIds: ['ju-programme', 'ju-solar-permit', 'ju-jurac', 'ju-pronovo', 'ju-foerderportal'] },
    { id: 'kosten', title: 'Combien coûte une installation solaire ici ?', paragraphs: ['Le Canton ne publie pas de prix fixe pour les installations solaires. La toiture, la taille de l’installation, les travaux électriques et l’équipement sont déterminants.', 'Le prix final dépend du bâtiment concret et de l’étendue des prestations souhaitées. Comparez donc plusieurs offres pour le même projet et examinez les conditions de subvention séparément des coûts d’investissement.'], bullets: ['surface et forme de la toiture', 'taille et puissance de l’installation', 'échafaudage, accès et contraintes du chantier', 'travaux électriques, compteur et raccordement au réseau', 'onduleur', 'batterie de stockage', 'autoconsommation et profil de consommation', 'étendue des prestations et garanties de l’installateur'], sourceIds: ['ju-programme', 'ju-pronovo'] },
  ],
  faqs: [
    { question: 'Les bâtiments neufs sont-ils soumis à une obligation de production propre dans le Jura ?', answer: 'Oui. Les bâtiments neufs doivent produire leur propre électricité. Cette règle n’entraîne pas d’obligation photovoltaïque générale pour les bâtiments existants.', sourceIds: ['ju-energy-law'] },
    { question: 'Quelle quantité d’électricité propre un bâtiment neuf doit-il produire ?', answer: 'La puissance minimale est de 10 W/m² de SRE. Cette règle ne peut pas imposer plus de 30 kW.', sourceIds: ['ju-energy-law'] },
    { question: 'Le budget de subvention 2026 est-il encore disponible ?', answer: 'Selon l’état cantonal au 15 septembre 2026, le budget ordinaire du Programme Bâtiments est en grande partie épuisé. Les CHF 3,893 millions du début d’année ne prouvent donc pas que des fonds sont encore disponibles aujourd’hui.', sourceIds: ['ju-programme'] },
    { question: 'Que signifie la liste d’attente pour M-01 ?', answer: 'M-01 est actuellement sur liste d’attente. Cette mesure relève des subventions pour l’enveloppe du bâtiment et ne constitue pas une subvention photovoltaïque générale.', sourceIds: ['ju-programme'] },
    { question: 'Dois-je déposer ma demande avant le début des travaux ?', answer: 'Oui, les demandes pertinentes pour les programmes concernant les bâtiments doivent en principe être déposées avant le début des travaux subventionnés. Vérifiez l’état actuel et les conditions avant de confier le mandat.', sourceIds: ['ju-programme'] },
    { question: 'Faut-il toujours un permis de construire pour le photovoltaïque ?', answer: 'Non. Lorsque les conditions en vigueur sont remplies, une annonce à la commune peut suffire. La commune vérifie si une procédure de construction ordinaire est nécessaire.', sourceIds: ['ju-solar-permit'] },
    { question: 'Qui décide de la procédure ?', answer: 'La commune décide si une annonce suffit ou si une procédure ordinaire est requise. Clarifiez ce point avec la commune compétente avant le début des travaux.', sourceIds: ['ju-solar-permit'] },
    { question: 'Qu’est-ce que JURAC ?', answer: 'JURAC est le portail électronique cantonal des demandes de permis de construire. Si votre projet solaire nécessite une demande de permis, elle y est déposée.', sourceIds: ['ju-jurac'] },
    { question: 'Qu’est-ce que Pronovo et à partir de quelle puissance la rétribution unique s’applique-t-elle ?', answer: 'Pronovo gère les subventions fédérales actuelles pour les installations photovoltaïques. La rétribution unique ordinaire s’applique actuellement à partir d’une puissance minimale de 2 kW.', sourceIds: ['ju-pronovo'] },
    { question: 'Puis-je simplement additionner les contributions cantonales et les bonus fédéraux ?', answer: 'Non. Les aides de Pronovo, les programmes cantonaux et les bonus fédéraux facultatifs doivent être examinés selon leurs propres conditions. Aucun montant global forfaitaire n’est garanti.', sourceIds: ['ju-programme', 'ju-pronovo'] },
    { question: 'Que signifie SRE ?', answer: 'SRE signifie surface de référence énergétique. Il s’agit de la surface déterminante pour le calcul énergétique du bâtiment.', sourceIds: ['ju-energy-law'] },
  ], sources: [...sources],
};
