import type { CantonGuide } from '../types';
const sources = [
 {id:'lu-keng',authority:'Canton de Lucerne, Environnement et énergie',title:'Loi cantonale sur l’énergie en bref – Canton de Lucerne',url:'https://uwe.lu.ch/Energiegesetz/KEnG_kompakt'},
 {id:'lu-foerderprogramme',authority:'Canton de Lucerne, Environnement et énergie',title:'Programmes de subventions énergétiques – Canton de Lucerne',url:'https://uwe.lu.ch/themen/energie/foerderprogramme'},
 {id:'lu-even',authority:'Canton de Lucerne, Environnement et énergie',title:'Justificatifs énergétiques dès le 1er janvier 2026 – Canton de Lucerne',url:'https://uwe.lu.ch/Energiegesetz/Energienachweise_ab_Anfang_2026'},
 {id:'lu-solar',authority:'Canton de Lucerne, Environnement et énergie',title:'Énergie solaire – Canton de Lucerne, Environnement et énergie',url:'https://uwe.lu.ch/themen/energie/erneuerbare_energien/Solar'},
] as const;
export const guide:CantonGuide={
 id:'luzern',path:'/fr/solaire-lucerne',canton:'Lucerne',title:'Solaire à Lucerne en 2026 : obligations, subventions et offres | PvPro.ch',description:'Les règles à Lucerne pour les bâtiments neufs et rénovations de toiture : production propre, taxe de remplacement, subventions et offres solaires.',h1:'Installation solaire à Lucerne : règles, subventions et offres 2026',
 intro:['Dans le canton de Lucerne, les bâtiments neufs et certaines rénovations de toiture sont soumis à des exigences précises concernant la production propre d’électricité. Découvrez ce qui s’applique à votre projet et quelles voies de subvention sont pertinentes.','Depuis le 1er mars 2025, il est particulièrement important de distinguer bâtiment neuf, rénovation de toiture, réparation et entretien. Depuis 2026, le justificatif énergétique est traité sur la plateforme numérique EVEN.'],
 quickFacts:[{value:'Depuis le 1.3.2025',label:'production propre pour bâtiment neuf et rénovation de toiture',sourceIds:['lu-keng']},{value:'Max. CHF 1’000',label:'de taxe de remplacement par kW manquant',sourceIds:['lu-keng']},{value:'Subventions photovoltaïques',label:'Confédération / Pronovo',sourceIds:['lu-foerderprogramme']},{value:'2026',label:'justificatif énergétique via EVEN',sourceIds:['lu-even']}],ctaAfterSection:'dach-check',
 sections:[
  {id:'dach-check',title:'Bâtiment neuf, rénovation ou réparation : que faut-il prévoir pour ma toiture ?',paragraphs:['Depuis le 1er mars 2025, dans le canton de Lucerne, la production propre d’électricité est pertinente pour les bâtiments neufs et les bâtiments existants dont la toiture est rénovée. La première étape consiste donc à qualifier correctement le projet.'],sourceIds:['lu-keng','lu-solar'],module:{kind:'roof-duty-check',title:'Que faut-il prévoir pour ma toiture ?',intro:'Classez le projet, puis vérifiez si l’exigence est satisfaite par une production propre ou si une taxe de remplacement doit être examinée.',items:[
   {title:'Bâtiment neuf',value:'Règle de production propre',text:'Pour un bâtiment neuf, exploiter convenablement le potentiel de production d’électricité et vérifier la règle de production propre applicable au projet.',sourceIds:['lu-keng']},
   {title:'Véritable rénovation de toiture',value:'Règle de production propre',text:'Pour un bâtiment existant dont la toiture est rénovée, le potentiel de production d’électricité doit également être exploité convenablement.',sourceIds:['lu-keng']},
   {title:'Réparation / entretien',value:'Pas automatiquement une rénovation',text:'Ne pas assimiler globalement de simples travaux de réparation et d’entretien à une rénovation complète de toiture ; vérifier le projet concret à l’aide du guide d’exécution cantonal.',sourceIds:['lu-solar','lu-keng']},
   {title:'Exigence satisfaite',value:'Production propre',text:'Si l’exigence est satisfaite, poursuivre la planification avec l’installation photovoltaïque ou la production propre prévue.',sourceIds:['lu-keng']},
   {title:'Exigence non satisfaite',value:'Taxe de remplacement',text:'Si l’exigence n’est pas satisfaite, examiner une taxe de remplacement. Elle s’élève au maximum à CHF 1’000 par kW de puissance minimale requise mais non réalisée.',sourceIds:['lu-keng']},
  ]}},
  {id:'even',title:'Justificatif énergétique 2026 : traitement via EVEN',paragraphs:['Clarifiez avec l’entreprise spécialisée chargée de la planification qui prépare le justificatif énergétique de votre projet et prend en charge la procédure numérique. La planification technique et la documentation seront ainsi coordonnées.'],sourceIds:['lu-even'],notice:{title:'EVEN dès le 1er janvier 2026',text:'Depuis le 1er janvier 2026, le justificatif énergétique est traité dans le canton de Lucerne sur la plateforme numérique EVEN.',status:'important'}},
  {id:'foerderung',title:'Subventions photovoltaïques de la Confédération et de Pronovo',paragraphs:['La Confédération, respectivement Pronovo, est compétente pour la subvention ordinaire d’une installation photovoltaïque. Les programmes lucernois mentionnés ici ne prévoient pas de contribution cantonale générale au photovoltaïque.','Faites indiquer séparément la subvention attendue dans l’offre. Pour une comparaison transparente, il faut d’abord connaître le prix de l’installation avant déduction de la subvention, puis la base du soutien supposé. Une éventuelle taxe de remplacement n’est pas une subvention, mais un poste de comparaison distinct.'],sourceIds:['lu-foerderprogramme','lu-keng']},
  {id:'vorhaben',title:'Préparer ensemble les travaux de toiture et l’installation solaire',paragraphs:['Décrivez aussi précisément que possible à l’entreprise spécialisée les travaux prévus sur la toiture. Des photos, les plans disponibles et une description de la composition du toit facilitent la qualification du projet selon le guide d’exécution cantonal. La seule mention « travaux de toiture » renseigne encore peu sur l’intervention réelle.','Coordonnez ensuite les travaux sur le bâtiment avec le montage photovoltaïque. Demandez quels échafaudages et travaux annexes sont déjà inclus dans l’offre de toiture et lesquels sont proposés en supplément pour l’installation solaire. Vous éviterez ainsi de comparer des prix couvrant des prestations différentes.'],sourceIds:['lu-solar','lu-keng']},
  {id:'kosten',title:'Combien coûte une installation solaire à Lucerne ?',paragraphs:['Un prix forfaitaire ne remplace pas une offre établie pour votre bâtiment. Les postes suivants doivent figurer clairement dans l’offre ou en être expressément exclus.','À Lucerne, un autre point de comparaison s’ajoute : la solution technique et une éventuelle taxe de remplacement ne doivent pas être comparées sur la base d’hypothèses de projet différentes. Demandez donc des offres reposant sur la même base.','Avec PvPro.ch, les propriétaires peuvent comparer gratuitement et sans engagement jusqu’à trois offres solaires adaptées.'],bullets:['surface et géométrie de la toiture','accessibilité et échafaudages','intégration au bâtiment','tableau électrique','batterie de stockage','travaux annexes'],sourceIds:['lu-keng','lu-solar']},
  {id:'offerten-pruefen',title:'Quelles différences entre les offres sont importantes ?',paragraphs:['Ne vérifiez pas seulement le prix final, mais aussi les prestations proposées et la répartition des travaux. La batterie est-elle proposée en option ou déjà comprise ? Les travaux électriques et les adaptations du tableau sont-ils inclus ? Quels postes sont facturés selon le travail effectif ?','En cas d’écarts, demandez une brève explication et une variante d’offre comparable. Ce n’est qu’en classant de la même manière les prestations, les travaux sur le bâtiment et les équipements facultatifs que l’on peut déterminer si une différence de prix tient à l’étendue des prestations ou à l’offre elle-même.'],sourceIds:[]},
 ],faqs:[
  {question:'L’obligation de production propre s’applique-t-elle aussi à une rénovation de toiture à Lucerne ?',answer:'Oui. Dans les bâtiments neufs et les bâtiments existants dont la toiture est rénovée, le potentiel de production d’électricité doit être exploité convenablement ; une taxe de remplacement est possible à défaut.',sourceIds:['lu-keng']},
  {question:'À combien peut s’élever la taxe de remplacement ?',answer:'Elle s’élève au maximum à CHF 1’000 par kW de puissance minimale requise mais non réalisée.',sourceIds:['lu-keng']},
  {question:'Toute petite réparation de toiture est-elle automatiquement une rénovation ?',answer:'Non. De simples travaux de réparation et d’entretien ne doivent pas être assimilés globalement à une rénovation complète de toiture ; le projet concret doit être vérifié à l’aide du guide d’exécution cantonal.',sourceIds:['lu-solar','lu-keng']},
  {question:'Le canton de Lucerne subventionne-t-il directement les installations photovoltaïques ordinaires ?',answer:'Les subventions ordinaires pour les installations photovoltaïques relèvent de la Confédération, respectivement de Pronovo ; les programmes cantonaux ne doivent pas être présentés comme une contribution photovoltaïque générale.',sourceIds:['lu-foerderprogramme']},
  {question:'Qu’est-ce qui change pour le justificatif énergétique en 2026 ?',answer:'Depuis le 1er janvier 2026, le justificatif énergétique est traité dans le canton de Lucerne sur la plateforme numérique EVEN.',sourceIds:['lu-even']},
 ],sources:[...sources]};
