import type { CantonGuide } from '../types';
export const guide:CantonGuide={id:'neuenburg',path:'/fr/solaire-neuchatel',canton:'Neuchâtel',title:'Solaire à Neuchâtel en 2026 : obligation et batteries | PvPro.ch',description:'15 W/m² pour les bâtiments neufs et nouvelles subventions au stockage depuis mars 2026 : règles photovoltaïques essentielles à Neuchâtel et offres.',h1:'Solaire à Neuchâtel : obligation photovoltaïque et batteries en 2026',intro:['Neuchâtel associe des exigences claires de production propre pour les bâtiments neufs à une nouvelle subvention cantonale pour les batteries photovoltaïques. Il est essentiel de bien distinguer ces deux instruments.'],quickFacts:[{value:'15 W/m² SRE',label:'production propre dans le bâtiment neuf ; au moins 1 kW de puissance installée',sourceIds:['ne-relcen']},{value:'CHF 800 + CHF 80/kWh',label:'contribution cantonale pour la batterie selon les conditions de subvention',sourceIds:['ne-battery-order','ne-battery-page']},{value:'dès le 1.3.2026',label:'subvention cantonale pour les batteries photovoltaïques',sourceIds:['ne-battery-order','ne-battery-page']},{value:'max. 50 %',label:'part de l’investissement total couverte par la contribution pour la batterie',sourceIds:['ne-battery-order','ne-battery-page']}],ctaAfterSection:'batterycheck',sections:[
 {id:'neubaupflicht',title:'Distinguer production propre dans le bâtiment neuf et batterie de stockage',paragraphs:['Les deux valeurs minimales applicables aux bâtiments neufs se cumulent : la surface de référence énergétique, ou SRE, détermine la puissance requise. Une puissance minimale s’applique en même temps, indépendamment de ce calcul par surface.','Il s’agit d’une exigence de production propre d’électricité, et non d’une obligation d’acheter une batterie. La subvention cantonale au stockage est un instrument distinct et peut aussi être pertinente pour une installation photovoltaïque existante.'],sourceIds:['ne-relcen']},
 {id:'batterycheck',title:'Votre batterie est-elle admissible au programme cantonal ?',paragraphs:['Vérifiez ensemble les conditions suivantes. La formule de contribution ne constitue pas à elle seule une promesse de subvention ; toute la capacité de stockage installée ne peut notamment pas toujours être prise en compte.'],sourceIds:['ne-battery-order','ne-battery-page'],module:{kind:'battery-eligibility',title:'Vérification de la subvention pour batterie 2026',intro:'Formule de contribution : CHF 800 par installation + CHF 80/kWh de capacité de stockage installée.',items:[
  {title:'Capacité >3 kWh',text:'La batterie doit avoir une capacité supérieure à 3 kWh.',value:'>3 kWh',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Capacité subventionnable',text:'La capacité subventionnable est limitée au double de la puissance photovoltaïque installée en kWc.',detail:'Au maximum 2 × la puissance photovoltaïque installée en kWc',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Plafond de la contribution',text:'La contribution totale ne peut pas dépasser 50 % de l’investissement total.',value:'max. 50 %',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Bâtiment, photovoltaïque et autoconsommation',text:'Il faut un bâtiment d’habitation, une installation photovoltaïque sur place et l’autoconsommation d’une partie de l’électricité solaire.',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Mise en service dès le 1er mars 2026',text:'Les batteries de stockage mises en service dès le 1er mars 2026 sont subventionnables. Le justificatif de sécurité correspondant fait foi.',detail:'Le justificatif de sécurité fait foi',sourceIds:['ne-battery-order','ne-battery-page']},
 ]},notice:{title:'Vérifier tous les critères ensemble',text:'La formule de contribution ne suffit pas à établir l’admissibilité. Capacité, puissance photovoltaïque, part de l’investissement, bâtiment, autoconsommation et justificatif de sécurité font partie de la vérification complète.',status:'important'}},
 {id:'bestehende-pv',title:'Ajouter une batterie à une installation photovoltaïque existante',paragraphs:['Une installation photovoltaïque existante n’exclut pas la subvention pour batterie. Celle-ci s’applique aussi avec une installation photovoltaïque existante, à condition qu’elle se trouve sur place, qu’une partie de l’électricité solaire soit autoconsommée et que les autres conditions soient remplies.','La distinction reste donc importante : l’exigence de 15 W/m² de SRE et d’au moins 1 kW vise les bâtiments neufs. La vérification de la batterie peut en revanche aussi concerner le complément d’une installation photovoltaïque existante.'],bullets:['Une installation photovoltaïque existante sur place est admise.','Une partie de l’électricité solaire doit être autoconsommée.','Les autres conditions de la vérification de la subvention pour batterie restent applicables.'],sourceIds:['ne-battery-order','ne-battery-page','ne-relcen']},
 {id:'nachweis',title:'Quelles données sont importantes pour vérifier la subvention ?',paragraphs:['Pour l’évaluation, la puissance photovoltaïque installée en kWc, la capacité de stockage installée et l’investissement total doivent être indiqués clairement et séparément. On peut ainsi vérifier la capacité subventionnable par rapport à la puissance photovoltaïque et comprendre le plafond de la contribution.','Pour les batteries mises en service dès le 1er mars 2026, le justificatif de sécurité correspondant fait foi. Le bâtiment d’habitation, l’installation photovoltaïque sur place et l’autoconsommation doivent en outre être examinés avec les autres conditions.'],bullets:['Examiner séparément la puissance photovoltaïque installée en kWc et la capacité de stockage installée.','Indiquer l’investissement total pour vérifier le plafond de 50 %.','Inclure le justificatif de sécurité et l’autoconsommation dans la vérification.'],sourceIds:['ne-battery-order','ne-battery-page']},
 {id:'kosten',title:'Coût d’une installation photovoltaïque avec batterie',paragraphs:['Les coûts ne dépendent pas uniquement de la puissance photovoltaïque. Pour une batterie, la capacité utile, la compatibilité de l’onduleur et l’intégration à l’installation existante ou nouvelle comptent particulièrement. La contribution cantonale est une règle de subvention et non la garantie d’une rentabilité donnée.','Comparez donc les offres sur la même base de projet. Le dimensionnement de la batterie doit pouvoir être compris séparément de celui de l’installation photovoltaïque, afin de ne pas confondre puissance, capacité et travaux électriques.'],bullets:['capacité de stockage utile et taille de batterie adaptée','onduleur et compatibilité technique','armoire électrique et autres travaux électriques','intégration à une installation photovoltaïque nouvelle ou existante'],sourceIds:['ne-battery-order','ne-battery-page']},
 {id:'offerten',title:'Comparer des offres adaptées pour le photovoltaïque et le stockage',paragraphs:['PvPro aide les propriétaires à comparer sans engagement jusqu’à trois offres adaptées pour le photovoltaïque et, s’ils le souhaitent, des solutions de stockage.','Faites indiquer séparément dans les offres la puissance photovoltaïque, les capacités de stockage installée et utile ainsi que les travaux électriques. Vous pourrez ainsi vérifier la subvention pour batterie et la réalisation technique sur la même base.'],sourceIds:[]},
],faqs:[
 {question:'Quelle quantité d’électricité propre un bâtiment neuf doit-il produire à Neuchâtel ?',answer:'Pour les bâtiments neufs, le droit cantonal de l’énergie exige au moins 15 W/m² de surface de référence énergétique, ou SRE, et au moins 1 kW de puissance installée.',sourceIds:['ne-relcen']},
 {question:'Depuis quand la subvention cantonale pour les batteries photovoltaïques existe-t-elle ?',answer:'Les batteries de stockage mises en service dès le 1er mars 2026 sont subventionnables ; le justificatif de sécurité correspondant fait foi.',sourceIds:['ne-battery-order','ne-battery-page']},
 {question:'Comment la subvention pour batterie est-elle calculée ?',answer:'La contribution comprend CHF 800 par installation plus CHF 80 par kWh de capacité de stockage installée et ne peut pas dépasser 50 % de l’investissement total.',sourceIds:['ne-battery-order','ne-battery-page']},
 {question:'Quelle taille de batterie est subventionnée ?',answer:'La batterie doit avoir une capacité supérieure à 3 kWh ; la capacité subventionnable est limitée au double de la puissance photovoltaïque installée en kWc.',sourceIds:['ne-battery-order','ne-battery-page']},
 {question:'La batterie peut-elle être ajoutée à une installation photovoltaïque existante ?',answer:'Oui. La subvention s’applique aussi avec une installation photovoltaïque existante, à condition qu’elle se trouve sur place, qu’une partie de l’électricité solaire soit autoconsommée et que les autres conditions soient remplies.',sourceIds:['ne-battery-order','ne-battery-page']},
],sources:[
 {id:'ne-relcen',authority:'Canton de Neuchâtel',title:'Règlement d’exécution de la loi cantonale sur l’énergie (RELCEn)',url:'https://rsn.ne.ch/DATA/program/books/RSN2021/20214/htm/74010.htm'},
 {id:'ne-battery-order',authority:'Canton de Neuchâtel',title:'740.13 : Arrêté relatif au subventionnement des batteries de stockage d’électricité photovoltaïque (ASBaSt), du 4 février 2026',url:'https://rsn.ne.ch/DATA/program/books/rsne/htm/740.13.htm'},
 {id:'ne-battery-page',authority:'Canton de Neuchâtel',title:'Subventions pour les batteries domestiques de stockage d’électricité photovoltaïque | ne.ch',url:'https://www.ne.ch/themes/energie-et-environnement/energie/subventions-pour-les-batteries-domestiques-de-stockage-delectricite-photovoltaique'},
]};
