import type { GuideContent } from './types';

export const de: GuideContent = {
  metaTitle: 'Den passenden Solarinstallateur wählen',
  metaDescription: 'Solarofferten fundiert vergleichen: Leistungsumfang, Komponenten, Dachprüfung, Garantien und Vertragsbedingungen. Mit Fragen und Checkliste vor der Unterschrift.',
  home: 'Startseite',
  breadcrumb: 'Solaranbieter wählen',
  eyebrow: 'PvPro.ch · Entscheidungsratgeber',
  title: 'Die beste Offerte ist nicht einfach die günstigste.',
  intro: 'Der passende Solarinstallateur erklärt nicht nur den Preis. Er zeigt, was auf Ihrem Dach möglich ist, was im Auftrag enthalten ist und wer später für die Anlage einsteht. So vergleichen Sie Angebote, bevor Sie sich entscheiden.',
  noteTitle: 'Erst verstehen. Dann unterschreiben.',
  noteText: 'Kein Anbieterranking, sondern konkrete Prüfpunkte für Ihr eigenes Projekt. Ein guter Vergleich beginnt mit denselben Voraussetzungen.',
  navLabel: 'In diesem Ratgeber',
  sections: ['Vergleichsbasis', 'Offerten prüfen', 'Garantien verstehen', 'Warnsignale', 'Vor der Unterschrift'],
  basisTitle: 'Gleiche Leistung. Gleicher Umfang. Erst dann den Preis vergleichen.',
  basisParagraphs: [
    'Legen Sie den Offerten dieselben Projektangaben zugrunde: Dachfläche, Stromverbrauch, geplante Wärmepumpe oder Ladestation und den Wunsch nach einem Speicher. Die Nennleistung in kWp beschreibt die Leistung unter standardisierten Prüfbedingungen, nicht den tatsächlichen Jahresertrag.',
    'Vergleichen Sie die gesamte installierte Leistung und den gleichen Lieferumfang. Ein Angebot mit Speicher, Gerüst und Elektroarbeiten ist nicht direkt mit einem Angebot ohne diese Leistungen vergleichbar. Lassen Sie fehlende Positionen ergänzen und optionale Leistungen separat ausweisen.',
    'Stellen Sie den Gesamtpreis inklusive Mehrwertsteuer vor Förderabzügen gegenüber. Förderbeiträge und mögliche Steuerabzüge gehören in eine separate Rechnung: Anspruch, Höhe und Auszahlung können von Bedingungen Ihres Projekts sowie von Kanton, Gemeinde und zuständiger Stelle abhängen. Klären Sie, wer den Antrag stellt und wer eine ausbleibende Förderung trägt.',
  ],
  principle: 'Vergleichsbasis: gleiche kWp + gleicher Leistungsumfang + Gesamtpreis vor Förderabzügen',
  tableTitle: 'Die Offerte Zeile für Zeile lesen.',
  tableIntro: 'Bitten Sie um schriftliche Antworten und eine überarbeitete Offerte, wenn etwas offenbleibt. Diese Fragen machen Unterschiede sichtbar, ohne Anbieter mit erfundenen Punkten zu bewerten.',
  tableCaption: 'Prüfraster für Gespräche mit den anbietenden Fachbetrieben',
  columns: ['Was prüfen?', 'Warum ist das wichtig?', 'Was konkret fragen?'],
  rows: [
    { check: 'Anlagengrösse & Gesamtpreis', why: 'Unterschiedliche kWp, Optionen oder bereits abgezogene Förderungen können den Preisvergleich verzerren.', question: 'Welche installierte Leistung und welcher Gesamtpreis inklusive Mehrwertsteuer gelten vor Förderungen? Welche Positionen sind optional?' },
    { check: 'Module & Wechselrichter', why: 'Exakte Modelle, Anzahl und technische Daten zeigen, was geliefert wird und ob die Komponenten zur Planung passen.', question: 'Welche Hersteller und Modellbezeichnungen sind vorgesehen? Wie viele Module werden installiert und wie ist der Wechselrichter dimensioniert? Sind Ersatzmodelle nur nach meiner Zustimmung möglich?' },
    { check: 'Speicher & Betrieb', why: 'Nutzbare Kapazität, Ladeleistung, Kompatibilität und Betriebsbedingungen sind wichtiger als eine blosse Grössenangabe.', question: 'Welche Kapazität ist tatsächlich nutzbar? Welche Lade- und Entladeleistung gilt? Ist Ersatzstrom enthalten, und welche Wartungs- oder Softwarekosten entstehen?' },
    { check: 'Ertragsannahmen', why: 'Ausrichtung, Neigung, Verschattung und Verluste beeinflussen den Ertrag. Prognosen sind keine Garantie.', question: 'Auf welchen Wetterdaten, Dachannahmen und Verlusten basiert die Prognose? Welche Eigenverbrauchsquote und Stromtarife verwenden Sie in der Wirtschaftlichkeitsrechnung?' },
    { check: 'Dachprüfung & Montage', why: 'Zustand, Tragfähigkeit, Befestigung und Abdichtung müssen vor der Ausführung geklärt sein.', question: 'Wer prüft das Dach vor Ort und dokumentiert Zustand, Statikbedarf und Verschattung? Was passiert, wenn eine Dachsanierung nötig ist? Wer haftet bei Undichtigkeiten?' },
    { check: 'Fachbetrieb & Nachweise', why: 'Qualifikationen, passende Referenzen und Versicherung sind überprüfbare Anhaltspunkte für die Ausführung.', question: 'Wer führt Montage und Elektroarbeiten aus, auch bei Subunternehmen? Können Sie relevante Qualifikationen, nötige Bewilligungen, vergleichbare Referenzen und einen aktuellen Haftpflichtnachweis vorlegen?' },
    { check: 'Umfang & Ausschlüsse', why: 'Gerüst, Dacharbeiten, Zählerschrank oder Anschlusskosten können ausserhalb des genannten Preises liegen.', question: 'Sind Gerüst, Transport, Elektroanpassungen, Netzanschluss und Entsorgung enthalten? Wer erledigt Meldungen, Bewilligungen und Netzunterlagen? Welche Kosten sind ausdrücklich ausgeschlossen?' },
    { check: 'Termine & Zahlungen', why: 'Ein Liefertermin ist nicht automatisch ein Termin für eine betriebsbereite Anlage. Zahlungen sollten nachvollziehbaren Leistungen zugeordnet sein.', question: 'Welche Termine gelten für Montage, Netzanschluss und Inbetriebnahme? Welche Teilzahlungen werden bei welchen erreichten Meilensteinen fällig? Wie werden Verzögerungen und Zusatzarbeiten geregelt?' },
    { check: 'Abnahme & Betreuung', why: 'Dokumentation, Funktionsprüfung und eine erreichbare Ansprechperson sind auch nach der Montage wichtig.', question: 'Erhalte ich Prüfprotokolle, Anlagendokumentation und Zugang zur Überwachung? Wer bearbeitet Störungen und Garantiefälle, und welche Servicekosten gelten?' },
  ],
  warrantyTitle: 'Eine lange Garantie ist noch keine umfassende Absicherung.',
  warrantyIntro: 'Trennen Sie die Garantiearten. Entscheidend sind nicht nur die Dauer, sondern der Geltungsbereich, die Bedingungen und die zuständige Vertragspartei.',
  warranties: [
    { title: 'Ausführung & Montage', text: 'Klären Sie die vertragliche Verantwortung des Installateurs für Montage, Verkabelung und Dachabdichtung. Lassen Sie Fristen, Mängelmeldung und allfällige Subunternehmen schriftlich festhalten.' },
    { title: 'Produktgarantie', text: 'Sie betrifft je nach Hersteller Material- und Herstellungsfehler an Modulen, Wechselrichter oder Speicher. Prüfen Sie Ausschlüsse, Registrierung, Arbeitskosten, Transport und Austausch.' },
    { title: 'Leistungsgarantie', text: 'Sie betrifft üblicherweise die verbleibende Modulleistung unter definierten Prüfbedingungen. Sie garantiert weder den Ertrag Ihres Dachs noch Ihre Stromersparnis.' },
    { title: 'Speicherbedingungen', text: 'Prüfen Sie zugesicherte Restkapazität, zulässige Zyklen oder Energiedurchsatz und Betriebsbedingungen. Diese können die Deckung begrenzen, auch wenn eine lange Laufzeit genannt wird.' },
  ],
  warrantyNote: 'Die zentrale Frage: An wen wende ich mich im Schadenfall – und wer bezahlt Diagnose, Demontage, Transport und erneute Montage? Lassen Sie sich die Antwort samt Garantieunterlagen geben.',
  warningTitle: 'Wann Sie besser noch nicht unterschreiben.',
  warningIntro: 'Ein offener Punkt ist nicht automatisch ein schlechter Anbieter. Bleibt er trotz Nachfrage unklar, fehlt aber eine belastbare Entscheidungsgrundlage.',
  warnings: [
    'Ein angeblicher Sonderpreis gilt nur bei sofortiger Unterschrift, obwohl Dachprüfung oder Leistungsumfang noch offen sind.',
    'Der Preis wird nur nach erwarteten Förderungen genannt; Gesamtpreis, Voraussetzungen oder Auszahlungsrisiken fehlen.',
    'Hohe Erträge oder Einsparungen werden als sicher dargestellt, ohne nachvollziehbare Annahmen zu Verschattung, Verbrauch und Tarifen.',
    'Es fehlen konkrete Komponenten, schriftliche Ausschlüsse oder eine klare Regelung für Modelländerungen und Zusatzarbeiten.',
    'Eine hohe Vorauszahlung wird verlangt, ohne verständliche Zahlungsmeilensteine; Nachweise und verantwortliche Ansprechpartner bleiben unklar.',
  ],
  checklistTitle: 'Was vor Ihrer Unterschrift geklärt sein sollte.',
  checklistIntro: 'Nutzen Sie diese Liste im Gespräch. Nicht alles muss dieselbe Lösung haben – aber jede Antwort sollte für Sie verständlich und schriftlich festgehalten sein.',
  checklist: [
    'Die Offerten haben vergleichbare kWp und denselben Leistungsumfang.',
    'Der Gesamtpreis inklusive Mehrwertsteuer und mögliche Zusatzkosten sind klar.',
    'Förderannahmen, Antragstellung und Auszahlungsrisiken sind separat geklärt.',
    'Module, Wechselrichter und gegebenenfalls Speicher sind genau bezeichnet.',
    'Dachprüfung und Ertragsannahmen sind dokumentiert.',
    'Qualifikationen, Referenzen und Versicherungsnachweis wurden geprüft.',
    'Garantiebedingungen, zuständige Parteien und Folgekosten sind bekannt.',
    'Termine, Zahlungsmeilensteine und Umgang mit Änderungen sind vereinbart.',
    'Abnahme, Dokumentation und Kontakt für den späteren Service sind geregelt.',
    'Alle offenen Fragen sind vor Vertragsabschluss schriftlich beantwortet.',
  ],
  checklistHint: 'Die Häkchen sind eine persönliche Lesehilfe und werden nach dem Neuladen nicht gespeichert.',
  ctaTitle: 'Bereit für einen fundierten Vergleich?',
  ctaText: 'Erfassen Sie Ihr Projekt über das Anfrageformular. Nutzen Sie diesen Ratgeber, um die eingehenden Offerten mit den Fachbetrieben zu besprechen.',
  quoteAction: 'Solarofferten anfordern',
  processAction: 'So funktioniert der Vergleich',
  disclaimer: 'PvPro.ch vermittelt Anfragen und ist kein Installationsbetrieb. Sie wählen selbst; den Installationsvertrag schliessen Sie direkt mit dem Fachbetrieb ab. Dieser Ratgeber ersetzt keine technische Prüfung Ihres Gebäudes oder individuelle Vertragsberatung.',
};
