import type { GuideContent } from './types';

export const en: GuideContent = {
  metaTitle: 'How to choose the right solar installer',
  metaDescription: 'Compare solar quotes with confidence: scope, equipment, roof assessment, warranties and contract terms. Practical questions and a checklist before you sign.',
  home: 'Home',
  breadcrumb: 'Choosing a solar installer',
  eyebrow: 'PvPro.ch · Decision guide',
  title: 'The best quote is not simply the cheapest.',
  intro: 'The right solar installer explains more than the price. They show what is possible on your roof, what the contract includes and who will take responsibility afterwards. Here is how to compare proposals before deciding.',
  noteTitle: 'Understand first. Sign later.',
  noteText: 'Not an installer ranking, but practical checks for your own project. A useful comparison starts with the same assumptions.',
  navLabel: 'In this guide',
  sections: ['Comparison basis', 'Reviewing quotes', 'Understanding warranties', 'Warning signs', 'Before you sign'],
  basisTitle: 'Same capacity. Same scope. Then compare the price.',
  basisParagraphs: [
    'Give each installer the same project information: roof area, electricity use, any planned heat pump or charging point, and whether you want a battery. Rated capacity in kWp describes power under standard test conditions, not actual annual electricity production.',
    'Compare the total installed capacity and the same scope of supply. A proposal including a battery, scaffolding and electrical work is not directly comparable with one excluding them. Ask for missing items to be added and optional work to be priced separately.',
    'Compare the total price including VAT before any subsidies are deducted. Keep grants and potential tax deductions in a separate calculation: eligibility, amounts and payment can depend on your project, canton, municipality and the authority involved. Establish who submits applications and who bears the cost if funding does not materialise.',
  ],
  principle: 'Comparison basis: same kWp + same scope + total price before subsidies',
  tableTitle: 'Read the quote line by line.',
  tableIntro: 'Ask for written answers and a revised proposal where anything remains unclear. These questions reveal meaningful differences without assigning invented scores to installers.',
  tableCaption: 'A comparison framework for discussions with installation companies',
  columns: ['What to check', 'Why it matters', 'What to ask'],
  rows: [
    { check: 'System size & total price', why: 'Different capacities, options or subsidies already deducted can distort a price comparison.', question: 'What installed capacity and total price including VAT apply before subsidies? Which items are optional?' },
    { check: 'Panels & inverter', why: 'Exact models, quantities and specifications show what will be supplied and whether the equipment fits the design.', question: 'Which manufacturers and models are specified? How many panels will be installed and how is the inverter sized? Will substitutions require my approval?' },
    { check: 'Battery & operation', why: 'Usable capacity, power, compatibility and operating conditions matter more than a headline capacity.', question: 'How much capacity is actually usable? What are the charging and discharging power ratings? Is backup power included, and what maintenance or software costs apply?' },
    { check: 'Yield assumptions', why: 'Orientation, roof pitch, shading and losses affect output. A forecast is not a guarantee.', question: 'Which weather data, roof assumptions and losses underpin the forecast? What self-consumption rate and electricity tariffs are used in the financial calculation?' },
    { check: 'Roof assessment & mounting', why: 'Roof condition, load-bearing capacity, fixings and weatherproofing need to be established before installation.', question: 'Who inspects the roof on site and records its condition, any structural assessment needed and shading? What happens if roof repairs are required? Who is responsible for leaks?' },
    { check: 'Installer & evidence', why: 'Qualifications, relevant references and insurance provide verifiable information about the people doing the work.', question: 'Who carries out mounting and electrical work, including subcontractors? Can you provide relevant qualifications, required authorisations, comparable references and current liability insurance evidence?' },
    { check: 'Scope & exclusions', why: 'Scaffolding, roof work, distribution-board upgrades or connection charges may sit outside the stated price.', question: 'Are scaffolding, transport, electrical upgrades, grid connection and waste removal included? Who handles notifications, permits and grid paperwork? Which costs are explicitly excluded?' },
    { check: 'Dates & payments', why: 'A delivery date is not necessarily a date for an operational system. Payments should correspond to identifiable work.', question: 'What dates apply to installation, grid connection and commissioning? Which instalments fall due at which completed milestones? How are delays and additional work handled?' },
    { check: 'Handover & support', why: 'Documentation, functional checks and a reachable contact matter after installation too.', question: 'Will I receive test reports, system documentation and monitoring access? Who handles faults and warranty claims, and what service charges apply?' },
  ],
  warrantyTitle: 'A long warranty does not mean everything is covered.',
  warrantyIntro: 'Separate the different types of cover. Duration matters, but so do scope, conditions and the party responsible under the contract.',
  warranties: [
    { title: 'Workmanship & installation', text: 'Clarify the installer’s contractual responsibility for mounting, wiring and roof weatherproofing. Get the time limits, defect-reporting process and any subcontracting arrangements in writing.' },
    { title: 'Product warranty', text: 'Depending on the manufacturer, this covers material and manufacturing defects in panels, inverters or batteries. Check exclusions, registration, labour, transport and replacement costs.' },
    { title: 'Performance warranty', text: 'This usually concerns remaining panel power under defined test conditions. It does not guarantee your roof’s annual production or your electricity savings.' },
    { title: 'Battery conditions', text: 'Check the stated remaining capacity, permitted cycles or energy throughput and operating conditions. These may limit cover even when a long warranty period is advertised.' },
  ],
  warrantyNote: 'The key question: who do I contact if something fails, and who pays for diagnosis, removal, transport and reinstallation? Ask for the answer together with the warranty documents.',
  warningTitle: 'When it is better not to sign yet.',
  warningIntro: 'An unanswered question does not automatically mean a poor installer. But if it stays unanswered after you ask, you lack a sound basis for deciding.',
  warnings: [
    'A supposed special price requires an immediate signature while the roof assessment or scope is still unresolved.',
    'Only a price after expected subsidies is shown; the total price, eligibility conditions or payment risks are missing.',
    'High output or savings are presented as certain, without transparent assumptions about shading, consumption and tariffs.',
    'The proposal lacks named components, written exclusions or clear rules for substitutions and additional work.',
    'A large advance payment is requested without understandable payment milestones, while evidence and accountable contacts remain unclear.',
  ],
  checklistTitle: 'What should be settled before you sign.',
  checklistIntro: 'Use this list during your discussions. There is no single answer for every project, but each answer should be understandable and recorded in writing.',
  checklist: [
    'The quotes have comparable kWp and the same scope of work.',
    'The total price including VAT and possible additional costs are clear.',
    'Subsidy assumptions, applications and payment risks are addressed separately.',
    'Panels, inverter and any battery are identified by exact model.',
    'The roof assessment and yield assumptions are documented.',
    'Qualifications, references and insurance evidence have been checked.',
    'Warranty conditions, responsible parties and associated costs are understood.',
    'Dates, payment milestones and arrangements for changes are agreed.',
    'Handover, documentation and a future service contact are established.',
    'All outstanding questions have written answers before the contract is signed.',
  ],
  checklistHint: 'The tick boxes are a personal reading aid. Your selections are not saved when you reload the page.',
  ctaTitle: 'Ready for a well-informed comparison?',
  ctaText: 'Describe your project using the request form. Use this guide to discuss the quotes you receive with the installation companies.',
  quoteAction: 'Request solar quotes',
  processAction: 'How comparison works',
  disclaimer: 'PvPro.ch connects enquiries with installers; it is not an installation company. You make the choice and agree the installation contract directly with the installer. This guide does not replace a technical assessment of your building or individual advice on your contract.',
};
