import type { GuideContent } from './types';

export const fr: GuideContent = {
  metaTitle: 'Choisir le bon installateur solaire',
  metaDescription: 'Comparez les offres solaires : prestations, équipements, toiture, garanties et contrat. Des questions concrètes et une liste de vérification avant de signer.',
  home: 'Accueil',
  breadcrumb: 'Choisir un installateur solaire',
  eyebrow: 'PvPro.ch · Guide de décision',
  title: 'La meilleure offre n’est pas simplement la moins chère.',
  intro: 'Le bon installateur solaire ne se contente pas d’expliquer son prix. Il précise ce qui est possible sur votre toit, ce que comprend le contrat et qui sera responsable par la suite. Voici comment comparer les propositions avant de décider.',
  noteTitle: 'Comprendre d’abord. Signer ensuite.',
  noteText: 'Pas de classement d’installateurs : des points concrets à vérifier pour votre projet. Une comparaison utile commence avec les mêmes hypothèses.',
  navLabel: 'Dans ce guide',
  sections: ['Base de comparaison', 'Examiner les offres', 'Comprendre les garanties', 'Signaux d’alerte', 'Avant de signer'],
  basisTitle: 'Même puissance. Mêmes prestations. Puis comparer le prix.',
  basisParagraphs: [
    'Transmettez les mêmes informations à chaque installateur : surface de toiture, consommation électrique, pompe à chaleur ou borne de recharge prévue et souhait d’une batterie. La puissance nominale en kWp décrit la puissance dans des conditions d’essai standardisées, pas la production annuelle réelle.',
    'Comparez la puissance totale installée et un périmètre de prestations identique. Une offre comprenant une batterie, un échafaudage et les travaux électriques n’est pas directement comparable à une offre qui les exclut. Faites compléter les postes manquants et chiffrer les options séparément.',
    'Comparez le prix total, TVA comprise, avant déduction des aides. Les subventions et les éventuelles déductions fiscales doivent faire l’objet d’un calcul distinct : le droit aux aides, leur montant et leur versement peuvent dépendre du projet, du canton, de la commune et de l’organisme compétent. Clarifiez qui dépose les demandes et qui assume le coût si une aide n’est pas versée.',
  ],
  principle: 'Base de comparaison : mêmes kWp + mêmes prestations + prix total avant les aides',
  tableTitle: 'Lire l’offre ligne par ligne.',
  tableIntro: 'Demandez des réponses écrites et une offre révisée si certains points restent flous. Ces questions révèlent les différences utiles, sans attribuer de notes inventées aux installateurs.',
  tableCaption: 'Une grille de comparaison pour vos échanges avec les entreprises',
  columns: ['Que vérifier ?', 'Pourquoi est-ce important ?', 'Que demander concrètement ?'],
  rows: [
    { check: 'Puissance et prix total', why: 'Des puissances différentes, des options ou des aides déjà déduites peuvent fausser la comparaison des prix.', question: 'Quelle puissance installée et quel prix total, TVA comprise, sont prévus avant les aides ? Quels postes sont optionnels ?' },
    { check: 'Panneaux et onduleur', why: 'Les modèles exacts, les quantités et les fiches techniques permettent de savoir ce qui sera livré et si le matériel convient au projet.', question: 'Quels fabricants et modèles sont prévus ? Combien de panneaux seront posés et comment l’onduleur est-il dimensionné ? Tout remplacement de modèle nécessite-t-il mon accord ?' },
    { check: 'Batterie et fonctionnement', why: 'La capacité utile, la puissance, la compatibilité et les conditions d’utilisation comptent davantage qu’une capacité affichée seule.', question: 'Quelle capacité est réellement utilisable ? Quelles sont les puissances de charge et de décharge ? L’alimentation de secours est-elle incluse ? Quels frais d’entretien ou de logiciel sont prévus ?' },
    { check: 'Hypothèses de production', why: 'L’orientation, la pente, l’ombrage et les pertes influencent la production. Une prévision n’est pas une garantie.', question: 'Sur quelles données météo, hypothèses de toiture et pertes repose la prévision ? Quels taux d’autoconsommation et tarifs d’électricité utilisez-vous pour le calcul économique ?' },
    { check: 'État du toit et fixation', why: 'L’état de la toiture, sa capacité portante, les fixations et l’étanchéité doivent être clarifiés avant les travaux.', question: 'Qui inspecte le toit sur place et documente son état, le besoin d’une étude statique et l’ombrage ? Que se passe-t-il si une réfection est nécessaire ? Qui répond des infiltrations ?' },
    { check: 'Entreprise et justificatifs', why: 'Les qualifications, des références pertinentes et l’assurance fournissent des éléments vérifiables sur les intervenants.', question: 'Qui réalise la pose et les travaux électriques, y compris en sous-traitance ? Pouvez-vous fournir les qualifications pertinentes, les autorisations nécessaires, des références comparables et une attestation d’assurance responsabilité civile à jour ?' },
    { check: 'Prestations et exclusions', why: 'L’échafaudage, les travaux de toiture, le tableau électrique ou les frais de raccordement peuvent être exclus du prix annoncé.', question: 'L’échafaudage, le transport, les adaptations électriques, le raccordement et l’évacuation des déchets sont-ils inclus ? Qui gère les annonces, les autorisations et les documents pour le réseau ? Quels frais sont expressément exclus ?' },
    { check: 'Délais et paiements', why: 'Une date de livraison n’est pas forcément une date de mise en service. Les paiements doivent correspondre à des prestations identifiables.', question: 'Quelles dates sont prévues pour la pose, le raccordement et la mise en service ? Quels acomptes sont dus à quelles étapes réalisées ? Comment sont traités les retards et les travaux supplémentaires ?' },
    { check: 'Réception et suivi', why: 'La documentation, les essais et un interlocuteur joignable restent importants après la pose.', question: 'Recevrai-je les procès-verbaux de contrôle, la documentation et l’accès au suivi de production ? Qui traite les pannes et les demandes de garantie ? Quels frais de service s’appliquent ?' },
  ],
  warrantyTitle: 'Une longue garantie ne signifie pas que tout est couvert.',
  warrantyIntro: 'Distinguez les types de garanties. La durée compte, mais aussi la couverture, les conditions et la partie responsable au titre du contrat.',
  warranties: [
    { title: 'Travaux et pose', text: 'Clarifiez la responsabilité contractuelle de l’installateur pour les fixations, le câblage et l’étanchéité. Faites préciser par écrit les délais, la procédure de signalement des défauts et le recours éventuel à des sous-traitants.' },
    { title: 'Garantie produit', text: 'Selon le fabricant, elle couvre les défauts de matériau et de fabrication des panneaux, de l’onduleur ou de la batterie. Vérifiez les exclusions, l’enregistrement, la main-d’œuvre, le transport et les frais de remplacement.' },
    { title: 'Garantie de performance', text: 'Elle concerne généralement la puissance restante des panneaux dans des conditions d’essai définies. Elle ne garantit ni la production annuelle de votre toiture ni vos économies d’électricité.' },
    { title: 'Conditions de la batterie', text: 'Vérifiez la capacité résiduelle annoncée, les cycles autorisés ou l’énergie cumulée et les conditions de fonctionnement. Ces critères peuvent limiter la couverture malgré une longue durée affichée.' },
  ],
  warrantyNote: 'La question essentielle : qui contacter en cas de panne, et qui paie le diagnostic, la dépose, le transport et la repose ? Demandez la réponse avec les documents de garantie.',
  warningTitle: 'Quand vaut-il mieux attendre avant de signer ?',
  warningIntro: 'Un point en suspens ne signifie pas automatiquement que l’installateur est mauvais. Mais s’il reste sans réponse après votre demande, vous ne disposez pas d’une base solide pour décider.',
  warnings: [
    'Un prétendu prix spécial exige une signature immédiate alors que l’examen du toit ou les prestations restent à préciser.',
    'Seul le prix après les aides attendues est présenté ; le prix total, les conditions d’éligibilité ou les risques de versement manquent.',
    'Une production ou des économies élevées sont présentées comme certaines, sans hypothèses transparentes sur l’ombrage, la consommation et les tarifs.',
    'L’offre ne précise pas les composants, les exclusions écrites ou les règles de remplacement de modèles et de travaux supplémentaires.',
    'Une avance importante est demandée sans étapes de paiement compréhensibles, tandis que les justificatifs et les interlocuteurs responsables restent flous.',
  ],
  checklistTitle: 'Ce qui doit être clarifié avant votre signature.',
  checklistIntro: 'Utilisez cette liste pendant vos échanges. Il n’existe pas une réponse unique pour tous les projets, mais chaque réponse doit être compréhensible et consignée par écrit.',
  checklist: [
    'Les offres portent sur des kWp comparables et les mêmes prestations.',
    'Le prix total, TVA comprise, et les frais supplémentaires possibles sont clairs.',
    'Les hypothèses d’aide, les demandes et les risques de versement sont traités séparément.',
    'Les panneaux, l’onduleur et l’éventuelle batterie sont identifiés précisément.',
    'L’examen de la toiture et les hypothèses de production sont documentés.',
    'Les qualifications, les références et l’attestation d’assurance ont été vérifiées.',
    'Les conditions de garantie, les parties responsables et les frais associés sont connus.',
    'Les dates, les étapes de paiement et le traitement des modifications sont convenus.',
    'La réception, la documentation et le contact pour le suivi sont définis.',
    'Toutes les questions en suspens ont reçu une réponse écrite avant la signature.',
  ],
  checklistHint: 'Les cases à cocher sont une aide personnelle à la lecture. Les sélections ne sont pas conservées après le rechargement de la page.',
  ctaTitle: 'Prêt à comparer en connaissance de cause ?',
  ctaText: 'Décrivez votre projet dans le formulaire de demande. Utilisez ce guide pour discuter des offres reçues avec les entreprises d’installation.',
  quoteAction: 'Demander des offres solaires',
  processAction: 'Comment fonctionne la comparaison',
  disclaimer: 'PvPro.ch transmet les demandes aux installateurs et n’est pas une entreprise d’installation. Vous faites votre choix et concluez le contrat directement avec l’entreprise retenue. Ce guide ne remplace pas un examen technique de votre bâtiment ni un conseil individuel sur votre contrat.',
};
