import type { GuideContent } from './types';

export const it: GuideContent = {
  metaTitle: 'Come scegliere l’installatore solare giusto',
  metaDescription: 'Confronta i preventivi solari: prestazioni, componenti, tetto, garanzie e contratto. Domande concrete e una lista di controllo prima della firma.',
  home: 'Home',
  breadcrumb: 'Scegliere un installatore solare',
  eyebrow: 'PvPro.ch · Guida alla scelta',
  title: 'Il preventivo migliore non è semplicemente il più economico.',
  intro: 'L’installatore solare giusto non spiega soltanto il prezzo. Chiarisce cosa è possibile sul tuo tetto, cosa comprende il contratto e chi sarà responsabile in seguito. Ecco come confrontare le proposte prima di decidere.',
  noteTitle: 'Prima capire. Poi firmare.',
  noteText: 'Non una classifica di installatori, ma verifiche concrete per il tuo progetto. Un confronto utile parte dagli stessi presupposti.',
  navLabel: 'In questa guida',
  sections: ['Base di confronto', 'Esaminare i preventivi', 'Capire le garanzie', 'Segnali di allarme', 'Prima della firma'],
  basisTitle: 'Stessa potenza. Stesse prestazioni. Poi confronta il prezzo.',
  basisParagraphs: [
    'Fornisci a ogni installatore le stesse informazioni: superficie del tetto, consumo elettrico, eventuale pompa di calore o stazione di ricarica prevista e interesse per una batteria. La potenza nominale in kWp descrive la potenza in condizioni di prova standardizzate, non la produzione annuale effettiva.',
    'Confronta la potenza totale installata e lo stesso insieme di prestazioni. Un preventivo con batteria, ponteggio e lavori elettrici non è direttamente confrontabile con uno che li esclude. Chiedi di integrare le voci mancanti e di indicare separatamente i costi delle opzioni.',
    'Confronta il prezzo totale IVA inclusa, prima di sottrarre gli incentivi. I contributi e le possibili deduzioni fiscali vanno considerati in un calcolo separato: diritto, importo e versamento possono dipendere dal progetto, dal cantone, dal comune e dall’ente competente. Chiarisci chi presenta le domande e chi sostiene il costo se un contributo non viene versato.',
  ],
  principle: 'Base di confronto: stessi kWp + stesse prestazioni + prezzo totale prima degli incentivi',
  tableTitle: 'Leggi il preventivo voce per voce.',
  tableIntro: 'Chiedi risposte scritte e un preventivo aggiornato se qualcosa resta poco chiaro. Queste domande fanno emergere differenze utili senza assegnare punteggi inventati agli installatori.',
  tableCaption: 'Una griglia di confronto per parlare con le imprese di installazione',
  columns: ['Cosa verificare', 'Perché è importante', 'Cosa chiedere'],
  rows: [
    { check: 'Potenza e prezzo totale', why: 'Potenze diverse, opzioni o incentivi già sottratti possono falsare il confronto dei prezzi.', question: 'Quali sono la potenza installata e il prezzo totale IVA inclusa prima degli incentivi? Quali voci sono facoltative?' },
    { check: 'Moduli e inverter', why: 'Modelli esatti, quantità e schede tecniche mostrano cosa verrà fornito e se i componenti sono adatti al progetto.', question: 'Quali produttori e modelli sono previsti? Quanti moduli saranno installati e come è dimensionato l’inverter? Le sostituzioni di modello richiedono il mio consenso?' },
    { check: 'Batteria e funzionamento', why: 'Capacità utilizzabile, potenza, compatibilità e condizioni operative contano più della sola capacità dichiarata.', question: 'Quanta capacità è effettivamente utilizzabile? Quali sono le potenze di carica e scarica? L’alimentazione di emergenza è inclusa? Quali costi di manutenzione o software sono previsti?' },
    { check: 'Ipotesi di produzione', why: 'Orientamento, inclinazione, ombreggiamento e perdite influenzano la produzione. Una previsione non è una garanzia.', question: 'Su quali dati meteo, ipotesi sul tetto e perdite si basa la previsione? Quali quote di autoconsumo e tariffe elettriche usate nel calcolo economico?' },
    { check: 'Valutazione del tetto e fissaggi', why: 'Stato del tetto, capacità portante, fissaggi e impermeabilizzazione devono essere chiariti prima dei lavori.', question: 'Chi esamina il tetto sul posto e documenta condizioni, necessità di una verifica statica e ombreggiamento? Cosa succede se serve un risanamento? Chi risponde delle infiltrazioni?' },
    { check: 'Impresa e documenti', why: 'Qualifiche, referenze pertinenti e assicurazione offrono elementi verificabili su chi esegue i lavori.', question: 'Chi esegue il montaggio e i lavori elettrici, inclusi eventuali subappaltatori? Potete fornire qualifiche pertinenti, autorizzazioni necessarie, referenze comparabili e un’attestazione aggiornata di responsabilità civile?' },
    { check: 'Prestazioni ed esclusioni', why: 'Ponteggio, lavori sul tetto, quadro elettrico o costi di allacciamento possono essere esclusi dal prezzo indicato.', question: 'Sono inclusi ponteggio, trasporto, adeguamenti elettrici, allacciamento e smaltimento? Chi gestisce notifiche, autorizzazioni e documenti per la rete? Quali costi sono espressamente esclusi?' },
    { check: 'Date e pagamenti', why: 'Una data di consegna non coincide necessariamente con la disponibilità di un impianto operativo. I pagamenti devono corrispondere a prestazioni identificabili.', question: 'Quali date sono previste per montaggio, allacciamento e messa in servizio? Quali rate sono dovute a quali traguardi completati? Come vengono gestiti ritardi e lavori aggiuntivi?' },
    { check: 'Collaudo e assistenza', why: 'Documentazione, verifiche funzionali e un referente raggiungibile sono importanti anche dopo il montaggio.', question: 'Riceverò verbali di verifica, documentazione dell’impianto e accesso al monitoraggio? Chi gestisce guasti e richieste di garanzia? Quali costi di assistenza si applicano?' },
  ],
  warrantyTitle: 'Una garanzia lunga non significa che tutto sia coperto.',
  warrantyIntro: 'Distingui i tipi di garanzia. Non conta soltanto la durata, ma anche la copertura, le condizioni e il soggetto responsabile secondo il contratto.',
  warranties: [
    { title: 'Lavori e montaggio', text: 'Chiarisci la responsabilità contrattuale dell’installatore per fissaggi, cablaggio e impermeabilizzazione del tetto. Fai mettere per iscritto termini, procedura di segnalazione dei difetti ed eventuali subappalti.' },
    { title: 'Garanzia del prodotto', text: 'A seconda del produttore, copre difetti di materiale e fabbricazione di moduli, inverter o batteria. Verifica esclusioni, registrazione, manodopera, trasporto e costi di sostituzione.' },
    { title: 'Garanzia di prestazione', text: 'Di solito riguarda la potenza residua dei moduli in condizioni di prova definite. Non garantisce la produzione annuale del tuo tetto né il risparmio sulla bolletta.' },
    { title: 'Condizioni della batteria', text: 'Verifica capacità residua dichiarata, cicli consentiti o energia complessiva e condizioni operative. Questi criteri possono limitare la copertura anche quando la durata pubblicizzata è lunga.' },
  ],
  warrantyNote: 'La domanda centrale: chi contatto in caso di guasto e chi paga diagnosi, smontaggio, trasporto e rimontaggio? Chiedi la risposta insieme ai documenti di garanzia.',
  warningTitle: 'Quando è meglio aspettare prima di firmare.',
  warningIntro: 'Un punto aperto non significa automaticamente che l’installatore sia poco affidabile. Ma se resta senza risposta dopo una richiesta di chiarimento, manca una base solida per decidere.',
  warnings: [
    'Un presunto prezzo speciale richiede la firma immediata mentre la valutazione del tetto o le prestazioni sono ancora da definire.',
    'Viene mostrato solo il prezzo dopo gli incentivi attesi; mancano prezzo totale, requisiti o rischi legati al versamento.',
    'Produzioni o risparmi elevati vengono presentati come certi, senza ipotesi trasparenti su ombreggiamento, consumi e tariffe.',
    'Il preventivo non specifica componenti, esclusioni scritte o regole chiare per sostituzioni di modello e lavori aggiuntivi.',
    'Viene richiesto un anticipo elevato senza traguardi di pagamento comprensibili, mentre documenti e referenti responsabili restano poco chiari.',
  ],
  checklistTitle: 'Cosa chiarire prima della tua firma.',
  checklistIntro: 'Usa questa lista durante i colloqui. Non esiste una risposta unica per ogni progetto, ma ogni risposta deve essere comprensibile e messa per iscritto.',
  checklist: [
    'I preventivi hanno kWp comparabili e le stesse prestazioni.',
    'Il prezzo totale IVA inclusa e i possibili costi aggiuntivi sono chiari.',
    'Le ipotesi sugli incentivi, le domande e i rischi di versamento sono trattati separatamente.',
    'Moduli, inverter ed eventuale batteria sono identificati con precisione.',
    'La valutazione del tetto e le ipotesi di produzione sono documentate.',
    'Qualifiche, referenze e attestazione assicurativa sono state verificate.',
    'Condizioni di garanzia, soggetti responsabili e costi associati sono noti.',
    'Date, traguardi di pagamento e gestione delle modifiche sono concordati.',
    'Collaudo, documentazione e contatto per l’assistenza futura sono definiti.',
    'Tutte le domande aperte hanno una risposta scritta prima della firma.',
  ],
  checklistHint: 'Le caselle sono un aiuto personale alla lettura. Le selezioni non vengono conservate dopo il ricaricamento della pagina.',
  ctaTitle: 'Pronto per un confronto consapevole?',
  ctaText: 'Descrivi il tuo progetto nel modulo di richiesta. Usa questa guida per discutere i preventivi ricevuti con le imprese di installazione.',
  quoteAction: 'Richiedi preventivi solari',
  processAction: 'Come funziona il confronto',
  disclaimer: 'PvPro.ch inoltra le richieste agli installatori e non è un’impresa di installazione. Scegli tu e stipuli il contratto direttamente con l’impresa selezionata. Questa guida non sostituisce una valutazione tecnica del tuo edificio né una consulenza individuale sul contratto.',
};
