// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/how-it-works/BoldSplit.tsx": () => import("../components/mockups/how-it-works/BoldSplit.tsx"),
  "./components/mockups/how-it-works/Cinematic.tsx": () => import("../components/mockups/how-it-works/Cinematic.tsx"),
  "./components/mockups/how-it-works/Timeline.tsx": () => import("../components/mockups/how-it-works/Timeline.tsx")
};
