import type { CantonGuide } from '../types';

export const guide: CantonGuide = {
  id: 'basel', path: '/it/fotovoltaico-basilea', canton: 'Basilea Città / Basilea Campagna',
  title: 'Fotovoltaico a Basilea 2026: Città o Campagna | PvPro.ch',
  description: 'Fotovoltaico a Basilea: incentivi, permessi e obbligo solare differiscono nettamente tra Basilea Città e Basilea Campagna.',
  h1: 'Fotovoltaico a Basilea: Basilea Città o Basilea Campagna?',
  intro: ['Gli incentivi e le regole applicabili dipendono dal lato del confine cantonale in cui si trova il vostro immobile.'],
  quickFacts: [
    { value: 'fino a CHF 100/m²', label: 'Tetto: risanamento insieme al fotovoltaico', sourceIds: ['bs-solarkraftwerk'] },
    { value: 'fino a CHF 140/m²', label: 'Facciata: risanamento insieme al fotovoltaico', sourceIds: ['bs-solarkraftwerk'] },
    { value: 'CHF 40/m²', label: 'Tetto: bonus fotovoltaico solo con isolamento termico', sourceIds: ['bl-energie'] },
    { value: 'CHF 120/m²', label: 'Facciata: bonus fotovoltaico solo con isolamento termico', sourceIds: ['bl-energie'] },
  ],
  sections: [
    { id: 'vergleich', title: 'Basilea Città e Basilea Campagna: cinque differenze', paragraphs: [
      'È anzitutto l’ubicazione a determinare la regola applicabile. Basilea Città e Basilea Campagna hanno incentivi e procedure differenti.',
      'Gli importi non sono una rimunerazione forfettaria per ogni impianto fotovoltaico. A Basilea Città rientrano in «Solarkraftwerk Basel», a Basilea Campagna in una domanda per l’isolamento termico. Verificate separatamente l’incentivo federale tramite Pronovo, ossia la rimunerazione unica (RU).',
    ], sourceIds: ['bs-solarkraftwerk', 'bl-energie'], module: { kind: 'comparison', title: 'Il confine cantonale è determinante', intro: 'Stessa tecnologia, ma regole diverse a seconda del Cantone:', columns: ['Basilea Città', 'Basilea Campagna'], items: [], rows: [
      { label: 'Incentivo fotovoltaico', left: 'Verificare separatamente l’incentivo federale. Il contributo cantonale supplementare vale solo per un risanamento energetico con fotovoltaico.', right: 'Verificare separatamente l’incentivo federale. Il bonus cantonale vale solo con un isolamento termico ammesso agli incentivi.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
      { label: 'Risanamento + fotovoltaico', left: 'Tetto: CHF 50/m², CHF 100/m² sulla superficie dei moduli con fotovoltaico. Facciata: CHF 70/m², CHF 140/m² con fotovoltaico.', right: 'Bonus fotovoltaico: CHF 40/m² sul tetto o CHF 120/m² in facciata. Solo con isolamento termico.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
      { label: 'Permesso', left: 'Per impianti ben integrati può bastare una notifica. Le zone protette e i monumenti culturali possono richiedere una licenza.', right: 'Nelle zone edificabili e agricole in genere basta la notifica, almeno 30 giorni prima dei lavori. Le zone protette richiedono una licenza.', sourceIds: ['bs-permit', 'bl-permit'] },
      { label: 'Obbligo solare', left: 'L’offensiva solare è soltanto un progetto. Sono previsti un obbligo fotovoltaico e 15 anni di transizione per gli edifici esistenti.', right: 'L’iniziativa energetica «Sfruttare il potenziale» è stata respinta l’8 marzo 2026 con il 67,6% di no. Non vi è quindi alcun nuovo obbligo generale di adeguamento.', sourceIds: ['bs-offensive', 'bl-abstimmung'] },
      { label: 'Particolarità 2026', left: 'L’azione incentiva solo grandi impianti sul tetto. Occorre coprire il 90% della superficie ben o molto ben idonea oppure del potenziale tecnicamente realizzabile.', right: 'Nuove domande sono possibili dal 12 gennaio 2026. Il massimo è di CHF 100’000 per domanda e del 50% dei costi ammessi per misura.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    ] } },
    { id: 'pflichten', title: 'Obbligo solare: che cosa vale oggi?', paragraphs: [
      'No. L’offensiva solare di Basilea Città non è ancora diritto vigente e Basilea Campagna non ha un nuovo obbligo generale di adeguamento.',
      'A Basilea Città il governo cantonale ha trasmesso al parlamento cantonale una proposta rielaborata. Sono previsti un obbligo per le superfici ben idonee e 15 anni di transizione per gli edifici esistenti.',
      'Finché il progetto non sarà approvato ed entrato in vigore, non sussiste alcun obbligo d’installazione. Il progetto indica per tetti e facciate un potenziale pari a circa il 40% dell’attuale consumo cantonale di elettricità.',
      'Non è né una promessa di rendimento né una quota d’incentivo. A Basilea Campagna l’iniziativa legislativa «Sfruttare il potenziale – garantire l’approvvigionamento» (iniziativa solare) è stata respinta l’8 marzo 2026 con il 67,6% di no.',
    ], bullets: ['Basilea Città: offensiva solare prevista, transizione di 15 anni proposta — non ancora diritto vigente.', 'Basilea Campagna: 67,6% di no all’iniziativa energetica — nessun nuovo obbligo generale di adeguamento.', 'Per il vostro progetto contano oggi ubicazione e procedura edilizia vigente, non un annuncio politico.'], sourceIds: ['bs-offensive', 'bl-abstimmung', 'bs-permit', 'bl-permit'], notice: { title: 'Previsto — non ancora diritto vigente', text: 'Fino a quando una decisione non produce effetti giuridici, valgono le regole attuali. Verificate idoneità, zona e protezione dell’edificio e avviate la procedura adatta.', status: 'future' } },
    { id: 'foerderung', title: 'Quali incentivi valgono nel 2026?', paragraphs: [
      'Il confine cantonale determina l’incentivo. Basilea Città paga solo in caso di risanamento energetico con fotovoltaico; Basilea Campagna solo per un isolamento termico che soddisfa le condizioni.',
      'A Basilea Città, nel 2026 «Solarkraftwerk Basel» prevede CHF 50 per m² di tetto, oppure CHF 100 sulla superficie dei moduli fotovoltaici. Per la facciata gli importi sono rispettivamente CHF 70 e CHF 140.',
      'Il raddoppio vale per la superficie dei moduli fotovoltaici, non automaticamente per tutto l’involucro. Un impianto sul tetto deve di regola coprire con il fotovoltaico il 90% della superficie idonea.',
      'Si intende la superficie indicata come ben o molto ben idonea nella mappa delle superfici adatte (catasto solare), oppure il potenziale tecnicamente realizzabile.',
      'La domanda deve essere presentata sul portale prima dell’inizio dei lavori. Un impianto fotovoltaico isolato su un tetto che non viene risanato non riceve questi contributi.',
      'Dal 2026 Basilea Campagna versa inoltre CHF 40 per m² di superficie dei moduli sul tetto o CHF 120 in facciata. Il bonus va inserito nella domanda per l’isolamento e non vale per un impianto fotovoltaico pianificato da solo.',
      'Sono possibili al massimo CHF 100’000 per domanda e il 50% dei costi ammessi per misura. Nuove domande sono possibili dal 12 gennaio 2026.',
      'Verificate separatamente l’incentivo federale tramite Pronovo, la rimunerazione unica (RU). Non sostituisce né la domanda cantonale di risanamento, né una notifica, né una licenza edilizia.',
      'Prima dell’offerta va chiarito se pianificate solo il fotovoltaico, fotovoltaico più isolamento o un risanamento globale.',
    ], bullets: ['Basilea Città: CHF 50/100 per m² di tetto e CHF 70/140 per m² di facciata — solo risanamento con fotovoltaico.', 'Basilea Città: 90% della superficie del tetto idonea o tecnicamente realizzabile; domanda prima dei lavori.', 'Basilea Campagna: CHF 40/120 per m² di superficie dei moduli — solo con isolamento termico.', 'Basilea Campagna: massimo CHF 100’000 per domanda e 50% dei costi ammessi per misura.'], sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { id: 'bewilligung', title: 'Serve una licenza o basta una notifica?', paragraphs: [
      'Se basti una notifica o serva una licenza edilizia dipende dal Cantone, dalla zona e dalla protezione. Incentivi e prescrizioni edilizie sono distinti.',
      'A Basilea Città, in determinate zone può bastare una notifica per un impianto ben integrato. Nelle zone con protezione particolare e per i monumenti culturali può servire una licenza edilizia.',
      'Per facciate visibili ed edifici storici è opportuno consultare presto l’autorità competente. A Basilea Campagna gli impianti fotovoltaici sui tetti nelle zone edificabili e agricole sono in linea di principio esenti da autorizzazione.',
      'Devono però essere notificati almeno 30 giorni prima dell’inizio. Nelle zone centrali, di protezione degli insediamenti e dei monumenti, per importanti monumenti culturali e naturali e fuori zona edificabile può servire una licenza.',
      'Una domanda d’incentivo non sostituisce né la notifica né la licenza. A Basilea Città la domanda va presentata prima dei lavori; nel pacchetto energetico di Basilea Campagna il bonus fotovoltaico rientra nella domanda per l’isolamento.',
    ], bullets: ['Annotare indirizzo e Cantone. Verificare poi zona, protezione dell’edificio e soluzione su tetto o facciata.', 'Presentare notifica o domanda di costruzione prima di iniziare e considerare i termini dell’autorità competente.', 'Verificare separatamente la domanda d’incentivo, soprattutto il momento anteriore ai lavori.'], sourceIds: ['bs-permit', 'bl-permit', 'bs-solarkraftwerk', 'bl-energie'] },
    { id: 'kosten', title: 'Quanto costa un impianto solare qui?', paragraphs: ['Il Cantone non pubblica un prezzo fisso per il fotovoltaico. Contano soprattutto tetto, dimensioni dell’impianto e dotazione desiderata.', 'Il confronto più utile non è quindi un prezzo forfettario online, ma diverse offerte per lo stesso progetto.'], bullets: ['Superficie e forma del tetto, superficie utile dei moduli, sottostruttura e stato della copertura', 'Potenza dell’impianto e moduli scelti', 'Ponteggio, accesso e logistica di cantiere', 'Lavori elettrici, contatore e allacciamento alla rete', 'Batteria di accumulo e altri componenti supplementari', 'Autoconsumo e profilo di carico previsto', 'Inverter', 'Installatore, entità delle prestazioni, garanzie e assistenza successiva'], sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { id: 'fuer-wen', title: 'Per chi è particolarmente adatto un impianto solare qui?', paragraphs: [
      'Un impianto solare è particolarmente adatto se pianificate insieme risanamento e fotovoltaico. A Basilea Città ciò vale per «Solarkraftwerk Basel», a Basilea Campagna per l’isolamento termico con fotovoltaico.',
      'A Basilea Città il requisito del 90% dovrebbe essere raggiungibile. Senza risanamento non includete l’azione cantonale nel calcolo, ma verificate separatamente incentivo federale e autoconsumo.',
      'A Basilea Campagna il bonus è adatto ai proprietari che pianificano insieme isolamento termico e fotovoltaico. Per edifici locati, plurifamiliari o piccole superfici del tetto vanno chiariti anche proprietà, pianificazione dei contatori, statica e ripartizione del consumo elettrico.',
    ], sourceIds: ['bs-solarkraftwerk', 'bl-energie'], module: { kind: 'jurisdiction-steps', title: 'Quale regola basilese vale per me?', intro: 'Verificate anzitutto da quale lato del confine cantonale si trova il vostro immobile:', columns: ['Immobile a Basilea Città', 'Immobile a Basilea Campagna'], items: [
      { title: 'Immobile a Basilea Città', text: '1. Verificare ubicazione e catasto solare. 2. Pianificare il risanamento di tetto o facciata con fotovoltaico e verificare se il 90% è raggiungibile. 3. Chiarire protezione e procedura; presentare la domanda prima dei lavori.', detail: 'Solo il risanamento con fotovoltaico rientra in «Solarkraftwerk Basel». Un impianto fotovoltaico isolato non diventa per questo un progetto di risanamento.', sourceIds: ['bs-solarkraftwerk', 'bs-permit'] },
      { title: 'Immobile a Basilea Campagna', text: '1. Pianificare insieme isolamento termico e fotovoltaico. 2. Verificare domanda d’isolamento, bonus per i moduli, CHF 100’000 e 50%. 3. Presentare la notifica almeno 30 giorni prima dei lavori o avviare una domanda di costruzione in caso di protezione.', detail: 'Il bonus fotovoltaico è legato a un isolamento termico ammesso agli incentivi. Non è un contributo autonomo per un normale impianto fotovoltaico.', sourceIds: ['bl-energie', 'bl-permit'] },
    ] } },
  ],
  faqs: [
    { question: 'Esiste un incentivo cantonale per il fotovoltaico a Basilea?', answer: 'Sì, ma non esiste un bonus basilese uniforme. A Basilea Città «Solarkraftwerk Basel» è legato al risanamento energetico con fotovoltaico. A Basilea Campagna il bonus fotovoltaico vale solo con isolamento termico; verificate separatamente la rimunerazione unica federale (RU) tramite Pronovo.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { question: 'Qual è la differenza tra Basilea Città e Basilea Campagna?', answer: 'I Cantoni hanno regole differenti. Basilea Città incentiva il risanamento con fotovoltaico con CHF 50/100 per m² di tetto e CHF 70/140 per m² di facciata; per gli impianti sul tetto vale in linea di principio il 90%. Basilea Campagna aggiunge all’isolamento termico CHF 40/120 per m² di moduli e ha regole proprie per domande e costruzioni.', sourceIds: ['bs-solarkraftwerk', 'bl-energie'] },
    { question: 'L’offensiva solare di Basilea Città è già legge?', answer: 'No. È una proposta pianificata per aumentare il fotovoltaico e imporlo sulle superfici idonee. Per gli edifici esistenti sono previsti 15 anni di transizione. Fino all’entrata in vigore, questo obbligo non è diritto applicabile.', sourceIds: ['bs-offensive'] },
    { question: 'Come funziona «Solarkraftwerk Basel»?', answer: 'Combinate un risanamento energetico del tetto o della facciata con fotovoltaico sulla superficie risanata. Presentate la domanda prima dei lavori. Sul tetto valgono CHF 50/100, in facciata CHF 70/140 per m²; per gli impianti sul tetto va rispettato il requisito del 90%.', sourceIds: ['bs-solarkraftwerk'] },
    { question: 'A quanto ammonta il bonus fotovoltaico a Basilea Campagna nel 2026?', answer: 'Il bonus ammonta a CHF 40 per m² di moduli sul tetto e CHF 120 in facciata. Rientra nella domanda per l’isolamento, non in un impianto fotovoltaico pianificato da solo. Sono possibili al massimo CHF 100’000 per domanda e il 50% dei costi ammessi per misura.', sourceIds: ['bl-energie'] },
    { question: 'Basilea Campagna impone il solare in generale alle case esistenti?', answer: 'No. L’iniziativa legislativa «Sfruttare il potenziale – garantire l’approvvigionamento» è stata respinta l’8 marzo 2026 con il 67,6% di no. Non ne è derivato alcun nuovo obbligo generale di adeguamento. Per notifica o licenza contano ancora zona, protezione dell’edificio e impianto.', sourceIds: ['bl-abstimmung', 'bl-permit'] },
    { question: 'Quando serve una licenza edilizia a Basilea Città?', answer: 'Dipende dall’impianto e dall’ubicazione. Per un impianto ben integrato può bastare una notifica. Nelle zone protette, per i monumenti culturali e per soluzioni sensibili su tetto o facciata può servire una licenza; l’autorità competente dovrebbe classificare il caso prima dell’offerta.', sourceIds: ['bs-permit', 'bs-offensive'] },
  ],
  sources: [
    { id: 'bs-solarkraftwerk', authority: 'Cantone di Basilea Città', title: 'Azione Solarkraftwerk Basel: contributi d’incentivazione', url: 'https://www.bs.ch/wsu/aue/abteilung-energie/aktion-solarkraftwerk-basel' },
    { id: 'bs-permit', authority: 'Cantone di Basilea Città', title: 'Ho bisogno di una licenza edilizia?', url: 'https://www.bs.ch/themen/umwelt-und-bauen/bauen-im-kanton-basel-stadt/brauche-ich-eine-baubewilligung' },
    { id: 'bs-offensive', authority: 'Gran Consiglio di Basilea Città', title: 'Rapporto del Consiglio di Stato sull’offensiva solare (25.06.2025, oggetto 25.0921.01)', url: 'https://grosserrat.bs.ch/dokumente/100410/000000410351.pdf' },
    { id: 'bl-energie', authority: 'Cantone di Basilea Campagna', title: 'Nuovi incentivi nel programma cantonale 2026', url: 'https://www.baselland.ch/politik-und-behorden/direktionen/bau-und-umweltschutzdirektion/umweltschutz-energie/medienmitteilungen/neue-anreize-im-kantonalen-foerderprogramm' },
    { id: 'bl-permit', authority: 'Cantone di Basilea Campagna', title: 'Impianti solari / pompe di calore: obbligo di notifica e autorizzazione', url: 'https://www.baselland.ch/politik-und-behorden/direktionen/bau-und-umweltschutzdirektion/bauinspektorat/solaranlagen-waermepumpen' },
    { id: 'bl-abstimmung', authority: 'Cantone di Basilea Campagna', title: 'Risultato della votazione: «Sfruttare il potenziale – garantire l’approvvigionamento» (8 marzo 2026)', url: 'https://abstimmungen.bl.ch/app/archive/de/vote/ct-13-160.html' },
  ],
};