import type { CantonGuide } from '../types';

const sources = [
  { id: 'fr-solar-permit', authority: 'Cantone di Friburgo / Etat de Fribourg', title: 'Impianti solari – licenza edilizia', url: 'https://www.fr.ch/territoire-amenagement-et-constructions/permis-de-construire-et-autorisations/permis-de-construire/permis-de-construire-installations-solaires' },
  { id: 'fr-energy-law', authority: 'Cantone di Friburgo', title: 'Regolamento sull’energia (SGF 770.11), art. 25', url: 'https://bdlf.fr.ch/app/de/texts_of_law/770.11' },
  { id: 'fr-energy-subsidies', authority: 'Cantone di Friburgo / Etat de Fribourg', title: 'Programma di incentivi in materia di energia', url: 'https://www.fr.ch/deef/sde/programmes-de-subventions-en-matiere-denergie' },
  { id: 'fr-pronovo-faq', authority: 'Pronovo AG su mandato della Confederazione', title: 'Domande frequenti sulla rimunerazione unica (RU) e sugli incentivi solari in Svizzera', url: 'https://pronovo.ch/de/foerderung/photovoltaik/haeufige-fragen/' },
] as const;

export const guide: CantonGuide = {
  id: 'freiburg', path: '/it/fotovoltaico-friburgo', canton: 'Friburgo',
  title: 'Fotovoltaico a Friburgo: obbligo e permessi 2026 | PvPro.ch',
  description: 'Fotovoltaico nel Cantone di Friburgo: elettricità propria nelle nuove costruzioni, incentivi Pronovo e notifica per tetti e facciate.',
  h1: 'Fotovoltaico nel Cantone di Friburgo: cosa vale per i proprietari nel 2026',
  intro: [
    'Nel Cantone di Friburgo una nuova costruzione deve produrre autonomamente una parte dell’elettricità. Non si tratta di un obbligo fotovoltaico generale per ogni casa esistente.',
    'Dal 2026, per gli impianti su tetti e facciate sufficientemente integrati può bastare una notifica anziché una domanda di costruzione completa. Qui sono spiegati in modo semplice la regola sull’elettricità propria, il termine, gli incentivi e le principali eccezioni.',
  ],
  quickFacts: [
    { value: '10 W/m²', label: 'Potenza minima per l’elettricità propria di una nuova costruzione interessata', sourceIds: ['fr-energy-law'] },
    { value: '30 kW', label: 'Potenza massima esigibile in virtù dell’obbligo per le nuove costruzioni', sourceIds: ['fr-energy-law'] },
    { value: '30 giorni', label: 'Termine generale per la relativa notifica prima dell’inizio dei lavori', sourceIds: ['fr-solar-permit'] },
    { value: '2026', label: 'Da allora gli impianti idonei in facciata possono essere esaminati con la procedura di notifica', sourceIds: ['fr-solar-permit'] },
  ],
  sections: [
    { id: 'neubau', title: 'Le nuove costruzioni a Friburgo devono produrre elettricità propria?', paragraphs: [
      'Sì. Per le nuove costruzioni vige l’obbligo di produrre elettricità propria. Nella pratica viene spesso adempiuto con il fotovoltaico, ma giuridicamente non è imposto in modo generalizzato un impianto fotovoltaico per ogni casa.',
      'Il requisito è di almeno 10 W/m² di superficie di riferimento energetico (SRE). La SRE è la superficie dell’edificio determinante per il calcolo energetico; non coincide semplicemente con la superficie del tetto disponibile. Complessivamente possono essere richiesti al massimo 30 kW.',
      'Determinati piccoli ampliamenti sono esclusi. L’eccezione di legge vale per un ampliamento inferiore a 50 m² oppure pari al massimo al 20% dell’edificio esistente e al massimo a 1’000 m²; il progetto concreto va verificato con la prova energetica.',
    ], sourceIds: ['fr-energy-law'], notice: { title: 'Nessun obbligo fotovoltaico generale per ogni casa', text: 'La regola friburghese riguarda la produzione propria di elettricità nelle nuove costruzioni. Per una casa esistente non ne deriva automaticamente l’obbligo di installare a posteriori un impianto fotovoltaico.', status: 'important' }, module: { kind: 'project-check', title: 'Che cosa vale per il mio progetto?', intro: 'Verificate le due domande una dopo l’altra e indipendentemente: prima la regola sull’elettricità propria, poi la procedura adatta per l’impianto.', items: [
      { title: '1. È una nuova costruzione?', text: 'Sì: verificare la produzione propria, almeno 10 W/m² SRE; per legge possono essere richiesti al massimo 30 kW. No: questa regola per le nuove costruzioni non comporta un obbligo generale di produzione propria per una casa esistente.', detail: 'I piccoli ampliamenti possono essere esclusi: meno di 50 m² oppure al massimo il 20% dell’esistente e al massimo 1’000 m².', sourceIds: ['fr-energy-law'] },
      { title: '2. Il tetto o la facciata sono sufficientemente integrati?', text: 'Sì: verificare la procedura di notifica e inviare di regola la notifica al Comune 30 giorni prima dell’inizio dei lavori. No: chiarire la licenza edilizia con il Comune; può restare necessaria per un oggetto protetto o un insediamento sensibile.', detail: 'Dal 1° gennaio 2026 anche gli impianti in facciata sufficientemente integrati possono essere notificati alle condizioni della procedura.', sourceIds: ['fr-solar-permit'] },
    ] } },
    { id: 'bewilligung', title: 'Notifica o licenza edilizia?', paragraphs: [
      'Per molti progetti solari sufficientemente integrati può bastare una notifica anziché una domanda di costruzione completa. A seconda del caso, ciò vale per gli impianti sul tetto e, dal 1° gennaio 2026, anche per quelli idonei in facciata.',
      'La notifica è una comunicazione semplificata al Comune, non un’autorizzazione automatica per ogni progetto. Per oggetti protetti, insediamenti sensibili o un impianto non sufficientemente integrato può essere necessaria una licenza edilizia.',
      'Per la relativa regola sulle facciate, la notifica avviene di regola 30 giorni prima dell’inizio dei lavori. Se occorre una procedura edilizia ordinaria, nel Cantone di Friburgo le domande passano attraverso FRIAC, il portale cantonale online per le domande di costruzione.',
    ], bullets: ['Procedura di notifica: presentare per tempo al Comune la documentazione del progetto.', 'Oggetto protetto o insediamento sensibile: chiarire presto la licenza edilizia con l’autorità competente.', 'Domanda di costruzione ordinaria: utilizzare FRIAC, il portale cantonale online.'], sourceIds: ['fr-solar-permit'] },
    { id: 'foerderung', title: 'Incentivi nel Cantone di Friburgo', paragraphs: [
      'L’incentivo vero e proprio per un impianto fotovoltaico è erogato in linea di principio dalla Confederazione tramite Pronovo. Secondo le FAQ di Pronovo, la rimunerazione unica ordinaria (RU) è possibile da una potenza minima di 2 kW; l’importo concreto dipende dal progetto, dalla potenza, dal tipo d’impianto e dal modello d’incentivazione.',
      'I bonus federali supplementari non costituiscono una somma complessiva automatica. A seconda del progetto possono essere rilevanti, ad esempio, un bonus per l’angolo d’inclinazione da 75°, un bonus per aree di parcheggio per impianti qualificati da 100 kW o, dal 2026, un bonus per l’elettricità invernale a condizioni particolari per impianti da 100 kW. Ogni bonus ha requisiti propri e non può essere semplicemente sommato agli altri contributi.',
      'Il Programma Edifici cantonale è distinto. Non va presentato come incentivo friburghese generale per ogni impianto fotovoltaico; una specifica misura edilizia e la relativa domanda vanno esaminate separatamente secondo le condizioni ufficiali.',
    ], sourceIds: ['fr-pronovo-faq', 'fr-energy-subsidies'], notice: { title: 'Distinguere l’incentivo federale dal programma cantonale', text: 'Pronovo esamina gli incentivi federali per il fotovoltaico. I programmi cantonali per gli edifici possono sostenere proprie misure energetiche, ma non sono un contributo fotovoltaico forfettario per ogni abitazione.', status: 'important' } },
    { id: 'begriffe', title: 'I termini principali spiegati semplicemente', paragraphs: [
      'W/m² significa watt per metro quadrato. I 10 W/m² si riferiscono alla superficie di riferimento energetico della nuova costruzione e descrivono la potenza richiesta per produrre elettricità propria.',
      'SRE significa superficie di riferimento energetico. È la superficie calcolata dell’edificio ai fini delle prescrizioni energetiche, non automaticamente la superficie su cui trovano posto i moduli solari.',
      'La procedura di notifica è la comunicazione semplificata di un progetto al Comune. La licenza edilizia è invece la procedura ordinaria quando il progetto deve essere esaminato più attentamente per ragioni di configurazione, protezione o altro.',
    ], sourceIds: ['fr-energy-law', 'fr-solar-permit'] },
    { id: 'kosten', title: 'Quanto costa un impianto solare qui?', paragraphs: [
      'Il Cantone non pubblica un prezzo fisso per gli impianti solari. Sono determinanti il tetto, le dimensioni dell’impianto, i lavori elettrici e la dotazione.',
      'Confrontate diverse offerte per lo stesso progetto. Vedrete così se i lavori sul tetto, l’allacciamento, l’accumulo e la potenza desiderata sono inclusi integralmente e in modo comprensibile.',
    ], bullets: ['Superficie e forma del tetto, superficie utile per i moduli', 'Dimensioni e potenza dell’impianto', 'Ponteggio, accesso e oneri di cantiere', 'Lavori elettrici, contatore e allacciamento alla rete', 'Inverter', 'Batteria di accumulo e infrastruttura di ricarica', 'Autoconsumo, pompa di calore e auto elettrica', 'Installatore, entità delle prestazioni e garanzie'], sourceIds: ['fr-pronovo-faq', 'fr-solar-permit'] },
    { id: 'fuer-wen', title: 'Per chi il solare è particolarmente interessante a Friburgo?', paragraphs: [
      'I proprietari di una nuova costruzione dovrebbero pianificare particolarmente presto, poiché la produzione propria di elettricità rientra nella prova energetica. Anche una grande superficie idonea del tetto o un risanamento del tetto o della facciata già previsto può essere il momento giusto per una pianificazione congiunta.',
      'Il solare si abbina inoltre bene a un’economia domestica con pompa di calore o auto elettrica, se autoconsumo e allacciamento vengono pianificati insieme. La convenienza dipende dal tetto, dal consumo, dalla procedura e dall’offerta concreta; non se ne possono dedurre rendimenti fissi.',
    ], sourceIds: ['fr-energy-law', 'fr-solar-permit', 'fr-pronovo-faq'] },
  ],
  faqs: [
    { question: 'Nel Cantone di Friburgo vige un obbligo solare?', answer: 'Per le nuove costruzioni vige l’obbligo di produrre elettricità propria, ma non esiste un obbligo fotovoltaico generale per ogni casa esistente. Nella pratica il fotovoltaico può adempiere il requisito. I piccoli ampliamenti possono essere esclusi al di sotto delle soglie di legge.', sourceIds: ['fr-energy-law'] },
    { question: 'Quanta elettricità propria deve produrre una nuova costruzione?', answer: 'Una nuova costruzione interessata deve prevedere almeno 10 W/m² di superficie di riferimento energetico per la produzione propria. Complessivamente possono essere richiesti al massimo 30 kW. La superficie di riferimento energetico è la superficie dell’edificio determinante per il calcolo energetico.', sourceIds: ['fr-energy-law'] },
    { question: 'Che cosa significa 10 W/m²?', answer: 'W/m² significa watt per metro quadrato. I 10 W/m² si applicano alla superficie di riferimento energetico della nuova costruzione, non semplicemente alla superficie utile del tetto. Ne risulta la potenza richiesta per la produzione propria di elettricità.', sourceIds: ['fr-energy-law'] },
    { question: 'Sono interessati piccoli annessi e ampliamenti?', answer: 'Determinati piccoli ampliamenti sono esclusi. L’eccezione di legge riguarda un ampliamento inferiore a 50 m² oppure pari al massimo al 20% dell’esistente e al massimo a 1’000 m². La classificazione precisa rientra nell’esame del progetto concreto.', sourceIds: ['fr-energy-law'] },
    { question: 'Devo presentare una domanda di costruzione per un impianto fotovoltaico?', answer: 'Non sempre. Per un impianto sufficientemente integrato può bastare una notifica. Per oggetti protetti, insediamenti sensibili o un’integrazione insufficiente può essere necessaria una licenza edilizia; nella procedura ordinaria la domanda viene presentata tramite FRIAC.', sourceIds: ['fr-solar-permit'] },
    { question: 'Che cosa è cambiato nel 2026 per le facciate?', answer: 'Dal 1° gennaio 2026 anche gli impianti solari in facciata sufficientemente integrati possono seguire, alle condizioni vigenti, una procedura di notifica. Ciò non vale automaticamente per ogni facciata. Oggetti protetti e insediamenti sensibili possono continuare a richiedere una licenza edilizia.', sourceIds: ['fr-solar-permit'] },
    { question: 'Con quanto anticipo devo notificare un impianto in facciata corrispondente?', answer: 'In questa procedura la notifica viene presentata di regola al Comune 30 giorni prima dell’inizio dei lavori. Prima vanno chiariti l’integrazione, lo stato di protezione e la completezza dei documenti. Il termine non sostituisce un’ulteriore licenza edilizia, se necessaria.', sourceIds: ['fr-solar-permit'] },
    { question: 'Quali incentivi esistono per un impianto solare a Friburgo?', answer: 'L’incentivo agli investimenti fotovoltaici è erogato principalmente dalla Confederazione tramite Pronovo. Secondo le FAQ di Pronovo, la rimunerazione unica ordinaria è possibile da 2 kW; l’incentivo concreto dipende dal progetto e dalle condizioni federali. I programmi cantonali per gli edifici sono distinti e non costituiscono un incentivo fotovoltaico generale.', sourceIds: ['fr-pronovo-faq', 'fr-energy-subsidies'] },
    { question: 'Quali bonus federali supplementari possono essere rilevanti?', answer: 'A seconda del progetto esistono bonus federali facoltativi con requisiti propri, ad esempio un bonus per l’angolo d’inclinazione da 75°, un bonus per aree di parcheggio per impianti qualificati da 100 kW o, dal 2026, un bonus per l’elettricità invernale a condizioni particolari da 100 kW. Questi bonus non sono garantiti e non vanno sommati in un importo forfettario.', sourceIds: ['fr-pronovo-faq'] },
    { question: 'Che cosa vale per un edificio protetto?', answer: 'Gli oggetti protetti e gli insediamenti sensibili possono continuare a richiedere una licenza edilizia. Una notifica semplificata per un impianto sufficientemente integrato non è quindi automaticamente possibile. Chiarite presto lo stato di protezione con il Comune o l’autorità edilizia competente.', sourceIds: ['fr-solar-permit'] },
  ],
  sources: [...sources],
};