import type { CantonGuide } from '../types';
const sources = [
 { id:'lu-keng', authority:'Cantone di Lucerna, Ambiente ed energia', title:'Legge cantonale sull’energia in breve – Cantone di Lucerna', url:'https://uwe.lu.ch/Energiegesetz/KEnG_kompakt' },
 { id:'lu-foerderprogramme', authority:'Cantone di Lucerna, Ambiente ed energia', title:'Programmi di incentivazione energetica – Cantone di Lucerna', url:'https://uwe.lu.ch/themen/energie/foerderprogramme' },
 { id:'lu-even', authority:'Cantone di Lucerna, Ambiente ed energia', title:'Giustificativi energetici dal 1° gennaio 2026 – Cantone di Lucerna', url:'https://uwe.lu.ch/Energiegesetz/Energienachweise_ab_Anfang_2026' },
 { id:'lu-solar', authority:'Cantone di Lucerna, Ambiente ed energia', title:'Energia solare – Cantone di Lucerna, Ambiente ed energia', url:'https://uwe.lu.ch/themen/energie/erneuerbare_energien/Solar' },
] as const;
export const guide: CantonGuide = {
 id:'luzern', path:'/it/fotovoltaico-lucerna', canton:'Lucerna', title:'Fotovoltaico a Lucerna 2026: obblighi, incentivi e offerte | PvPro.ch',
 description:'Cosa vale nel Cantone di Lucerna per nuovi edifici e risanamenti del tetto: elettricità propria, tassa sostitutiva, incentivi e offerte solari.',
 h1:'Fotovoltaico a Lucerna: regole, incentivi e offerte 2026',
 intro:['Nel Cantone di Lucerna, i nuovi edifici e determinati risanamenti del tetto sono soggetti a prescrizioni precise sulla produzione propria di elettricità. Qui scoprite cosa vale per il vostro progetto e quali canali di incentivazione sono pertinenti.','Dal 1° marzo 2025 è particolarmente importante distinguere tra nuovo edificio, risanamento del tetto, riparazione e manutenzione. Dal 2026 il giustificativo energetico viene gestito tramite la piattaforma digitale EVEN.'],
 quickFacts:[
  {value:'Dal 1.3.2025',label:'elettricità propria per nuovi edifici e risanamenti del tetto',sourceIds:['lu-keng']},
  {value:'Max. CHF 1’000',label:'di tassa sostitutiva per ogni kW mancante',sourceIds:['lu-keng']},
  {value:'Incentivi fotovoltaici',label:'Confederazione / Pronovo',sourceIds:['lu-foerderprogramme']},
  {value:'2026',label:'giustificativo energetico tramite EVEN',sourceIds:['lu-even']},
 ], ctaAfterSection:'dach-check', sections:[
  {id:'dach-check',title:'Nuovo edificio, risanamento o riparazione: cosa vale per il mio tetto?',paragraphs:['Dal 1° marzo 2025, nel Cantone di Lucerna la produzione propria di elettricità è rilevante per i nuovi edifici e per gli edifici esistenti sottoposti a risanamento del tetto. Il primo passo consiste quindi nel classificare correttamente il progetto.'],sourceIds:['lu-keng','lu-solar'],module:{kind:'roof-duty-check',title:'Cosa vale per il mio tetto?',intro:'Classificate il progetto e verificate poi se il requisito viene soddisfatto producendo elettricità propria o se occorre esaminare una tassa sostitutiva.',items:[
   {title:'Nuovo edificio',value:'Norma sull’elettricità propria',text:'Per un nuovo edificio, sfruttare adeguatamente il potenziale di produzione elettrica e verificare la norma sull’elettricità propria applicabile al progetto.',sourceIds:['lu-keng']},
   {title:'Vero risanamento del tetto',value:'Norma sull’elettricità propria',text:'Anche per un edificio esistente sottoposto a risanamento del tetto vale il principio secondo cui il potenziale di produzione elettrica deve essere sfruttato adeguatamente.',sourceIds:['lu-keng']},
   {title:'Riparazione / manutenzione',value:'Non è automaticamente un risanamento',text:'I semplici lavori di riparazione e manutenzione non vanno equiparati in modo generalizzato a un risanamento completo del tetto; verificate il progetto concreto in base all’aiuto cantonale all’esecuzione.',sourceIds:['lu-solar','lu-keng']},
   {title:'Requisito soddisfatto',value:'Elettricità propria',text:'Se il requisito è soddisfatto, proseguire la progettazione con il fotovoltaico o la produzione propria prevista.',sourceIds:['lu-keng']},
   {title:'Requisito non soddisfatto',value:'Tassa sostitutiva',text:'Se il requisito non è soddisfatto, va esaminata una tassa sostitutiva. Ammonta al massimo a CHF 1’000 per ogni kW della potenza minima richiesta ma non realizzata.',sourceIds:['lu-keng']},
  ]}},
  {id:'even',title:'Giustificativo energetico 2026: gestione tramite EVEN',paragraphs:['Chiarite con l’impresa specializzata incaricata della progettazione chi prepara il giustificativo energetico per il vostro progetto e chi ne cura la gestione digitale. In questo modo progettazione tecnica e documentazione restano coordinate.'],sourceIds:['lu-even'],notice:{title:'EVEN dal 1° gennaio 2026',text:'Dal 1° gennaio 2026 il giustificativo energetico nel Cantone di Lucerna viene gestito tramite la piattaforma digitale EVEN.',status:'important'}},
  {id:'foerderung',title:'Incentivi fotovoltaici della Confederazione e di Pronovo',paragraphs:['Per gli incentivi ordinari destinati a un impianto fotovoltaico è competente la Confederazione, rispettivamente Pronovo. Dai programmi lucernesi qui elencati non risulta un contributo cantonale generale per il fotovoltaico.','Fate indicare separatamente nell’offerta l’incentivo previsto. Per un confronto trasparente servono dapprima il prezzo dell’impianto prima della deduzione degli incentivi e poi la base del sostegno ipotizzato. Un’eventuale tassa sostitutiva non è un incentivo, ma una voce di confronto distinta.'],sourceIds:['lu-foerderprogramme','lu-keng']},
  {id:'vorhaben',title:'Preparare insieme i lavori al tetto e l’impianto solare',paragraphs:['Descrivete all’impresa specializzata nel modo più preciso possibile i lavori previsti sul tetto. Fotografie, piani esistenti e una descrizione della struttura del tetto aiutano a classificare il progetto secondo l’aiuto cantonale all’esecuzione. La sola dicitura «lavori al tetto» dice ancora poco sull’intervento effettivo.','Coordinate poi i lavori all’edificio con il montaggio fotovoltaico. Chiedete quali ponteggi e lavori accessori sono già inclusi nell’offerta per il tetto e quali vengono proposti in aggiunta per l’impianto solare. Eviterete così di confrontare prezzi riferiti a prestazioni diverse.'],sourceIds:['lu-solar','lu-keng']},
  {id:'kosten',title:'Quanto costa un impianto fotovoltaico a Lucerna?',paragraphs:['Un prezzo forfettario non sostituisce un’offerta per il vostro edificio. Le seguenti voci dovrebbero essere incluse in modo comprensibile oppure escluse espressamente.','A Lucerna si aggiunge un ulteriore elemento di confronto: la soluzione tecnica e un’eventuale tassa sostitutiva non dovrebbero essere confrontate partendo da ipotesi progettuali diverse. Richiedete quindi offerte sulla stessa base.','Con PvPro.ch i proprietari possono confrontare gratuitamente e senza impegno fino a tre offerte solari adeguate.'],bullets:['superficie e geometria del tetto','accessibilità e ponteggi','integrazione nell’edificio','quadro elettrico','batteria di accumulo','lavori accessori'],sourceIds:['lu-keng','lu-solar']},
  {id:'offerten-pruefen',title:'Quali differenze tra le offerte sono importanti?',paragraphs:['Non verificate soltanto il prezzo finale, ma anche le prestazioni offerte e la ripartizione dei lavori. La batteria è un’opzione o è già compresa? Sono inclusi i lavori elettrici e gli adeguamenti del quadro? Quali voci vengono fatturate secondo l’onere effettivo?','In caso di differenze, chiedete una breve spiegazione e una variante d’offerta comparabile. Solo classificando allo stesso modo prestazioni, lavori all’edificio e dotazione facoltativa si può stabilire se la differenza di prezzo dipende dall’estensione delle prestazioni o dall’offerta stessa.'],sourceIds:[]},
 ], faqs:[
  {question:'A Lucerna l’obbligo di produrre elettricità propria vale anche per il risanamento del tetto?',answer:'Sì. Nei nuovi edifici e negli edifici esistenti sottoposti a risanamento del tetto, il potenziale di produzione elettrica deve essere sfruttato adeguatamente; in alternativa è possibile una tassa sostitutiva.',sourceIds:['lu-keng']},
  {question:'A quanto può ammontare la tassa sostitutiva?',answer:'Ammonta al massimo a CHF 1’000 per ogni kW della potenza minima richiesta ma non realizzata.',sourceIds:['lu-keng']},
  {question:'Ogni piccola riparazione del tetto è automaticamente un risanamento?',answer:'No. I semplici lavori di riparazione e manutenzione non vanno equiparati in modo generalizzato a un risanamento completo del tetto; il progetto concreto va verificato in base all’aiuto cantonale all’esecuzione.',sourceIds:['lu-solar','lu-keng']},
  {question:'Il Cantone di Lucerna incentiva direttamente i normali impianti fotovoltaici?',answer:'Gli incentivi ordinari per gli impianti fotovoltaici provengono dalla Confederazione, rispettivamente da Pronovo; i programmi cantonali non possono essere presentati come contributo fotovoltaico generale.',sourceIds:['lu-foerderprogramme']},
  {question:'Cosa cambia per il giustificativo energetico nel 2026?',answer:'Dal 1° gennaio 2026 il giustificativo energetico nel Cantone di Lucerna viene gestito tramite la piattaforma digitale EVEN.',sourceIds:['lu-even']},
 ], sources:[...sources]
};
