import type { CantonGuide } from '../types';
export const guide:CantonGuide={
 id:'neuenburg',path:'/it/fotovoltaico-neuchatel',canton:'Neuchâtel',title:'Fotovoltaico a Neuchâtel 2026: obbligo e batterie | PvPro.ch',description:'15 W/m² per i nuovi edifici e nuovi incentivi per l’accumulo da marzo 2026: regole fotovoltaiche essenziali nel Cantone di Neuchâtel e offerte.',h1:'Fotovoltaico a Neuchâtel: obbligo e batterie di accumulo 2026',intro:['Neuchâtel abbina prescrizioni chiare sulla produzione propria di elettricità per i nuovi edifici a un nuovo incentivo cantonale per le batterie fotovoltaiche. È essenziale tenere distinti i due strumenti.'],
 quickFacts:[{value:'15 W/m² SRE',label:'elettricità propria nei nuovi edifici; almeno 1 kW di potenza installata',sourceIds:['ne-relcen']},{value:'CHF 800 + CHF 80/kWh',label:'contributo cantonale per la batteria alle condizioni previste',sourceIds:['ne-battery-order','ne-battery-page']},{value:'dal 1.3.2026',label:'incentivi cantonali per batterie fotovoltaiche',sourceIds:['ne-battery-order','ne-battery-page']},{value:'max. 50%',label:'quota dell’investimento totale coperta dal contributo per la batteria',sourceIds:['ne-battery-order','ne-battery-page']}],ctaAfterSection:'batterycheck',
 sections:[
  {id:'neubaupflicht',title:'Distinguere elettricità propria nei nuovi edifici e batterie di accumulo',paragraphs:['I due valori minimi per i nuovi edifici valgono congiuntamente: la superficie di riferimento energetico, detta anche SRE, determina la potenza prescritta. Al contempo si applica una potenza minima indipendente da questo calcolo basato sulla superficie.','Si tratta di una prescrizione sulla produzione propria di elettricità, non di un obbligo di acquistare una batteria. Gli incentivi cantonali per l’accumulo sono uno strumento distinto e possono essere pertinenti anche per un impianto fotovoltaico esistente.'],sourceIds:['ne-relcen']},
  {id:'batterycheck',title:'Il vostro accumulatore è compatibile con il programma cantonale?',paragraphs:['Verificate congiuntamente i requisiti seguenti. La sola formula del contributo non costituisce ancora una garanzia di incentivo; in particolare, non tutta la capacità di accumulo installata può necessariamente essere considerata per intero.'],sourceIds:['ne-battery-order','ne-battery-page'],module:{kind:'battery-eligibility',title:'Verifica degli incentivi per le batterie 2026',intro:'Formula del contributo: CHF 800 per impianto + CHF 80/kWh di capacità di accumulo installata.',items:[
   {title:'Capacità >3 kWh',text:'La batteria deve avere una capacità superiore a 3 kWh.',value:'>3 kWh',sourceIds:['ne-battery-order','ne-battery-page']},
   {title:'Capacità incentivabile',text:'È incentivabile al massimo una capacità pari al doppio della potenza fotovoltaica installata in kWc.',detail:'Al massimo 2 × la potenza fotovoltaica installata in kWc',sourceIds:['ne-battery-order','ne-battery-page']},
   {title:'Limite massimo del contributo',text:'Il contributo complessivo non può superare il 50% dell’investimento totale.',value:'max. 50%',sourceIds:['ne-battery-order','ne-battery-page']},
   {title:'Edificio, fotovoltaico e autoconsumo',text:'Sono necessari un edificio abitativo, un impianto fotovoltaico sul posto e il consumo diretto di una parte dell’elettricità solare.',sourceIds:['ne-battery-order','ne-battery-page']},
   {title:'Messa in servizio dal 1° marzo 2026',text:'Sono incentivabili le batterie di accumulo messe in servizio dal 1° marzo 2026. Fa stato il relativo attestato di sicurezza.',detail:'Fa stato l’attestato di sicurezza',sourceIds:['ne-battery-order','ne-battery-page']},
  ]},notice:{title:'Verificare congiuntamente tutti i criteri',text:'La sola formula del contributo non basta per determinare l’ammissibilità. Capacità, potenza fotovoltaica, quota dell’investimento, edificio, autoconsumo e attestato di sicurezza fanno parte della verifica completa.',status:'important'}},
  {id:'bestehende-pv',title:'Aggiungere una batteria a un impianto fotovoltaico esistente',paragraphs:['Un impianto fotovoltaico esistente non esclude l’incentivo per la batteria. Il contributo vale anche in abbinamento a un impianto fotovoltaico esistente, purché questo si trovi sul posto, una parte dell’elettricità solare venga autoconsumata e siano soddisfatte le altre condizioni.','La distinzione resta quindi importante: la prescrizione di 15 W/m² di SRE e almeno 1 kW riguarda i nuovi edifici. La verifica della batteria può invece interessare anche l’ampliamento di un impianto fotovoltaico esistente.'],bullets:['È ammesso un impianto fotovoltaico esistente sul posto.','Una parte dell’elettricità solare deve essere autoconsumata.','Restano valide le altre condizioni della verifica degli incentivi per le batterie.'],sourceIds:['ne-battery-order','ne-battery-page','ne-relcen']},
  {id:'nachweis',title:'Quali dati sono importanti per verificare l’incentivo',paragraphs:['Per la valutazione, la potenza fotovoltaica installata in kWc, la capacità di accumulo installata e l’investimento totale devono essere indicati separatamente e con chiarezza. In questo modo si può verificare la capacità incentivabile rispetto alla potenza fotovoltaica e comprendere il limite massimo del contributo.','Per gli accumulatori dal 1° marzo 2026 fa stato il relativo attestato di sicurezza. Inoltre, edificio abitativo, impianto fotovoltaico sul posto e autoconsumo vanno considerati insieme alle altre condizioni.'],bullets:['Considerare separatamente la potenza fotovoltaica installata in kWc e la capacità di accumulo installata.','Indicare l’investimento totale per verificare il limite del 50%.','Includere nella verifica l’attestato di sicurezza e l’autoconsumo.'],sourceIds:['ne-battery-order','ne-battery-page']},
  {id:'kosten',title:'Costi di un impianto fotovoltaico con batteria di accumulo',paragraphs:['I costi non dipendono unicamente dalla potenza fotovoltaica. Per una batteria contano soprattutto la capacità utilizzabile, la compatibilità dell’inverter e l’integrazione nell’impianto esistente o nuovo. Il contributo cantonale è una norma d’incentivazione e non garantisce una determinata redditività.','Confrontate quindi le offerte sulla stessa base progettuale. Il dimensionamento della batteria dovrebbe essere comprensibile separatamente da quello del fotovoltaico, affinché potenza, capacità e lavori elettrici non vengano confusi.'],bullets:['capacità di accumulo utilizzabile e dimensione adeguata della batteria','inverter e compatibilità tecnica','quadro elettrico e ulteriori lavori elettrici','integrazione in un impianto fotovoltaico nuovo o esistente'],sourceIds:['ne-battery-order','ne-battery-page']},
  {id:'offerten',title:'Confrontare offerte adeguate per fotovoltaico e accumulo',paragraphs:['PvPro aiuta i proprietari a confrontare senza impegno fino a tre offerte adeguate per il fotovoltaico e, se desiderato, per soluzioni di accumulo.','Fate indicare separatamente nelle offerte la potenza fotovoltaica, la capacità di accumulo installata e utilizzabile e i lavori elettrici. Potrete così verificare sulla stessa base sia l’incentivo per la batteria sia l’esecuzione tecnica.'],sourceIds:[]},
 ],faqs:[
  {question:'Quanta elettricità propria deve produrre un nuovo edificio a Neuchâtel?',answer:'Per i nuovi edifici, il diritto cantonale sull’energia prescrive almeno 15 W/m² di superficie di riferimento energetico, ossia SRE, e almeno 1 kW di potenza installata.',sourceIds:['ne-relcen']},
  {question:'Da quando esistono gli incentivi cantonali per le batterie fotovoltaiche?',answer:'Sono incentivabili le batterie di accumulo messe in servizio dal 1° marzo 2026; fa stato il relativo attestato di sicurezza.',sourceIds:['ne-battery-order','ne-battery-page']},
  {question:'Come viene calcolato l’incentivo per la batteria?',answer:'Il contributo comprende CHF 800 per impianto più CHF 80 per kWh di capacità di accumulo installata e non può superare il 50% dell’investimento totale.',sourceIds:['ne-battery-order','ne-battery-page']},
  {question:'Quale dimensione della batteria viene incentivata?',answer:'La batteria deve avere una capacità superiore a 3 kWh; la capacità incentivabile è limitata al doppio della potenza fotovoltaica installata in kWc.',sourceIds:['ne-battery-order','ne-battery-page']},
  {question:'La batteria può essere aggiunta a un impianto fotovoltaico esistente?',answer:'Sì. Il contributo vale anche con un impianto fotovoltaico esistente, purché questo si trovi sul posto, una parte dell’elettricità solare venga autoconsumata e siano soddisfatte le altre condizioni.',sourceIds:['ne-battery-order','ne-battery-page']},
 ],sources:[
  {id:'ne-relcen',authority:'Cantone di Neuchâtel',title:'Regolamento di esecuzione della legge cantonale sull’energia (RELCEn)',url:'https://rsn.ne.ch/DATA/program/books/RSN2021/20214/htm/74010.htm'},
  {id:'ne-battery-order',authority:'Cantone di Neuchâtel',title:'740.13: decreto sugli incentivi per le batterie di accumulo dell’elettricità fotovoltaica (ASBaSt), del 4 febbraio 2026',url:'https://rsn.ne.ch/DATA/program/books/rsne/htm/740.13.htm'},
  {id:'ne-battery-page',authority:'Cantone di Neuchâtel',title:'Incentivi per le batterie domestiche di accumulo dell’elettricità fotovoltaica | ne.ch',url:'https://www.ne.ch/themes/energie-et-environnement/energie/subventions-pour-les-batteries-domestiques-de-stockage-delectricite-photovoltaique'},
 ]};
