import type { CantonGuide } from '../types';
const sources = [
{id:'nwlaw641.1',authority:'Cantone di Nidvaldo',title:'NG 641.1 – Legge sull’utilizzazione parsimoniosa dell’energia',url:'https://gesetze.nw.ch/app/de/texts_of_law/641.1'},
{id:'programme40289',authority:'Cantone di Nidvaldo',title:'Programma d’incentivazione Energia 2026',url:'https://www.nw.ch/energiefachstellepub/40289'},
{id:'notification37780',authority:'Cantone di Nidvaldo',title:'Modulo di notifica BK per impianti solari | Cantone di Nidvaldo online',url:'https://www.nw.ch/baukoordpub/37780'},
] as const;
export const guide: CantonGuide = {
id:'nidwalden',path:'/it/fotovoltaico-nidvaldo',canton:'Nidvaldo',title:'Fotovoltaico a Nidvaldo 2026: obbligo e incentivi | PvPro.ch',description:'10 W/m² di produzione propria, tassa sostitutiva e bonus per l’involucro edilizio con fotovoltaico: le principali regole per gli impianti solari a Nidvaldo.',h1:'Fotovoltaico a Nidvaldo: obbligo di produzione propria e incentivi 2026',
intro:['Nidvaldo applica un requisito per la produzione propria calcolabile con chiarezza e, a determinate condizioni, abbina il risanamento energetico degli edifici a un ulteriore effetto incentivante per il fotovoltaico.','Per il requisito di produzione propria conta la nuova superficie di riferimento energetico (SRE). L’incentivo per il risanamento edilizio è distinto: CHF 120/m² si riferiscono a un elemento costruttivo termoisolato incentivato, abbinato a un impianto fotovoltaico a copertura integrale, e non alla superficie fotovoltaica stessa.'],
quickFacts:[{value:'10 W/m²',label:'Potenza minima per m² di nuova SRE',sourceIds:['nwlaw641.1']},{value:'max. 30 kW',label:'Limite massimo del requisito di produzione propria',sourceIds:['nwlaw641.1']},{value:'CHF 1’000/kW',label:'Tassa sostitutiva per ogni kW richiesto non realizzato',sourceIds:['nwlaw641.1']},{value:'CHF 60 → CHF 120/m²',label:'Contributo per un elemento costruttivo termoisolato incentivato',sourceIds:['programme40289']}],
sections:[
{id:'eigenstrompflicht',title:'La regola dei 10 W/m² in tre passaggi',paragraphs:['Il punto di partenza per l’obbligo di produzione propria è la nuova superficie di riferimento energetico (SRE). Il calcolo si articola in tre passaggi chiari.'],sourceIds:['nwlaw641.1'],module:{kind:'own-power-steps',title:'Regola dei 10 W/m² in tre passaggi',intro:'Nuova SRE × 10 W/m² → potenza risultante → limite massimo di 30 kW.',items:[{title:'1. Nuova SRE',value:'Nuova SRE × 10 W/m²',text:'Fa stato la superficie di riferimento energetico creata dal progetto.',detail:'La prescrizione legale è di almeno 10 W di potenza per ogni m² di nuova SRE.',sourceIds:['nwlaw641.1']},{title:'2. Potenza risultante',value:'SRE × 10 W/m²',text:'Dalla superficie risulta la potenza minima da garantire ai fini del requisito di produzione propria.',detail:'Il calcolo combina la nuova SRE con il valore minimo di 10 W/m².',sourceIds:['nwlaw641.1']},{title:'3. Applicare il limite massimo',value:'Al massimo 30 kW',text:'In virtù di questa prescrizione devono essere garantiti al massimo 30 kW.',detail:'Il limite massimo fa parte del requisito di produzione propria.',sourceIds:['nwlaw641.1']}]},notice:{title:'Alternativa in caso di potenza non realizzata',text:'Per la potenza richiesta ma non realizzata, il diritto cantonale prevede una tassa sostitutiva di CHF 1’000 per kW.',status:'important'}},
{id:'gebaeudehuelle-pv',title:'Considerare separatamente involucro edilizio e fotovoltaico',paragraphs:['Il contributo per l’involucro edilizio si riferisce all’elemento costruttivo termoisolato incentivato, non alla superficie fotovoltaica. Secondo il programma, l’abbinamento con un impianto fotovoltaico a copertura integrale può aumentare l’aliquota.'],sourceIds:['programme40289'],module:{kind:'comparison',items:[],title:'CHF 60/m² o CHF 120/m²?',intro:'È determinante che il fotovoltaico soddisfi la definizione di «copertura integrale» del programma.',columns:['Involucro edilizio','Involucro edilizio + fotovoltaico'],rows:[{label:'Contributo',left:'CHF 60/m² per l’elemento costruttivo termoisolato incentivato',right:'CHF 120/m² per l’elemento costruttivo termoisolato incentivato abbinato al fotovoltaico',sourceIds:['programme40289']},{label:'Fotovoltaico a copertura integrale',left:'Contributo per l’involucro edilizio senza l’aliquota combinata maggiorata',right:'Fotovoltaico sul 20% della facciata o sul 50% del tetto piano o inclinato',sourceIds:['programme40289']},{label:'Inquadramento',left:'Contributo per l’elemento isolato, non per la superficie fotovoltaica',right:'Non è un incentivo fotovoltaico generale; gli impianti fotovoltaici ordinari sono incentivati in linea di principio dalla Confederazione.',sourceIds:['programme40289']}]},notice:{title:'Domanda d’incentivo prima dell’inizio dei lavori',text:'La domanda per il risanamento edilizio deve essere presentata di principio prima dell’inizio dei lavori; i contributi cantonali sono inoltre soggetti alle condizioni e ai crediti disponibili del programma.',status:'important'}},
{id:'meldung',title:'Modulo di notifica per impianti solari',paragraphs:['Per il progetto solare è disponibile il modulo BK aggiornato del Cantone di Nidvaldo per la notifica degli impianti solari. Utilizzate il modello cantonale per i dati relativi al progetto e chiarite eventuali questioni particolari con l’ufficio competente prima della realizzazione.'],sourceIds:['notification37780']},
{id:'kosten',title:'Fattori di costo del vostro progetto',paragraphs:['I costi dipendono dalle dimensioni del progetto e dalle condizioni costruttive. Confrontate le offerte solo se indicano gli stessi lavori e la stessa potenza richiesta.','In caso di abbinamento con lavori d’isolamento, è utile una ripartizione chiara: quale voce riguarda l’involucro edilizio, quale l’impianto solare e quale entrambi i lavori? Fate attribuire in modo trasparente soprattutto ponteggi e lavori accessori. Il contributo più elevato per l’involucro edilizio non giustifica il confronto di tutti i costi del cantiere comune come costi del fotovoltaico.','Chiedete agli offerenti di indicare nell’offerta la superficie di riferimento energetico utilizzata e la potenza che ne deriva. Per una batteria aggiuntiva è utile una voce di prezzo separata. Potrete così confrontare una variante senza accumulo con lo stesso impianto fotovoltaico e capire se le differenze di prezzo derivano dal dimensionamento o da lavori supplementari.','Con PvPro.ch i proprietari confrontano fino a tre offerte solari non vincolanti sulla stessa base di progetto.'],bullets:['potenza richiesta in base alla nuova SRE','superficie e geometria del tetto','montaggio, ponteggi e accessibilità','lavori elettrici e distribuzione elettrica','sistema di accumulo a batteria','coordinamento con l’isolamento del tetto o della facciata'],sourceIds:[]}
],ctaAfterSection:'eigenstrompflicht',faqs:[{question:'Come si calcola l’obbligo di produzione propria a Nidvaldo?',answer:'Fa stato una potenza minima di 10 W per ogni m² di nuova superficie di riferimento energetico.',sourceIds:['nwlaw641.1']},{question:'Esiste un limite massimo per l’obbligo?',answer:'Sì. In virtù di questa prescrizione devono essere garantiti al massimo 30 kW.',sourceIds:['nwlaw641.1']},{question:'Che cosa succede se la potenza richiesta non viene realizzata?',answer:'Per la potenza richiesta ma non realizzata, il diritto cantonale prevede una tassa sostitutiva di CHF 1’000 per kW.',sourceIds:['nwlaw641.1']},{question:'Nidvaldo versa CHF 120/m² per ogni impianto fotovoltaico?',answer:'No. CHF 120/m² si riferiscono a un elemento costruttivo termoisolato incentivato abbinato a un impianto fotovoltaico a copertura integrale secondo la definizione del programma; gli impianti fotovoltaici ordinari sono incentivati in linea di principio dalla Confederazione.',sourceIds:['programme40289']},{question:'Quando va presentata la domanda d’incentivo per il risanamento edilizio?',answer:'La domanda deve essere presentata di principio prima dell’inizio dei lavori; i contributi cantonali sono inoltre soggetti alle condizioni e ai crediti disponibili del programma.',sourceIds:['programme40289']}],sources:[...sources]};
