import type { CantonGuide } from '../types';

const sources = [
  { id: 'ju-programme', authority: 'Republic and Canton of Jura', title: 'Buildings Programme – 2026 funding status', url: 'https://www.jura.ch/fr/Autorites/Administration/DEC/SDT/Energie/Subventions/Programme-Batiments/Programme-Batiments.html' },
  { id: 'ju-energy-law', authority: 'Republic and Canton of Jura', title: 'Energy Ordinance, own-electricity rule', url: 'https://rsju.jura.ch/fr/viewdocument.html?download=1&id=38231&idn=20131' },
  { id: 'ju-solar-permit', authority: 'Republic and Canton of Jura', title: 'Solar panels – planning permission', url: 'https://www.jura.ch/fr/Autorites/Administration/DEC/SDT/Permis-de-construire/Panneaux-solaires/Panneaux-solaires.html' },
  { id: 'ju-jurac', authority: 'Republic and Canton of Jura', title: 'JURAC – electronic planning application portal', url: 'https://www.jura.ch/fr/Autorites/JURAC/Requerants-Auteurs-du-projet/JURAC-Requerants-auteurs-du-projet.html' },
  { id: 'ju-foerderportal', authority: 'Cantonal energy funding service', title: 'Funding portal for cantonal programmes', url: 'https://portal.energie-foerderung.ch' },
  { id: 'ju-pronovo', authority: 'Pronovo Ltd on behalf of the Swiss Confederation', title: 'Frequently asked questions about the one-off payment and Swiss solar funding', url: 'https://pronovo.ch/de/foerderung/photovoltaik/haeufige-fragen/' },
] as const;

export const guide: CantonGuide = {
  id: 'jura', path: '/en/solar-panels-jura', canton: 'Jura', title: 'Solar panels in Jura 2026: funding and rules | PvPro.ch',
  description: 'Solar power in Jura: funding status in September 2026, own generation for new buildings, Pronovo, notification procedures and JURAC.',
  h1: 'Solar panels in Jura: funding and rules – September 2026 status',
  intro: ['In Jura, the position as at 15 September 2026 is what matters. The regular Buildings Programme budget is largely exhausted, and M-01 has a waiting list.', 'Check Pronovo and any remaining funds from the Incentive Programme separately. New buildings must generate 10 W/m² of energy reference area, capped at 30 kW. A notification may be sufficient for some systems; the municipality decides which procedure applies.'],
  quickFacts: [
    { value: 'Check separately', label: 'Pronovo / Confederation: current solar funding', sourceIds: ['ju-pronovo'] },
    { value: 'Waiting list', label: 'M-01 building envelope', sourceIds: ['ju-programme'] },
    { value: 'Check remaining funds', label: 'Incentive Programme: current status', sourceIds: ['ju-programme'] },
  ],
  sections: [
    { id: 'foerderung', title: 'Which funding is still available?', paragraphs: [
      'According to the cantonal position as at 15 September 2026, the regular 2026 Buildings Programme budget is largely exhausted. M-01 has a waiting list; Pronovo and the Incentive Programme must be checked separately.',
      'Current federal funding for photovoltaic systems is administered by Pronovo. The regular one-off payment currently applies from 2 kW. Additional federal bonuses, for example for panel angle, parking areas or winter electricity, have their own conditions and cannot simply be added together as a single funding amount.',
      'The Incentive Programme and building measures funded exclusively by the Confederation must be considered separately from the regular cantonal budget. M-01 concerns the building envelope and is not general solar funding. An exhausted cantonal budget therefore does not mean that every other form of funding is also exhausted.',
    ], sourceIds: ['ju-programme', 'ju-pronovo'], module: { kind: 'funding-status', title: 'Jura funding status', intro: 'Status: 15 September 2026. Check again before placing an order and starting construction.', items: [
      { title: 'Pronovo / Confederation', text: 'Check current federal photovoltaic funding separately. The one-off payment and any federal bonuses are subject to their respective conditions.', detail: 'One-off payment currently from 2 kW; optional bonuses are not added automatically.', value: 'Check separately', sourceIds: ['ju-pronovo'] },
      { title: 'Incentive Programme', text: 'Any remaining Incentive Programme funds must be assessed separately from the regular Buildings Programme budget. Check the current amount before placing an order.', value: 'Check remaining funds', sourceIds: ['ju-programme'] },
      { title: 'M-01 building envelope', text: 'M-01 concerns the building envelope, not general photovoltaic funding. This measure currently has a waiting list.', value: 'Waiting list', sourceIds: ['ju-programme'] },
    ] } },
    { id: 'jahresbudget', title: 'Why the current status matters more than the annual budget', paragraphs: ['The overall programme started 2026 with CHF 3.893 million: about CHF 1.18 million came from the Canton and CHF 2.713 million from the Confederation.', 'This breakdown describes the budget at the start of the year. It does not mean that the same amount is still available in September. The current information for the relevant programme therefore matters, not the old brochure from the beginning of the year.'], sourceIds: ['ju-programme'] },
    { id: 'neubau', title: 'Own electricity in new buildings', paragraphs: ['New buildings in Jura are subject to an own-generation requirement of 10 W/m² of energy reference area, capped at 30 kW.', 'The energy reference area is the floor area used for the building’s energy calculation. The rule concerns on-site electricity generation and does not automatically impose a general solar requirement on every existing home.', 'The units are straightforward: W/m² describes the required capacity per square metre of energy reference area, while kW is the system’s total capacity. Whether the requirement is met and which solution is suitable should be addressed early in the design of the new building.'], sourceIds: ['ju-energy-law'] },
    { id: 'bewilligung', title: 'Notification or planning application?', paragraphs: ['No, planning permission is not always required. Where the conditions under federal law are met, some solar systems can proceed by notification to the municipality.', 'A notification informs the municipality instead of submitting a full planning application. The municipality decides whether an ordinary procedure is required.', 'If a planning application is necessary, JURAC is used. JURAC is the Canton’s electronic planning application portal.'], sourceIds: ['ju-solar-permit', 'ju-jurac'] },
    { id: 'vor-bestellung', title: 'What to check before ordering', paragraphs: ['Clarify funding, procedure and municipal requirements before ordering. Applications for the relevant building programmes must generally be submitted before the funded work begins.', 'This avoids commissioning work before the current funding status or the required procedure has been established.', 'Use portal.energie-foerderung.ch for applications to the cantonal building programmes. It is separate from the JURAC planning portal and from federal photovoltaic funding through Pronovo.'], bullets: ['Pronovo and the current one-off payment for your system', 'current cantonal status of building programmes and the Incentive Programme', 'municipality: notification procedure or ordinary planning application', 'planning process and JURAC if an application is required', 'funding application before the funded work begins'], sourceIds: ['ju-programme', 'ju-solar-permit', 'ju-jurac', 'ju-pronovo', 'ju-foerderportal'] },
    { id: 'kosten', title: 'What does a solar installation cost here?', paragraphs: ['The Canton does not publish a fixed price for solar installations. The roof, system size, electrical work and equipment are decisive.', 'The final price depends on the specific building and the required scope of work. Compare several quotes for the same project and assess funding conditions separately from investment costs.'], bullets: ['roof area and shape', 'system size and capacity', 'scaffolding, access and site work', 'electrical work, meter and grid connection', 'inverter', 'battery storage', 'self-consumption and consumption profile', 'installer’s scope of work and warranties'], sourceIds: ['ju-programme', 'ju-pronovo'] },
  ],
  faqs: [
    { question: 'Is there an own-electricity requirement for new buildings in Jura?', answer: 'Yes. New buildings must generate their own electricity. This does not create a general solar requirement for existing homes.', sourceIds: ['ju-energy-law'] },
    { question: 'How much own electricity must a new building produce?', answer: 'The minimum capacity is 10 W/m² of energy reference area. No more than 30 kW can be required under this rule.', sourceIds: ['ju-energy-law'] },
    { question: 'Is the 2026 funding budget still available?', answer: 'According to the cantonal position as at 15 September 2026, the regular Buildings Programme budget is largely exhausted. The CHF 3.893 million available at the start of the year is therefore not evidence that funds remain available today.', sourceIds: ['ju-programme'] },
    { question: 'What does the M-01 waiting list mean?', answer: 'M-01 currently has a waiting list. M-01 supports the building envelope and is not general photovoltaic funding.', sourceIds: ['ju-programme'] },
    { question: 'Must I apply before construction starts?', answer: 'Yes. Relevant building programme applications must generally be submitted before the funded work begins. Check the current status and conditions before commissioning the work.', sourceIds: ['ju-programme'] },
    { question: 'Do solar panels always require planning permission?', answer: 'No. A notification to the municipality may be sufficient where the applicable conditions are met. The municipality checks whether an ordinary planning procedure is needed.', sourceIds: ['ju-solar-permit'] },
    { question: 'Who decides which procedure applies?', answer: 'The municipality decides whether a notification is sufficient or an ordinary procedure is required. Clarify this with the responsible municipality before work starts.', sourceIds: ['ju-solar-permit'] },
    { question: 'What is JURAC?', answer: 'JURAC is the electronic portal for cantonal planning applications. If your solar project requires a planning application, it is submitted there.', sourceIds: ['ju-jurac'] },
    { question: 'What is Pronovo, and from what capacity does the one-off payment apply?', answer: 'Pronovo administers current federal funding for photovoltaic systems. The regular one-off payment currently applies from a minimum capacity of 2 kW.', sourceIds: ['ju-pronovo'] },
    { question: 'Can I simply add cantonal contributions and federal bonuses together?', answer: 'No. Pronovo funding, cantonal programmes and optional federal bonuses must each be checked against their own conditions. No flat-rate total is guaranteed.', sourceIds: ['ju-programme', 'ju-pronovo'] },
    { question: 'What is the energy reference area?', answer: 'It is the floor area used as the basis for the building’s energy calculation.', sourceIds: ['ju-energy-law'] },
  ], sources: [...sources],
};
