import type { CantonGuide } from '../types';
const sources=[
 {id:'lu-keng',authority:'Canton of Lucerne, Environment and Energy',title:'Cantonal Energy Act at a glance – Canton of Lucerne',url:'https://uwe.lu.ch/Energiegesetz/KEnG_kompakt'},
 {id:'lu-foerderprogramme',authority:'Canton of Lucerne, Environment and Energy',title:'Energy funding programmes – Canton of Lucerne',url:'https://uwe.lu.ch/themen/energie/foerderprogramme'},
 {id:'lu-even',authority:'Canton of Lucerne, Environment and Energy',title:'Energy compliance documents from 1 January 2026 – Canton of Lucerne',url:'https://uwe.lu.ch/Energiegesetz/Energienachweise_ab_Anfang_2026'},
 {id:'lu-solar',authority:'Canton of Lucerne, Environment and Energy',title:'Solar energy – Canton of Lucerne, Environment and Energy',url:'https://uwe.lu.ch/themen/energie/erneuerbare_energien/Solar'},
] as const;
export const guide:CantonGuide={id:'luzern',path:'/en/solar-panels-lucerne',canton:'Lucerne',title:'Solar panels in Lucerne 2026: duties, funding and quotes | PvPro.ch',description:'Rules for new builds and roof renovations in Lucerne: own electricity, the replacement levy, federal funding and comparable solar quotes.',h1:'Solar panels in Lucerne: rules, funding and quotes for 2026',intro:['New buildings and certain roof renovations in the Canton of Lucerne are subject to clear own-electricity requirements. This guide explains what applies to your project and which funding routes are relevant.','Since 1 March 2025, it has been particularly important to distinguish a new build or roof renovation from repair and maintenance. Since 2026, energy compliance documentation has been handled through the digital EVEN platform.'],quickFacts:[{value:'Since 1 Mar 2025',label:'own electricity for new builds and roof renovations',sourceIds:['lu-keng']},{value:'Max. CHF 1,000',label:'replacement levy for each missing kW',sourceIds:['lu-keng']},{value:'Solar funding',label:'Confederation / Pronovo',sourceIds:['lu-foerderprogramme']},{value:'2026',label:'energy compliance via EVEN',sourceIds:['lu-even']}],ctaAfterSection:'dach-check',sections:[
 {id:'dach-check',title:'New build, roof renovation or repair: what applies to my roof?',paragraphs:['Since 1 March 2025, own-electricity generation has been relevant in the Canton of Lucerne for new buildings and existing buildings undergoing a roof renovation. The first step is therefore to classify the planned work correctly.'],sourceIds:['lu-keng','lu-solar'],module:{kind:'roof-duty-check',title:'What applies to my roof?',intro:'Classify the project, then check whether own generation meets the requirement or whether a replacement levy must be considered.',items:[
  {title:'New building',value:'Own-electricity rule',text:'For a new building, make appropriate use of its electricity-generation potential and check the own-electricity rule for the project.',sourceIds:['lu-keng']},
  {title:'Genuine roof renovation',value:'Own-electricity rule',text:'For an existing building undergoing a roof renovation, its electricity-generation potential must likewise be used appropriately.',sourceIds:['lu-keng']},
  {title:'Repair / maintenance',value:'Not automatically a renovation',text:'Do not automatically treat repair and maintenance alone as a comprehensive roof renovation; assess the specific work against the cantonal implementation guidance.',sourceIds:['lu-solar','lu-keng']},
  {title:'Requirement met',value:'Own electricity',text:'If the requirement is met, continue planning with the proposed photovoltaic system or other own generation.',sourceIds:['lu-keng']},
  {title:'Requirement not met',value:'Replacement levy',text:'If the requirement is not met, consider a replacement levy. It is capped at CHF 1,000 per kW of the minimum required capacity that is not installed.',sourceIds:['lu-keng']},
 ]}},
 {id:'even',title:'2026 energy compliance: processing through EVEN',paragraphs:['Clarify with the specialist planning firm who will prepare the energy compliance documents for your project and handle the digital process. This keeps the technical design and documentation aligned.'],sourceIds:['lu-even'],notice:{title:'EVEN from 1 January 2026',text:'Since 1 January 2026, energy compliance documentation in the Canton of Lucerne has been processed through the digital EVEN platform.',status:'important'}},
 {id:'foerderung',title:'Solar funding from the Confederation and Pronovo',paragraphs:['The Confederation, through Pronovo, is responsible for regular funding of photovoltaic systems. The Lucerne programmes listed here do not provide a general cantonal contribution for solar installations.','Ask for expected funding to be shown separately in the quote. For a transparent comparison, first identify the system price before funding is deducted and then the basis for the assumed support. A possible replacement levy is not funding but a separate comparison item.'],sourceIds:['lu-foerderprogramme','lu-keng']},
 {id:'vorhaben',title:'Plan roof work and the solar installation together',paragraphs:['Describe the planned roof work to the specialist firm as precisely as possible. Photos, existing plans and a description of the roof construction help classify the project under the cantonal implementation guidance. The label “roof work” alone says little about the actual intervention.','Then coordinate work on the building with installation of the solar panels. Ask which scaffolding and ancillary work is already included in the roofing quote and which is offered additionally for the solar system. This avoids comparing prices with different scopes of work.'],sourceIds:['lu-solar','lu-keng']},
 {id:'kosten',title:'What does a solar installation cost in Lucerne?',paragraphs:['A standard system price is no substitute for a quote for your building. The following items should be clearly included or expressly excluded.','Lucerne adds another point to the comparison: the technical solution and any replacement levy should not be compared using different project assumptions. Request quotes on the same basis.','PvPro.ch allows homeowners to compare up to three suitable solar quotes free of charge and without obligation.'],bullets:['roof area and geometry','access and scaffolding','integration into the building','electrical distribution board','battery storage','ancillary work'],sourceIds:['lu-keng','lu-solar']},
 {id:'offerten-pruefen',title:'Which differences between quotes matter?',paragraphs:['Check not only the final price but also the proposed system and division of work. Is a battery optional or already included? Are electrical work and changes to the distribution board included? Which items are charged according to actual time and materials?','Where quotes differ, ask for a brief explanation and a comparable alternative. Only when the system, building work and optional equipment are classified consistently can you judge whether a price difference arises from scope or from the quote itself.'],sourceIds:[]},
],faqs:[
 {question:'Does Lucerne’s own-electricity requirement also apply to a roof renovation?',answer:'Yes. New buildings and existing buildings undergoing roof renovation must make appropriate use of their electricity-generation potential; a replacement levy is an alternative.',sourceIds:['lu-keng']},
 {question:'How high can the replacement levy be?',answer:'It is capped at CHF 1,000 per kW of the minimum required capacity that is not installed.',sourceIds:['lu-keng']},
 {question:'Is every small roof repair automatically a roof renovation?',answer:'No. Repair and maintenance alone must not automatically be equated with a comprehensive roof renovation; assess the specific project against the cantonal implementation guidance.',sourceIds:['lu-solar','lu-keng']},
 {question:'Does the Canton of Lucerne directly fund ordinary photovoltaic systems?',answer:'Regular photovoltaic funding is provided by the Confederation through Pronovo; cantonal programmes must not be presented as a general solar contribution.',sourceIds:['lu-foerderprogramme']},
 {question:'What changes for energy compliance in 2026?',answer:'Since 1 January 2026, energy compliance documentation in the Canton of Lucerne has been processed through the digital EVEN platform.',sourceIds:['lu-even']},
],sources:[...sources]};
