import type { CantonGuide } from '../types';
export const guide:CantonGuide={id:'neuenburg',path:'/en/solar-panels-neuchatel',canton:'Neuchâtel',title:'Solar panels in Neuchâtel 2026: requirements and batteries | PvPro.ch',description:'15 W/m² for new buildings and new storage funding from March 2026: the key photovoltaic rules in Neuchâtel and how to compare quotes.',h1:'Solar panels in Neuchâtel: requirements and battery storage in 2026',intro:['Neuchâtel combines clear own-electricity requirements for new buildings with a new cantonal subsidy for photovoltaic batteries. It is essential to keep the two instruments separate.'],quickFacts:[{value:'15 W/m² ERA',label:'own electricity in new buildings; at least 1 kW installed capacity',sourceIds:['ne-relcen']},{value:'CHF 800 + CHF 80/kWh',label:'cantonal battery contribution subject to funding conditions',sourceIds:['ne-battery-order','ne-battery-page']},{value:'from 1 Mar 2026',label:'cantonal funding for photovoltaic batteries',sourceIds:['ne-battery-order','ne-battery-page']},{value:'max. 50%',label:'share of total investment covered by the battery contribution',sourceIds:['ne-battery-order','ne-battery-page']}],ctaAfterSection:'batterycheck',sections:[
 {id:'neubaupflicht',title:'Distinguishing own electricity in new buildings from battery storage',paragraphs:['The two minimum values for new buildings apply together: the energy reference area, also called ERA, determines the required capacity. At the same time, a minimum capacity applies independently of this area-based calculation.','This is a requirement to generate electricity on site, not a requirement to buy a battery. Cantonal storage funding is a separate instrument and may also be relevant to an existing photovoltaic system.'],sourceIds:['ne-relcen']},
 {id:'batterycheck',title:'Does your battery qualify for the cantonal programme?',paragraphs:['Check the following conditions together. The contribution formula alone is not a funding commitment; in particular, not all installed storage capacity can necessarily be taken into account.'],sourceIds:['ne-battery-order','ne-battery-page'],module:{kind:'battery-eligibility',title:'2026 battery funding check',intro:'Contribution formula: CHF 800 per installation + CHF 80/kWh of installed storage capacity.',items:[
  {title:'Capacity >3 kWh',text:'The battery must have a capacity greater than 3 kWh.',value:'>3 kWh',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Eligible capacity',text:'Eligible capacity is limited to twice the installed photovoltaic capacity in kWp.',detail:'Maximum 2 × installed photovoltaic capacity in kWp',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Contribution cap',text:'The total contribution may not exceed 50% of the total investment.',value:'max. 50%',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Building, solar system and self-consumption',text:'A residential building, an on-site photovoltaic system and self-consumption of part of the solar electricity are required.',sourceIds:['ne-battery-order','ne-battery-page']},
  {title:'Commissioned from 1 March 2026',text:'Battery storage commissioned from 1 March 2026 is eligible. The corresponding electrical safety certificate is decisive.',detail:'Electrical safety certificate is decisive',sourceIds:['ne-battery-order','ne-battery-page']},
 ]},notice:{title:'Check all criteria together',text:'The contribution formula alone does not establish eligibility. Capacity, photovoltaic output, investment share, building, self-consumption and the electrical safety certificate all form part of the full check.',status:'important'}},
 {id:'bestehende-pv',title:'Adding a battery to an existing photovoltaic system',paragraphs:['An existing photovoltaic system does not rule out the battery subsidy. Funding also applies with an existing photovoltaic system, provided it is on site, some solar electricity is self-consumed and the remaining conditions are met.','The distinction therefore remains important: the requirement of 15 W/m² ERA and at least 1 kW applies to new buildings. The battery check, by contrast, may also concern an addition to an existing photovoltaic system.'],bullets:['An existing on-site photovoltaic system is permitted.','Some of the solar electricity must be self-consumed.','The other battery funding check conditions continue to apply.'],sourceIds:['ne-battery-order','ne-battery-page','ne-relcen']},
 {id:'nachweis',title:'Which details matter for the funding check?',paragraphs:['For assessment, clearly show installed photovoltaic capacity in kWp, installed storage capacity and total investment separately. This allows eligible capacity to be checked against photovoltaic capacity and the contribution cap to be understood.','For storage commissioned from 1 March 2026, the corresponding electrical safety certificate is decisive. The residential building, on-site photovoltaic system and self-consumption must also be considered together with the other funding conditions.'],bullets:['Consider installed photovoltaic capacity in kWp and installed storage capacity separately.','Show total investment for the 50% cap.','Include the electrical safety certificate and self-consumption in the check.'],sourceIds:['ne-battery-order','ne-battery-page']},
 {id:'kosten',title:'Cost of a photovoltaic system with battery storage',paragraphs:['Costs do not depend on photovoltaic capacity alone. For a battery, usable capacity, inverter compatibility and integration into the existing or new system are particularly important. The cantonal contribution is a funding rule, not a guarantee of a particular financial return.','Compare quotes using the same project basis. Battery sizing should be clear separately from photovoltaic sizing so that output, capacity and electrical work are not conflated.'],bullets:['usable storage capacity and suitable battery size','inverter and technical compatibility','distribution board and other electrical work','integration into a new or existing photovoltaic system'],sourceIds:['ne-battery-order','ne-battery-page']},
 {id:'offerten',title:'Comparing suitable quotes for solar and storage',paragraphs:['PvPro helps homeowners compare up to three suitable photovoltaic quotes and, if requested, storage solutions without obligation.','Ask for photovoltaic output, installed and usable storage capacity, and electrical work to be listed separately. This lets you assess the battery funding check and technical implementation on the same basis.'],sourceIds:[]},
],faqs:[
 {question:'How much own electricity must a new building in Neuchâtel generate?',answer:'For new buildings, cantonal energy law requires at least 15 W/m² of energy reference area, or ERA, and at least 1 kW of installed capacity.',sourceIds:['ne-relcen']},
 {question:'When did cantonal funding for photovoltaic batteries begin?',answer:'Battery storage commissioned from 1 March 2026 is eligible; the corresponding electrical safety certificate is decisive.',sourceIds:['ne-battery-order','ne-battery-page']},
 {question:'How is the battery subsidy calculated?',answer:'The contribution is CHF 800 per installation plus CHF 80 per kWh of installed storage capacity and may not exceed 50% of the total investment.',sourceIds:['ne-battery-order','ne-battery-page']},
 {question:'What battery size is funded?',answer:'The battery must have a capacity greater than 3 kWh; eligible capacity is limited to twice the installed photovoltaic capacity in kWp.',sourceIds:['ne-battery-order','ne-battery-page']},
 {question:'Can a battery be added to an existing photovoltaic system?',answer:'Yes. Funding also applies with an existing photovoltaic system, provided it is on site, some solar electricity is self-consumed and the remaining conditions are met.',sourceIds:['ne-battery-order','ne-battery-page']},
],sources:[
 {id:'ne-relcen',authority:'Canton of Neuchâtel',title:'Implementing Regulation for the Cantonal Energy Act (RELCEn)',url:'https://rsn.ne.ch/DATA/program/books/RSN2021/20214/htm/74010.htm'},
 {id:'ne-battery-order',authority:'Canton of Neuchâtel',title:'740.13: Order on subsidies for photovoltaic electricity storage batteries (ASBaSt), 4 February 2026',url:'https://rsn.ne.ch/DATA/program/books/rsne/htm/740.13.htm'},
 {id:'ne-battery-page',authority:'Canton of Neuchâtel',title:'Subsidies for domestic photovoltaic electricity storage batteries | ne.ch',url:'https://www.ne.ch/themes/energie-et-environnement/energie/subventions-pour-les-batteries-domestiques-de-stockage-delectricite-photovoltaique'},
]};
